// java.sql — JDBC 4.3 Core Interfaces (driver-agnostic)
// Mirrors: java.sql.Connection, Statement, ResultSet, DriverManager
//
// This file declares the JDBC abstraction (interfaces) and dispatches
// DriverManager_getConnection by URL scheme. Concrete drivers
// (e.g. MySQL wire protocol, future SQLite-pure-SS / PostgreSQL) provide
// implementations under lib/com/<vendor>/jdbc.ss.
//
// D133: SQLite C link removed — interfaces hold no driver-specific shape.
// D134: MySQL wire-protocol driver registered (jdbc:mysql://). The cycle
// jdbc.ss ↔ sql.ss is handled by bootstrap/main.ss resolveInner visited set.
// See docs/3-decisions/D133-sqlite-c-link-elimination.md
// See docs/3-decisions/D134-jdbc-mysql-wire-protocol.md §A.5

// ── ResultSet ────────────────────────────────────────────────
// Driver controls internal row storage (socket buffer / pre-fetch /
// streaming cursor). Callers iterate via next() and column getters.

interface ResultSet {
    function next(): int
    function getString(col: string): string
    function getInt(col: string): int
    function getLong(col: string): int
    function getDouble(col: string): double
    function getBoolean(col: string): int
    function close()
}

// ── JDBC 4.3 §Statement constants — D138 §核心原则 6 ─────────
// Mirror java.sql.Statement.RETURN_GENERATED_KEYS / NO_GENERATED_KEYS. Passed
// to Connection.prepareStatement(sql, autoGeneratedKeys) to opt in / out of
// generated key retrieval. MySQL wire protocol returns lastInsertId for every
// INSERT regardless, so these constants are no-op for the MySQL driver — kept
// for JDBC spec parity (PostgreSQL / SQLite drivers reading the parameter).
const RETURN_GENERATED_KEYS = 1
const NO_GENERATED_KEYS = 2

// ── Statement ────────────────────────────────────────────────
// D138 Phase 2: getGeneratedKeys() returns a ResultSet over auto-increment ids
// produced by the most recent executeUpdate. getLastInsertId() is the SS
// shortcut around the ResultSet wrapping (single int, no row iteration). MySQL
// generates one id per INSERT (multi-row VALUES (...),(...),(...) reports the
// first id; subsequent ids are first + 1, first + 2, ... by protocol contract).

interface Statement {
    function executeQuery(sql: string): ResultSet
    function executeUpdate(sql: string): int
    function execute(sql: string): int
    function getGeneratedKeys(): ResultSet
    function getLastInsertId(): int
    function close()
}

// ── PreparedStatement ────────────────────────────────────────
// JDBC 4.3 PreparedStatement (driver-agnostic). Bound to a parameterized SQL
// at Connection.prepareStatement(sql) time; setXxx(idx, val) binds positional
// params (idx from 1, JDBC convention). executeQuery() / executeUpdate() use
// the bound sql + bound params via the binary protocol.
//
// D136 §A.5 retcon: standalone interface (not `extends Statement`). SS parser
// has no interface-extends syntax (parseInterfaceDecl) and no method overload
// support, so the JDBC spec historical `PreparedStatement extends Statement`
// shape is unimplementable here — and per JDBC 4.3 §A.4.2, calling
// Statement.execute(String) on a PreparedStatement throws SQLException anyway.
// Standalone interface matches the spec's effective semantics.

interface PreparedStatement {
    function setInt(idx: int, val: int)
    function setLong(idx: int, val: int)
    function setString(idx: int, val: string)
    function setDouble(idx: int, val: double)
    function setBoolean(idx: int, val: int)
    function setNull(idx: int)
    function executeQuery(): ResultSet
    function executeUpdate(): int
    function getGeneratedKeys(): ResultSet
    function getLastInsertId(): int
    function close()
}

// ── Connection ───────────────────────────────────────────────
// D138 Phase 2: prepareStatement is overloaded by arity. The 1-arg form is the
// legacy entry; the 2-arg form takes RETURN_GENERATED_KEYS / NO_GENERATED_KEYS
// to declare intent for generated-key retrieval (drivers that gate id
// retrieval read the flag; MySQL returns ids unconditionally so the flag is
// informational only).

interface Connection {
    function createStatement(): Statement
    function prepareStatement(sql: string): PreparedStatement
    function prepareStatement(sql: string, autoGeneratedKeys: int): PreparedStatement
    function setAutoCommit(auto: int)
    function commit()
    function rollback()
    function close()
    function isClosed(): int
}

// ── DriverManager ────────────────────────────────────────────
// D134 §A.5: hardcoded scheme dispatch. Future drivers add an else-if branch.

import { getMysqlConnection } from "@/lib/com/mysql/jdbc"

class DriverManager

function DriverManager_getConnection(url: string): Connection {
    if (url.startsWith("jdbc:mysql://") == 1) {
        return getMysqlConnection(url)
    }
    println(`JDBC: no driver registered for url: ${url}`)
    exit(1)
}

// ── SQLException Hierarchy — JDBC 4.3 §13.1 ──────────────────
// Mirrors java.sql.SQLException complete class tree:
//
//   SQLException (extends Error, adds sqlState + errorCode)
//   ├── SQLNonTransientException                 ← retry will not succeed
//   │   ├── SQLNonTransientConnectionException   SQLState class 08 / 28
//   │   ├── SQLIntegrityConstraintViolationException SQLState class 23
//   │   ├── SQLSyntaxErrorException              SQLState class 42
//   │   ├── SQLDataException                     SQLState class 22
//   │   └── SQLFeatureNotSupportedException      SQLState class 0A
//   ├── SQLTransientException                    ← retry may succeed
//   │   ├── SQLTransientConnectionException      SQLState class 08 (transient)
//   │   ├── SQLTransactionRollbackException      SQLState class 40
//   │   └── SQLTimeoutException                  query timeout
//   └── SQLRecoverableException                  ← reconnect may succeed
//
// Constructor positional args follow Error base class convention (prelude.ss
// `class Error { message: string }` + tests/phase5/error_class.ss):
//   new SQLNonTransientConnectionException(message, sqlState, errorCode)
// (3 args, all subclasses identical — extra fields declared on SQLException
// transit to descendants via SS class extends chain — D025 vtable + bootstrap
// classParents lookup, exercised by tests/phase5/typed_catch.ss Test 4).
//
// Empty-body subclasses are intentional — JDBC subclasses carry no extra
// state; type identity alone routes catch-clause dispatch via
// bootstrap/gen/stmts/stmts_exc.ss:99 genCatchClauses.

class SQLException extends Error {
    sqlState: string
    errorCode: int
}

class SQLNonTransientException extends SQLException {}
class SQLTransientException extends SQLException {}
class SQLRecoverableException extends SQLException {}

class SQLNonTransientConnectionException extends SQLNonTransientException {}
class SQLIntegrityConstraintViolationException extends SQLNonTransientException {}
class SQLSyntaxErrorException extends SQLNonTransientException {}
class SQLDataException extends SQLNonTransientException {}
class SQLFeatureNotSupportedException extends SQLNonTransientException {}

class SQLTransientConnectionException extends SQLTransientException {}
class SQLTransactionRollbackException extends SQLTransientException {}
class SQLTimeoutException extends SQLTransientException {}
