// gen_rt_system.ss — Runtime filesystem, network, exception, and SQLite operations

// ── Filesystem ────────────────────────────────────────────────

function emitRuntimeFS() {
    // ss_mkdir
    emitIR("define i32 @ss_mkdir(ptr %path) {")
    irCall("result", "i32", "mkdir", "ptr %path, i32 493")
    irRet("i32", "%result")
    emitIR("}")
    emitIR("")

    // ss_mkdirp — recursive mkdir
    emitIR("define i32 @ss_mkdirp(ptr %path) {")
    irLabel("entry")
    irCall("len", "i64", "strlen", "ptr %path")
    irAdd("alloc", "i64", "%len", "1")
    irCall("buf", "ptr", "malloc", "i64 %alloc")
    irCall("_1", "ptr", "memcpy", "ptr %buf, ptr %path, i64 %len")
    irGEP("term", "i8", "%buf", "%len")
    irStore("i8", "0", "%term")
    irAlloca("i", "i64", 8)
    irStore("i64", "1", "%i")
    irBr("loop")
    irLabel("loop")
    irLoad("ci", "i64", "%i")
    irICmp("cond", "sle", "i64", "%ci", "%len")
    irBrCond("cond", "body", "final")
    irLabel("body")
    irGEP("cp", "i8", "%buf", "%ci")
    irLoad("ch", "i8", "%cp")
    irICmp("is_slash", "eq", "i8", "%ch", "47")
    irICmp("is_end", "eq", "i64", "%ci", "%len")
    irOr("should_mkdir", "i1", "%is_slash", "%is_end")
    irBrCond("should_mkdir", "do_mkdir", "next")
    irLabel("do_mkdir")
    irStore("i8", "0", "%cp")
    irCall("_2", "i32", "mkdir", "ptr %buf, i32 493")
    irStore("i8", "%ch", "%cp")
    irBr("next")
    irLabel("next")
    irAdd("ni", "i64", "%ci", "1")
    irStore("i64", "%ni", "%i")
    irBr("loop")
    irLabel("final")
    irCallVoid("free", "ptr %buf")
    irRet("i32", "0")
    emitIR("}")
    emitIR("")

    // ss_fileExists
    emitIR("define i32 @ss_fileExists(ptr %path) {")
    irAlloca("statbuf", "[144 x i8]", 8)
    irCall("rc", "i32", "stat", "ptr %path, ptr %statbuf")
    irICmp("exists", "eq", "i32", "%rc", "0")
    irZext("result", "i1", "%exists", "i32")
    irRet("i32", "%result")
    emitIR("}")
    emitIR("")

    // ss_fileSize
    emitIR("define i64 @ss_fileSize(ptr %path) {")
    irLabel("entry")
    irAlloca("statbuf", "[144 x i8]", 8)
    irCall("rc", "i32", "stat", "ptr %path, ptr %statbuf")
    irICmp("failed", "ne", "i32", "%rc", "0")
    irBrCond("failed", "fail", "ok")
    irLabel("ok")
    irGEP("sizep", "i8", "%statbuf", "48")
    irLoad("size", "i64", "%sizep")
    irRet("i64", "%size")
    irLabel("fail")
    irRet("i64", "-1")
    emitIR("}")
    emitIR("")

    // ss_removeFile
    emitIR("define i32 @ss_removeFile(ptr %path) {")
    irCall("result", "i32", "remove", "ptr %path")
    irRet("i32", "%result")
    emitIR("}")
    emitIR("")

    // ss_renameFile
    emitIR("define i32 @ss_renameFile(ptr %oldpath, ptr %newpath) {")
    irCall("result", "i32", "rename", "ptr %oldpath, ptr %newpath")
    irRet("i32", "%result")
    emitIR("}")
    emitIR("")

    // ss_listDir (dynamic buffer)
    emitIR("define ptr @ss_listDir(ptr %path) {")
    irLabel("entry")
    irCall("dp", "ptr", "opendir", "ptr %path")
    irICmp("isnull", "eq", "ptr", "%dp", "null")
    irBrCond("isnull", "fail", "init")
    irLabel("fail")
    irCall("empty", "ptr", "ss_rc_strdup", "ptr @.rt.str.empty")
    irRet("ptr", "%empty")
    irLabel("init")
    irAlloca("bufp", "ptr", 8)
    irAlloca("cap", "i64", 8)
    irCall("r0", "ptr", "ss_rc_alloc", "i64 4096, i32 0")
    irStore("ptr", "%r0", "%bufp")
    irStore("i64", "4096", "%cap")
    irAlloca("pos", "i64", 8)
    irStore("i64", "0", "%pos")
    irBr("loop")
    irLabel("loop")
    irCall("ent", "ptr", "readdir", "ptr %dp")
    irICmp("done", "eq", "ptr", "%ent", "null")
    irBrCond("done", "finish", "process")
    irLabel("process")
    irGEP("name", "i8", "%ent", "19")
    irCall("nlen", "i64", "strlen", "ptr %name")
    irLoad("cpos", "i64", "%pos")
    emitIR("  ; Skip . and ..")
    irLoad("c0", "i8", "%name")
    irICmp("is_dot", "eq", "i8", "%c0", "46")
    irBrCond("is_dot", "chk_dot", "copy")
    irLabel("chk_dot")
    irGEP("c1", "i8", "%name", "1")
    irLoad("c1v", "i8", "%c1")
    irICmp("is_dotdot", "eq", "i8", "%c1v", "46")
    irICmp("is_end1", "eq", "i8", "%c1v", "0")
    irOr("skip", "i1", "%is_dotdot", "%is_end1")
    irBrCond("skip", "loop", "copy")
    irLabel("copy")
    // ensure capacity for name + newline + null terminator
    irAdd("need", "i64", "%cpos", "%nlen")
    irAdd("need2", "i64", "%need", "2")
    irCall("cbuf", "ptr", "ss_rt_ensure_cap", "ptr %bufp, ptr %cap, i64 %need2")
    irGEP("dst", "i8", "%cbuf", "%cpos")
    irCall("_1", "ptr", "memcpy", "ptr %dst, ptr %name, i64 %nlen")
    irAdd("np1", "i64", "%cpos", "%nlen")
    irGEP("nlp", "i8", "%cbuf", "%np1")
    irStore("i8", "10", "%nlp")
    irAdd("np2", "i64", "%np1", "1")
    irStore("i64", "%np2", "%pos")
    irBr("loop")
    irLabel("finish")
    irCall("_2", "i32", "closedir", "ptr %dp")
    irLoad("fpos", "i64", "%pos")
    irLoad("fbuf", "ptr", "%bufp")
    irGEP("fterm", "i8", "%fbuf", "%fpos")
    irStore("i8", "0", "%fterm")
    irRet("ptr", "%fbuf")
    emitIR("}")
    emitIR("")

    // ss_timeMs
    emitIR("define i64 @ss_timeMs() {")
    irAlloca("ts", "[16 x i8]", 8)
    irCall("_1", "i32", "clock_gettime", "i32 1, ptr %ts")
    irLoad("sec", "i64", "%ts")
    irGEP("nsp", "i8", "%ts", "8")
    irLoad("nsec", "i64", "%nsp")
    irMul("ms_sec", "i64", "%sec", "1000")
    irSDiv("ms_ns", "i64", "%nsec", "1000000")
    irAdd("result", "i64", "%ms_sec", "%ms_ns")
    irRet("i64", "%result")
    emitIR("}")
    emitIR("")

    // ss_timeUnix
    emitIR("define i64 @ss_timeUnix() {")
    irCall("result", "i64", "time", "ptr null")
    irRet("i64", "%result")
    emitIR("}")
    emitIR("")
}

// ── Network ───────────────────────────────────────────────────

function emitRuntimeNet() {
    // ss_tcpListen
    emitIR("define i32 @ss_tcpListen(i32 %port) {")
    irLabel("entry")
    irCall("fd", "i32", "socket", "i32 2, i32 1, i32 0")
    irICmp("bad", "slt", "i32", "%fd", "0")
    irBrCond("bad", "fail", "setsock")
    irLabel("setsock")
    irAlloca("optval", "i32", 4)
    irStore("i32", "1", "%optval")
    irCall("_1", "i32", "setsockopt", "i32 %fd, i32 1, i32 2, ptr %optval, i32 4")
    irAlloca("addr", "[16 x i8]", 4)
    irCall("_2", "ptr", "memset", "ptr %addr, i32 0, i64 16")
    irStore("i16", "2", "%addr")
    irTrunc("port16", "i32", "%port", "i16")
    irCall("portn", "i16", "htons", "i16 %port16")
    irGEP("pptr", "i8", "%addr", "2")
    irStore("i16", "%portn", "%pptr")
    irCall("br", "i32", "bind", "i32 %fd, ptr %addr, i32 16")
    irICmp("bfail", "slt", "i32", "%br", "0")
    irBrCond("bfail", "close_fail", "do_listen")
    irLabel("do_listen")
    irCall("lr", "i32", "listen", "i32 %fd, i32 128")
    irICmp("lfail", "slt", "i32", "%lr", "0")
    irBrCond("lfail", "close_fail", "done")
    irLabel("done")
    irRet("i32", "%fd")
    irLabel("close_fail")
    irCall("_3", "i32", "close", "i32 %fd")
    irBr("fail")
    irLabel("fail")
    irRet("i32", "-1")
    emitIR("}")
    emitIR("")

    // ss_tcpAccept
    emitIR("define i32 @ss_tcpAccept(i32 %fd) {")
    irCall("client", "i32", "accept", "i32 %fd, ptr null, ptr null")
    irRet("i32", "%client")
    emitIR("}")
    emitIR("")

    // ss_tcpRead
    emitIR("define ptr @ss_tcpRead(i32 %fd, i32 %maxlen) {")
    irSext("maxlen64", "i32", "%maxlen", "i64")
    irAdd("alloc", "i64", "%maxlen64", "1")
    irCall("buf", "ptr", "ss_rc_alloc", "i64 %alloc, i32 0")
    irCall("nread", "i64", "read", "i32 %fd, ptr %buf, i64 %maxlen64")
    irICmp("neg", "slt", "i64", "%nread", "0")
    irSelect("safe", "neg", "i64", "0", "%nread")
    irGEP("term", "i8", "%buf", "%safe")
    irStore("i8", "0", "%term")
    irRet("ptr", "%buf")
    emitIR("}")
    emitIR("")

    // ss_tcpWrite
    emitIR("define i32 @ss_tcpWrite(i32 %fd, ptr %data) {")
    irCall("len", "i64", "strlen", "ptr %data")
    irCall("nwritten", "i64", "write", "i32 %fd, ptr %data, i64 %len")
    irTrunc("result", "i64", "%nwritten", "i32")
    irRet("i32", "%result")
    emitIR("}")
    emitIR("")

    // ss_tcpWriteBytes
    emitIR("define i32 @ss_tcpWriteBytes(i32 %fd, ptr %data, i32 %len) {")
    irSext("len64", "i32", "%len", "i64")
    irCall("nwritten", "i64", "write", "i32 %fd, ptr %data, i64 %len64")
    irTrunc("result", "i64", "%nwritten", "i32")
    irRet("i32", "%result")
    emitIR("}")
    emitIR("")

    // ss_tcpClose
    emitIR("define void @ss_tcpClose(i32 %fd) {")
    irCall("_1", "i32", "close", "i32 %fd")
    irRetVoid()
    emitIR("}")
    emitIR("")
}

// ── Exception handling ────────────────────────────────────────

function emitRuntimeExceptions() {
    // ss_throw: store message, longjmp if handler exists, else print+exit
    emitIR("define void @ss_throw(ptr %msg) {")
    irLabel("entry")
    irStore("ptr", "%msg", "@ss_exc_msg")
    irLoad("depth", "i32", "@ss_exc_depth")
    irICmp("has_handler", "sgt", "i32", "%depth", "0")
    irBrCond("has_handler", "do_jump", "no_handler")
    irLabel("do_jump")
    irSub("d1", "i32", "%depth", "1")
    irMul("offset", "i32", "%d1", "200")
    irSext("off64", "i32", "%offset", "i64")
    irGEP("bufptr", "i8", "@ss_jmpbuf", "%off64")
    irCallVoid("longjmp", "ptr %bufptr, i32 1")
    emitIR("  unreachable")
    irLabel("no_handler")
    irCall("_1", "ptr", "ss_string_concat", "ptr @.rt.str.uncaught, ptr %msg")
    emitIR("  call i32 @puts(ptr %_1)")
    irCallVoid("exit", "i32 1")
    emitIR("  unreachable")
    emitIR("}")
    emitIR("")
}

// ── SQLite bindings ───────────────────────────────────────────

function emitRuntimeSQLite() {
    // ss_sqlite3_open(path) → db pointer (as ptr)
    emitIR("define ptr @ss_sqlite3_open(ptr %path) {")
    irLabel("entry")
    irAlloca("dbpp", "ptr", 8)
    irCall("rc", "i32", "sqlite3_open", "ptr %path, ptr %dbpp")
    irICmp("ok", "eq", "i32", "%rc", "0")
    irBrCond("ok", "success", "fail")
    irLabel("success")
    irLoad("db", "ptr", "%dbpp")
    irRet("ptr", "%db")
    irLabel("fail")
    irRet("ptr", "null")
    emitIR("}")
    emitIR("")

    // ss_sqlite3_close(db)
    emitIR("define void @ss_sqlite3_close(ptr %db) {")
    irCall("_1", "i32", "sqlite3_close", "ptr %db")
    irRetVoid()
    emitIR("}")
    emitIR("")

    // ss_sqlite3_exec(db, sql) → 0 on success
    emitIR("define i32 @ss_sqlite3_exec(ptr %db, ptr %sql) {")
    irCall("rc", "i32", "sqlite3_exec", "ptr %db, ptr %sql, ptr null, ptr null, ptr null")
    irRet("i32", "%rc")
    emitIR("}")
    emitIR("")

    // ss_sqlite3_query(db, sql) → "col1\tcol2\nval1\tval2\n..." result string (dynamic buffer)
    emitIR("define ptr @ss_sqlite3_query(ptr %db, ptr %sql) {")
    irLabel("entry")
    irAlloca("stmtpp", "ptr", 8)
    irCall("rc", "i32", "sqlite3_prepare_v2", "ptr %db, ptr %sql, i32 -1, ptr %stmtpp, ptr null")
    irICmp("ok", "eq", "i32", "%rc", "0")
    irBrCond("ok", "prepared", "empty")
    irLabel("empty")
    irCall("e", "ptr", "ss_rc_strdup", "ptr @.rt.str.empty")
    irRet("ptr", "%e")
    irLabel("prepared")
    irLoad("stmt", "ptr", "%stmtpp")
    irCall("ncols", "i32", "sqlite3_column_count", "ptr %stmt")
    irAlloca("bufp", "ptr", 8)
    irAlloca("cap", "i64", 8)
    irCall("r0", "ptr", "ss_rc_alloc", "i64 4096, i32 0")
    irStore("ptr", "%r0", "%bufp")
    irStore("i64", "4096", "%cap")
    irAlloca("pos", "i64", 8)
    irStore("i64", "0", "%pos")
    // Write column headers
    irAlloca("ci", "i32", 4)
    irStore("i32", "0", "%ci")
    irBr("hdr.loop")
    irLabel("hdr.loop")
    irLoad("hci", "i32", "%ci")
    irICmp("hcond", "slt", "i32", "%hci", "%ncols")
    irBrCond("hcond", "hdr.body", "hdr.done")
    irLabel("hdr.body")
    irLoad("hci2", "i32", "%ci")
    // Add tab separator between columns
    irICmp("needtab", "sgt", "i32", "%hci2", "0")
    irBrCond("needtab", "hdr.tab", "hdr.name")
    irLabel("hdr.tab")
    irLoad("tp", "i64", "%pos")
    irAdd("tn", "i64", "%tp", "2")
    irCall("tbuf", "ptr", "ss_rt_ensure_cap", "ptr %bufp, ptr %cap, i64 %tn")
    irGEP("td", "i8", "%tbuf", "%tp")
    irStore("i8", "9", "%td")
    irAdd("tp1", "i64", "%tp", "1")
    irStore("i64", "%tp1", "%pos")
    irBr("hdr.name")
    irLabel("hdr.name")
    irCall("cname", "ptr", "sqlite3_column_name", "ptr %stmt, i32 %hci2")
    irCall("cnlen", "i64", "strlen", "ptr %cname")
    irLoad("cp2", "i64", "%pos")
    irAdd("hn", "i64", "%cp2", "%cnlen")
    irAdd("hn2", "i64", "%hn", "1")
    irCall("hbuf", "ptr", "ss_rt_ensure_cap", "ptr %bufp, ptr %cap, i64 %hn2")
    irGEP("cdst", "i8", "%hbuf", "%cp2")
    irCall("_2", "ptr", "memcpy", "ptr %cdst, ptr %cname, i64 %cnlen")
    irAdd("cp3", "i64", "%cp2", "%cnlen")
    irStore("i64", "%cp3", "%pos")
    irAdd("hci3", "i32", "%hci2", "1")
    irStore("i32", "%hci3", "%ci")
    irBr("hdr.loop")
    irLabel("hdr.done")
    // Add newline after headers
    irLoad("hp", "i64", "%pos")
    irAdd("hpn", "i64", "%hp", "2")
    irCall("hdbuf", "ptr", "ss_rt_ensure_cap", "ptr %bufp, ptr %cap, i64 %hpn")
    irGEP("hd", "i8", "%hdbuf", "%hp")
    irStore("i8", "10", "%hd")
    irAdd("hp1", "i64", "%hp", "1")
    irStore("i64", "%hp1", "%pos")
    // Row loop
    irBr("row.loop")
    irLabel("row.loop")
    irCall("src", "i32", "sqlite3_step", "ptr %stmt")
    irICmp("isrow", "eq", "i32", "%src", "100")
    irBrCond("isrow", "row.body", "row.done")
    irLabel("row.body")
    irStore("i32", "0", "%ci")
    irBr("col.loop")
    irLabel("col.loop")
    irLoad("cci", "i32", "%ci")
    irICmp("ccond", "slt", "i32", "%cci", "%ncols")
    irBrCond("ccond", "col.body", "col.done")
    irLabel("col.body")
    irLoad("cci2", "i32", "%ci")
    // Tab separator
    irICmp("cntab", "sgt", "i32", "%cci2", "0")
    irBrCond("cntab", "col.tab", "col.val")
    irLabel("col.tab")
    irLoad("vtp", "i64", "%pos")
    irAdd("vtn", "i64", "%vtp", "2")
    irCall("vtbuf", "ptr", "ss_rt_ensure_cap", "ptr %bufp, ptr %cap, i64 %vtn")
    irGEP("vtd", "i8", "%vtbuf", "%vtp")
    irStore("i8", "9", "%vtd")
    irAdd("vtp1", "i64", "%vtp", "1")
    irStore("i64", "%vtp1", "%pos")
    irBr("col.val")
    irLabel("col.val")
    irCall("ctxt", "ptr", "sqlite3_column_text", "ptr %stmt, i32 %cci2")
    irICmp("isnull", "eq", "ptr", "%ctxt", "null")
    irBrCond("isnull", "col.next", "col.copy")
    irLabel("col.copy")
    irCall("vtlen", "i64", "strlen", "ptr %ctxt")
    irLoad("vp2", "i64", "%pos")
    irAdd("vn", "i64", "%vp2", "%vtlen")
    irAdd("vn2", "i64", "%vn", "1")
    irCall("vbuf", "ptr", "ss_rt_ensure_cap", "ptr %bufp, ptr %cap, i64 %vn2")
    irGEP("vdst", "i8", "%vbuf", "%vp2")
    irCall("_3", "ptr", "memcpy", "ptr %vdst, ptr %ctxt, i64 %vtlen")
    irAdd("vp3", "i64", "%vp2", "%vtlen")
    irStore("i64", "%vp3", "%pos")
    irBr("col.next")
    irLabel("col.next")
    irAdd("cci3", "i32", "%cci2", "1")
    irStore("i32", "%cci3", "%ci")
    irBr("col.loop")
    irLabel("col.done")
    // Newline after row
    irLoad("rp", "i64", "%pos")
    irAdd("rn", "i64", "%rp", "2")
    irCall("rbuf", "ptr", "ss_rt_ensure_cap", "ptr %bufp, ptr %cap, i64 %rn")
    irGEP("rd", "i8", "%rbuf", "%rp")
    irStore("i8", "10", "%rd")
    irAdd("rp1", "i64", "%rp", "1")
    irStore("i64", "%rp1", "%pos")
    irBr("row.loop")
    irLabel("row.done")
    irCall("_4", "i32", "sqlite3_finalize", "ptr %stmt")
    irLoad("fp", "i64", "%pos")
    irAdd("fn", "i64", "%fp", "1")
    irCall("fbuf", "ptr", "ss_rt_ensure_cap", "ptr %bufp, ptr %cap, i64 %fn")
    irGEP("ft", "i8", "%fbuf", "%fp")
    irStore("i8", "0", "%ft")
    irRet("ptr", "%fbuf")
    emitIR("}")
    emitIR("")
}
