// gen_rt_io.ss — Runtime I/O, process, and math operations

// ── I/O ───────────────────────────────────────────────────────

function emitRuntimeIO() {
    // ss_println
    emitIR("define void @ss_println(ptr %s) {")
    irCall("_1", "i32", "puts", "ptr %s")
    irRetVoid()
    emitIR("}")
    emitIR("")

    // ss_print
    emitIR("define void @ss_print(ptr %s) {")
    irLoad("out", "ptr", "@stdout")
    irCall("_1", "i32", "fputs", "ptr %s, ptr %out")
    irLoad("out2", "ptr", "@stdout")
    irCall("_2", "i32", "fflush", "ptr %out2")
    irRetVoid()
    emitIR("}")
    emitIR("")

    // ss_readLine — dynamic buffer, reads lines of any length
    emitIR("define ptr @ss_readLine() {")
    irLabel("entry")
    irAlloca("bufp", "ptr", 8)
    irAlloca("cap", "i64", 8)
    irAlloca("off", "i64", 8)
    irCall("r0", "ptr", "ss_rc_alloc", "i64 1024, i32 0")
    irStore("ptr", "%r0", "%bufp")
    irStore("i64", "1024", "%cap")
    irStore("i64", "0", "%off")
    irLoad("in", "ptr", "@stdin")
    irBr("read")
    irLabel("read")
    irLoad("cbuf", "ptr", "%bufp")
    irLoad("coff", "i64", "%off")
    irLoad("ccap", "i64", "%cap")
    irSub("rem", "i64", "%ccap", "%coff")
    irTrunc("remi", "i64", "%rem", "i32")
    irGEP("dst", "i8", "%cbuf", "%coff")
    irCall("result", "ptr", "fgets", "ptr %dst, i32 %remi, ptr %in")
    irICmp("isnull", "eq", "ptr", "%result", "null")
    irBrCond("isnull", "eof", "check")
    irLabel("eof")
    irLoad("eoff", "i64", "%off")
    irICmp("empty", "eq", "i64", "%eoff", "0")
    irBrCond("empty", "nil", "done")
    irLabel("nil")
    irLoad("nbuf", "ptr", "%bufp")
    irStore("i8", "0", "%nbuf")
    irRet("ptr", "%nbuf")
    irLabel("check")
    irLoad("kbuf", "ptr", "%bufp")
    irCall("total", "i64", "strlen", "ptr %kbuf")
    irICmp("haslen", "sgt", "i64", "%total", "0")
    irBrCond("haslen", "chklast", "done")
    irLabel("chklast")
    irSub("lastidx", "i64", "%total", "1")
    irGEP("lastp", "i8", "%kbuf", "%lastidx")
    irLoad("lastch", "i8", "%lastp")
    irICmp("isnl", "eq", "i8", "%lastch", "10")
    irBrCond("isnl", "strip", "chkfull")
    irLabel("strip")
    irStore("i8", "0", "%lastp")
    irBr("done")
    irLabel("chkfull")
    irLoad("kcap", "i64", "%cap")
    irSub("maxidx", "i64", "%kcap", "1")
    irICmp("isfull", "eq", "i64", "%total", "%maxidx")
    irBrCond("isfull", "grow", "done")
    irLabel("grow")
    irLoad("gcap", "i64", "%cap")
    irMul("newcap", "i64", "%gcap", "2")
    irLoad("gbuf", "ptr", "%bufp")
    irCall("newbuf", "ptr", "ss_rc_realloc", "ptr %gbuf, i64 %newcap")
    irStore("ptr", "%newbuf", "%bufp")
    irStore("i64", "%newcap", "%cap")
    irStore("i64", "%total", "%off")
    irBr("read")
    irLabel("done")
    irLoad("ret", "ptr", "%bufp")
    irRet("ptr", "%ret")
    emitIR("}")
    emitIR("")

    // ss_readFile
    emitIR("define ptr @ss_readFile(ptr %path) {")
    irLabel("entry")
    irCall("fp", "ptr", "fopen", "ptr %path, ptr @.rt.str.rb")
    irICmp("isnull", "eq", "ptr", "%fp", "null")
    irBrCond("isnull", "fail", "read")
    irLabel("read")
    irCall("_1", "i32", "fseek", "ptr %fp, i64 0, i32 2")
    irCall("size", "i64", "ftell", "ptr %fp")
    irCall("_2", "i32", "fseek", "ptr %fp, i64 0, i32 0")
    irAdd("alloc", "i64", "%size", "1")
    irCall("buf", "ptr", "ss_rc_alloc", "i64 %alloc, i32 0")
    irCall("_3", "i64", "fread", "ptr %buf, i64 1, i64 %size, ptr %fp")
    irGEP("term", "i8", "%buf", "%size")
    irStore("i8", "0", "%term")
    irCall("_4", "i32", "fclose", "ptr %fp")
    irRet("ptr", "%buf")
    irLabel("fail")
    irCall("empty", "ptr", "ss_rc_strdup", "ptr @.rt.str.empty")
    irRet("ptr", "%empty")
    emitIR("}")
    emitIR("")

    // ss_writeFile
    emitIR("define void @ss_writeFile(ptr %path, ptr %data) {")
    irLabel("entry")
    irCall("fp", "ptr", "fopen", "ptr %path, ptr @.rt.str.w")
    irICmp("isnull", "eq", "ptr", "%fp", "null")
    irBrCond("isnull", "done", "wr")
    irLabel("wr")
    irCall("_1", "i32", "fputs", "ptr %data, ptr %fp")
    irCall("_2", "i32", "fclose", "ptr %fp")
    irBr("done")
    irLabel("done")
    irRetVoid()
    emitIR("}")
    emitIR("")

    // ss_appendFile
    emitIR("define void @ss_appendFile(ptr %path, ptr %data) {")
    irLabel("entry")
    irCall("fp", "ptr", "fopen", "ptr %path, ptr @.rt.str.a")
    irICmp("isnull", "eq", "ptr", "%fp", "null")
    irBrCond("isnull", "done", "wr")
    irLabel("wr")
    irCall("_1", "i32", "fputs", "ptr %data, ptr %fp")
    irCall("_2", "i32", "fclose", "ptr %fp")
    irBr("done")
    irLabel("done")
    irRetVoid()
    emitIR("}")
    emitIR("")
}

// ── Process ───────────────────────────────────────────────────

function emitRuntimeProcess() {
    emitIR("define void @ss_exit(i32 %code) {")
    irCallVoid("exit", "i32 %code")
    emitIR("  unreachable")
    emitIR("}")
    emitIR("")

    emitIR("define i32 @ss_system(ptr %cmd) {")
    irCall("result", "i32", "system", "ptr %cmd")
    irRet("i32", "%result")
    emitIR("}")
    emitIR("")

    emitIR("define void @ss_initArgs(i32 %argc, ptr %argv) {")
    irStore("i32", "%argc", "@ss_argc")
    irStore("ptr", "%argv", "@ss_argv")
    irRetVoid()
    emitIR("}")
    emitIR("")

    emitIR("define i32 @ss_argCount() {")
    irLoad("count", "i32", "@ss_argc")
    irRet("i32", "%count")
    emitIR("}")
    emitIR("")

    emitIR("define ptr @ss_argGet(i32 %idx) {")
    irLabel("entry")
    irLoad("argc", "i32", "@ss_argc")
    irICmp("oob", "sge", "i32", "%idx", "%argc")
    irBrCond("oob", "oob_ret", "ok")
    irLabel("oob_ret")
    irCall("empty", "ptr", "ss_rc_strdup", "ptr @.rt.str.empty")
    irRet("ptr", "%empty")
    irLabel("ok")
    irLoad("argv", "ptr", "@ss_argv")
    irSext("idx64", "i32", "%idx", "i64")
    irGEP("argp", "ptr", "%argv", "%idx64")
    irLoad("arg", "ptr", "%argp")
    irCall("result", "ptr", "ss_rc_strdup", "ptr %arg")
    irRet("ptr", "%result")
    emitIR("}")
    emitIR("")

    emitIR("define ptr @ss_getenv(ptr %name) {")
    irLabel("entry")
    irCall("val", "ptr", "getenv", "ptr %name")
    irICmp("isnull", "eq", "ptr", "%val", "null")
    irBrCond("isnull", "nil", "ok")
    irLabel("nil")
    irCall("empty", "ptr", "ss_rc_strdup", "ptr @.rt.str.empty")
    irRet("ptr", "%empty")
    irLabel("ok")
    irCall("result", "ptr", "ss_rc_strdup", "ptr %val")
    irRet("ptr", "%result")
    emitIR("}")
    emitIR("")
}

// ── Math ──────────────────────────────────────────────────────

function emitRuntimeMath() {
    emitIR("define double @ss_sqrt(double %x) {")
    irCall("result", "double", "sqrt", "double %x")
    irRet("double", "%result")
    emitIR("}")
    emitIR("define double @ss_abs(double %x) {")
    irCall("result", "double", "fabs", "double %x")
    irRet("double", "%result")
    emitIR("}")
    emitIR("define double @ss_floor(double %x) {")
    irCall("result", "double", "floor", "double %x")
    irRet("double", "%result")
    emitIR("}")
    emitIR("define double @ss_ceil(double %x) {")
    irCall("result", "double", "ceil", "double %x")
    irRet("double", "%result")
    emitIR("}")
    emitIR("define double @ss_round(double %x) {")
    irCall("result", "double", "round", "double %x")
    irRet("double", "%result")
    emitIR("}")
    emitIR("define double @ss_pow(double %base, double %exp) {")
    irCall("result", "double", "pow", "double %base, double %exp")
    irRet("double", "%result")
    emitIR("}")
    emitIR("define double @ss_log(double %x) {")
    irCall("result", "double", "log", "double %x")
    irRet("double", "%result")
    emitIR("}")
    emitIR("define double @ss_sin(double %x) {")
    irCall("result", "double", "sin", "double %x")
    irRet("double", "%result")
    emitIR("}")
    emitIR("define double @ss_cos(double %x) {")
    irCall("result", "double", "cos", "double %x")
    irRet("double", "%result")
    emitIR("}")
    emitIR("define double @ss_tan(double %x) {")
    irCall("result", "double", "tan", "double %x")
    irRet("double", "%result")
    emitIR("}")
    emitIR("define double @ss_asin(double %x) {")
    irCall("result", "double", "asin", "double %x")
    irRet("double", "%result")
    emitIR("}")
    emitIR("define double @ss_acos(double %x) {")
    irCall("result", "double", "acos", "double %x")
    irRet("double", "%result")
    emitIR("}")
    emitIR("define double @ss_atan(double %x) {")
    irCall("result", "double", "atan", "double %x")
    irRet("double", "%result")
    emitIR("}")
    emitIR("define double @ss_atan2(double %y, double %x) {")
    irCall("result", "double", "atan2", "double %y, double %x")
    irRet("double", "%result")
    emitIR("}")
    emitIR("define double @ss_exp(double %x) {")
    irCall("result", "double", "exp", "double %x")
    irRet("double", "%result")
    emitIR("}")
    emitIR("define double @ss_log10(double %x) {")
    irCall("result", "double", "log10", "double %x")
    irRet("double", "%result")
    emitIR("}")
    emitIR("define double @ss_log2(double %x) {")
    irCall("result", "double", "log2", "double %x")
    irRet("double", "%result")
    emitIR("}")
    emitIR("define double @ss_trunc(double %x) {")
    irCall("result", "double", "trunc", "double %x")
    irRet("double", "%result")
    emitIR("}")
    emitIR("define double @ss_hypot(double %x, double %y) {")
    irCall("result", "double", "hypot", "double %x, double %y")
    irRet("double", "%result")
    emitIR("}")
    emitIR("define double @ss_fmod(double %x, double %y) {")
    irCall("result", "double", "fmod", "double %x, double %y")
    irRet("double", "%result")
    emitIR("}")
    emitIR("")
    // sign: returns -1.0, 0.0, or 1.0
    emitIR("define double @ss_sign(double %x) {")
    emitIR("  %is_pos = fcmp ogt double %x, 0.0")
    emitIR("  %is_neg = fcmp olt double %x, 0.0")
    emitIR("  %pos = select i1 %is_pos, double 1.0, double 0.0")
    emitIR("  %result = select i1 %is_neg, double -1.0, double %pos")
    irRet("double", "%result")
    emitIR("}")
    emitIR("")
    // cbrt: cube root
    emitIR("define double @ss_cbrt(double %x) {")
    emitIR("  %third = fdiv double 1.0, 3.0")
    irCall("result", "double", "pow", "double %x, double %third")
    irRet("double", "%result")
    emitIR("}")
    emitIR("")
    emitIR("define double @ss_min(double %a, double %b) {")
    emitIR("  %cmp = fcmp olt double %a, %b")
    emitIR("  %result = select i1 %cmp, double %a, double %b")
    irRet("double", "%result")
    emitIR("}")
    emitIR("")
    emitIR("define double @ss_max(double %a, double %b) {")
    emitIR("  %cmp = fcmp ogt double %a, %b")
    emitIR("  %result = select i1 %cmp, double %a, double %b")
    irRet("double", "%result")
    emitIR("}")
    emitIR("")
    emitIR("define double @ss_random() {")
    irCall("raw", "i32", "rand", "")
    emitIR("  %fp = sitofp i32 %raw to double")
    emitIR("  %result = fdiv double %fp, 2147483647.0")
    irRet("double", "%result")
    emitIR("}")
    emitIR("")
    emitIR("define i32 @ss_randomInt(i32 %max) {")
    emitIR("  %guard = icmp sle i32 %max, 0")
    emitIR("  br i1 %guard, label %bad, label %ok")
    emitIR("bad:")
    emitIR("  ret i32 0")
    emitIR("ok:")
    irCall("raw", "i32", "rand", "")
    emitIR("  %result = srem i32 %raw, %max")
    irRet("i32", "%result")
    emitIR("}")
    emitIR("")
}
