// gen_runtime.ss — Generate LLVM IR define blocks for all runtime functions
// Replaces runtime/runtime.c by emitting equivalent LLVM IR that calls libc directly

function emitRuntimeDefs() {
    emitLibcDecls()
    emitRuntimeGlobals()
    emitRuntimeHelpers()
    emitRuntimeRC()
    emitRuntimeStringOps()
    emitRuntimeIO()
    emitRuntimeArrayOps()
    emitRuntimeConversions()
    emitRuntimeProcess()
    emitRuntimeMath()
    emitRuntimeFS()
    emitRuntimeNet()
    emitRuntimeMap()
    emitRuntimeExceptions()
    emitRuntimeSQLite()
}

// ── libc declarations ─────────────────────────────────────────

function emitLibcDecls() {
    // I/O
    emitIR("declare i32 @puts(ptr)")
    emitIR("declare i32 @fputs(ptr, ptr)")
    emitIR("declare i32 @fflush(ptr)")
    emitIR("declare ptr @fopen(ptr, ptr)")
    emitIR("declare i32 @fclose(ptr)")
    emitIR("declare i32 @fseek(ptr, i64, i32)")
    emitIR("declare i64 @ftell(ptr)")
    emitIR("declare i64 @fread(ptr, i64, i64, ptr)")
    emitIR("declare ptr @fgets(ptr, i32, ptr)")
    // String
    emitIR("declare i64 @strlen(ptr)")
    emitIR("declare ptr @strdup(ptr)")
    emitIR("declare ptr @strstr(ptr, ptr)")
    emitIR("declare i32 @strcmp(ptr, ptr)")
    emitIR("declare i32 @strncmp(ptr, ptr, i64)")
    // Memory
    emitIR("declare ptr @malloc(i64)")
    emitIR("declare ptr @calloc(i64, i64)")
    emitIR("declare ptr @realloc(ptr, i64)")
    emitIR("declare void @free(ptr)")
    emitIR("declare ptr @memcpy(ptr, ptr, i64)")
    emitIR("declare ptr @memset(ptr, i32, i64)")
    // Conversion
    emitIR("declare i32 @atoi(ptr)")
    emitIR("declare double @atof(ptr)")
    emitIR("declare i32 @snprintf(ptr, i64, ptr, ...)")
    // Math
    emitIR("declare double @sqrt(double)")
    emitIR("declare double @fabs(double)")
    emitIR("declare double @floor(double)")
    emitIR("declare double @ceil(double)")
    emitIR("declare double @round(double)")
    emitIR("declare double @pow(double, double)")
    emitIR("declare double @log(double)")
    emitIR("declare double @sin(double)")
    emitIR("declare double @cos(double)")
    emitIR("declare i32 @rand()")
    // Exception handling (setjmp/longjmp)
    emitIR("declare i32 @setjmp(ptr)")
    emitIR("declare void @longjmp(ptr, i32)")
    // Process
    emitIR("declare void @exit(i32)")
    emitIR("declare i32 @system(ptr)")
    emitIR("declare ptr @getenv(ptr)")
    emitIR("declare i32 @atexit(ptr)")
    // Time
    emitIR("declare i64 @time(ptr)")
    emitIR("declare i32 @clock_gettime(i32, ptr)")
    // Filesystem
    emitIR("declare i32 @mkdir(ptr, i32)")
    emitIR("declare i32 @stat(ptr, ptr)")
    emitIR("declare ptr @opendir(ptr)")
    emitIR("declare ptr @readdir(ptr)")
    emitIR("declare i32 @closedir(ptr)")
    emitIR("declare i32 @remove(ptr)")
    emitIR("declare i32 @rename(ptr, ptr)")
    // Network
    emitIR("declare i32 @socket(i32, i32, i32)")
    emitIR("declare i32 @bind(i32, ptr, i32)")
    emitIR("declare i32 @listen(i32, i32)")
    emitIR("declare i32 @accept(i32, ptr, ptr)")
    emitIR("declare i32 @setsockopt(i32, i32, i32, ptr, i32)")
    emitIR("declare i64 @read(i32, ptr, i64)")
    emitIR("declare i64 @write(i32, ptr, i64)")
    emitIR("declare i32 @close(i32)")
    emitIR("declare i16 @htons(i16)")
    // Sort
    emitIR("declare void @qsort(ptr, i64, i64, ptr)")
    // SQLite3 C API
    emitIR("declare i32 @sqlite3_open(ptr, ptr)")
    emitIR("declare i32 @sqlite3_close(ptr)")
    emitIR("declare i32 @sqlite3_exec(ptr, ptr, ptr, ptr, ptr)")
    emitIR("declare i32 @sqlite3_prepare_v2(ptr, ptr, i32, ptr, ptr)")
    emitIR("declare i32 @sqlite3_step(ptr)")
    emitIR("declare i32 @sqlite3_finalize(ptr)")
    emitIR("declare i32 @sqlite3_column_count(ptr)")
    emitIR("declare ptr @sqlite3_column_name(ptr, i32)")
    emitIR("declare ptr @sqlite3_column_text(ptr, i32)")
    emitIR("declare i32 @sqlite3_column_int(ptr, i32)")
    emitIR("declare i32 @sqlite3_changes(ptr)")
    emitIR("")
}

// ── Globals ───────────────────────────────────────────────────

function emitRuntimeGlobals() {
    emitIR("@stdin = external global ptr")
    emitIR("@stdout = external global ptr")
    emitIR("@ss_argc = internal global i32 0, align 4")
    emitIR("@ss_argv = internal global ptr null, align 8")
    // Exception handling: jmp_buf stack (200 bytes per level, max 16 deep)
    emitIR("@ss_jmpbuf = internal global [3200 x i8] zeroinitializer, align 16")
    emitIR("@ss_exc_depth = internal global i32 0, align 4")
    emitIR("@ss_exc_msg = internal global ptr null, align 8")
    emitIR(`@.rt.str.uncaught = private constant [21 x i8] c"uncaught exception: \\00"`)
    // Format strings (use @.rt. prefix to avoid collision with user string consts)
    emitIR(`@.rt.fmt.d = private constant [3 x i8] c"%d\\00"`)
    emitIR(`@.rt.fmt.g = private constant [3 x i8] c"%g\\00"`)
    emitIR(`@.rt.fmt.lld = private constant [5 x i8] c"%lld\\00"`)
    emitIR(`@.rt.str.true = private constant [5 x i8] c"true\\00"`)
    emitIR(`@.rt.str.false = private constant [6 x i8] c"false\\00"`)
    emitIR(`@.rt.str.empty = private constant [1 x i8] c"\\00"`)
    emitIR(`@.rt.str.rb = private constant [3 x i8] c"rb\\00"`)
    emitIR(`@.rt.str.w = private constant [2 x i8] c"w\\00"`)
    emitIR(`@.rt.str.a = private constant [2 x i8] c"a\\00"`)
    emitIR(`@.rt.str.nl = private constant [2 x i8] c"\\0A\\00"`)
    // Class destructor table: tag >= 10 indexes into this (tag-10)
    emitIR("@ss_class_dtor = internal global [100 x ptr] zeroinitializer")
    emitIR("")
}

// ── Internal helpers ──────────────────────────────────────────

function emitRuntimeHelpers() {
    // ss_rt_ensure_cap(bufp, capp, needed) — grow buffer if needed
    // bufp: ptr to buffer pointer, capp: ptr to capacity i64, needed: required bytes
    // Returns the (possibly reallocated) buffer pointer
    emitIR("define ptr @ss_rt_ensure_cap(ptr %bufp, ptr %capp, i64 %needed) {")
    emitIR("entry:")
    emitIR("  %cap = load i64, ptr %capp")
    emitIR("  %fits = icmp slt i64 %needed, %cap")
    emitIR("  br i1 %fits, label %ok, label %grow")
    emitIR("grow:")
    emitIR("  %dbl = mul i64 %cap, 2")
    emitIR("  %enough = icmp sge i64 %dbl, %needed")
    emitIR("  %min = add i64 %needed, 256")
    emitIR("  %newcap = select i1 %enough, i64 %dbl, i64 %min")
    emitIR("  %oldbuf = load ptr, ptr %bufp")
    emitIR("  %newbuf = call ptr @ss_rc_realloc(ptr %oldbuf, i64 %newcap)")
    emitIR("  store ptr %newbuf, ptr %bufp")
    emitIR("  store i64 %newcap, ptr %capp")
    emitIR("  br label %ok")
    emitIR("ok:")
    emitIR("  %buf = load ptr, ptr %bufp")
    emitIR("  ret ptr %buf")
    emitIR("}")
    emitIR("")
}

// ── Reference counting ────────────────────────────────────────
// Object layout: [rc:i64][tag:i32][pad:i32] | [user data...]
//                ^raw ptr (malloc'd)          ^user ptr (returned, +16)
// Tags: 0=string, 1=array(scalar), 2=map, 3=class(no dtor), 5=array(ptr), >=10=class(with dtor)

function emitRuntimeRC() {
    // ss_rc_alloc(size, tag) → user ptr with rc=1
    emitIR("define ptr @ss_rc_alloc(i64 %size, i32 %tag) {")
    emitIR("entry:")
    emitIR("  %total = add i64 %size, 16")
    emitIR("  %raw = call ptr @malloc(i64 %total)")
    emitIR("  store i64 1, ptr %raw")
    emitIR("  %tagp = getelementptr i8, ptr %raw, i64 8")
    emitIR("  store i32 %tag, ptr %tagp")
    emitIR("  %padp = getelementptr i8, ptr %raw, i64 12")
    emitIR("  store i32 1397969747, ptr %padp")
    emitIR("  %user = getelementptr i8, ptr %raw, i64 16")
    emitIR("  ret ptr %user")
    emitIR("}")
    emitIR("")

    // ss_rc_calloc(size, tag) → zeroed user data with rc=1
    emitIR("define ptr @ss_rc_calloc(i64 %size, i32 %tag) {")
    emitIR("entry:")
    emitIR("  %buf = call ptr @ss_rc_alloc(i64 %size, i32 %tag)")
    emitIR("  %_1 = call ptr @memset(ptr %buf, i32 0, i64 %size)")
    emitIR("  ret ptr %buf")
    emitIR("}")
    emitIR("")

    // ss_rc_realloc(user_ptr, new_data_size) → new user ptr (preserves header)
    emitIR("define ptr @ss_rc_realloc(ptr %p, i64 %size) {")
    emitIR("entry:")
    emitIR("  %raw = getelementptr i8, ptr %p, i64 -16")
    emitIR("  %total = add i64 %size, 16")
    emitIR("  %newraw = call ptr @realloc(ptr %raw, i64 %total)")
    emitIR("  %user = getelementptr i8, ptr %newraw, i64 16")
    emitIR("  ret ptr %user")
    emitIR("}")
    emitIR("")

    // ss_rc_strdup(s) → RC-managed copy of string
    emitIR("define ptr @ss_rc_strdup(ptr %s) {")
    emitIR("entry:")
    emitIR("  %len = call i64 @strlen(ptr %s)")
    emitIR("  %size = add i64 %len, 1")
    emitIR("  %buf = call ptr @ss_rc_alloc(i64 %size, i32 0)")
    emitIR("  %_1 = call ptr @memcpy(ptr %buf, ptr %s, i64 %size)")
    emitIR("  ret ptr %buf")
    emitIR("}")
    emitIR("")

    // ss_rc_retain(p) — increment rc; skip null, non-RC, and immortal (rc<0)
    emitIR("define void @ss_rc_retain(ptr %p) {")
    emitIR("entry:")
    emitIR("  %isnull = icmp eq ptr %p, null")
    emitIR("  br i1 %isnull, label %done, label %guard")
    emitIR("guard:")
    emitIR("  %magp = getelementptr i8, ptr %p, i64 -4")
    emitIR("  %mag = load i32, ptr %magp")
    emitIR("  %isrc = icmp eq i32 %mag, 1397969747")
    emitIR("  br i1 %isrc, label %check, label %done")
    emitIR("check:")
    emitIR("  %raw = getelementptr i8, ptr %p, i64 -16")
    emitIR("  %rc = load i64, ptr %raw")
    emitIR("  %immortal = icmp slt i64 %rc, 0")
    emitIR("  br i1 %immortal, label %done, label %inc")
    emitIR("inc:")
    emitIR("  %rc1 = add i64 %rc, 1")
    emitIR("  store i64 %rc1, ptr %raw")
    emitIR("  br label %done")
    emitIR("done:")
    emitIR("  ret void")
    emitIR("}")
    emitIR("")

    // ss_rc_release(p) — decrement rc; free when 0; skip null, non-RC, and immortal
    // On rc=0: dispatch to type-specific destructor based on tag before freeing
    emitIR("define void @ss_rc_release(ptr %p) {")
    emitIR("entry:")
    emitIR("  %isnull = icmp eq ptr %p, null")
    emitIR("  br i1 %isnull, label %done, label %guard")
    emitIR("guard:")
    emitIR("  %magp = getelementptr i8, ptr %p, i64 -4")
    emitIR("  %mag = load i32, ptr %magp")
    emitIR("  %isrc = icmp eq i32 %mag, 1397969747")
    emitIR("  br i1 %isrc, label %check, label %done")
    emitIR("check:")
    emitIR("  %raw = getelementptr i8, ptr %p, i64 -16")
    emitIR("  %rc = load i64, ptr %raw")
    emitIR("  %immortal = icmp slt i64 %rc, 0")
    emitIR("  br i1 %immortal, label %done, label %dec")
    emitIR("dec:")
    emitIR("  %rc1 = sub i64 %rc, 1")
    emitIR("  %iszero = icmp eq i64 %rc1, 0")
    emitIR("  br i1 %iszero, label %destroy, label %store")
    emitIR("store:")
    emitIR("  store i64 %rc1, ptr %raw")
    emitIR("  br label %done")
    emitIR("destroy:")
    emitIR("  ; Dispatch destructor by tag")
    emitIR("  %tagp = getelementptr i8, ptr %p, i64 -8")
    emitIR("  %tag = load i32, ptr %tagp")
    emitIR("  %is_map = icmp eq i32 %tag, 2")
    emitIR("  br i1 %is_map, label %dtor_map, label %check_arrptr")
    emitIR("check_arrptr:")
    emitIR("  %is_arrptr = icmp eq i32 %tag, 5")
    emitIR("  br i1 %is_arrptr, label %dtor_arrptr, label %check_class")
    emitIR("check_class:")
    emitIR("  %is_class_dtor = icmp sge i32 %tag, 10")
    emitIR("  br i1 %is_class_dtor, label %dtor_class, label %do_free")
    emitIR("dtor_map:")
    emitIR("  call void @ss_rc_destroy_map(ptr %p)")
    emitIR("  br label %do_free")
    emitIR("dtor_arrptr:")
    emitIR("  call void @ss_rc_destroy_array_ptrs(ptr %p)")
    emitIR("  br label %do_free")
    emitIR("dtor_class:")
    emitIR("  %didx = sub i32 %tag, 10")
    emitIR("  %didx64 = sext i32 %didx to i64")
    emitIR("  %dgep = getelementptr [100 x ptr], ptr @ss_class_dtor, i64 0, i64 %didx64")
    emitIR("  %dfn = load ptr, ptr %dgep")
    emitIR("  %has_dtor = icmp ne ptr %dfn, null")
    emitIR("  br i1 %has_dtor, label %call_dtor, label %do_free")
    emitIR("call_dtor:")
    emitIR("  call void %dfn(ptr %p)")
    emitIR("  br label %do_free")
    emitIR("do_free:")
    emitIR("  call void @free(ptr %raw)")
    emitIR("  br label %done")
    emitIR("done:")
    emitIR("  ret void")
    emitIR("}")
    emitIR("")

    // ss_rc_release_no_children(p) — decrement rc; if zero, free without destructor/element cleanup
    // Used for non-owning container fields: the container is freed but elements are not released
    emitIR("define void @ss_rc_release_no_children(ptr %p) {")
    emitIR("entry:")
    emitIR("  %isnull = icmp eq ptr %p, null")
    emitIR("  br i1 %isnull, label %done, label %guard")
    emitIR("guard:")
    emitIR("  %magp = getelementptr i8, ptr %p, i64 -4")
    emitIR("  %mag = load i32, ptr %magp")
    emitIR("  %isrc = icmp eq i32 %mag, 1397969747")
    emitIR("  br i1 %isrc, label %check, label %done")
    emitIR("check:")
    emitIR("  %raw = getelementptr i8, ptr %p, i64 -16")
    emitIR("  %rc = load i64, ptr %raw")
    emitIR("  %immortal = icmp slt i64 %rc, 0")
    emitIR("  br i1 %immortal, label %done, label %dec")
    emitIR("dec:")
    emitIR("  %rc1 = sub i64 %rc, 1")
    emitIR("  %iszero = icmp eq i64 %rc1, 0")
    emitIR("  br i1 %iszero, label %do_free, label %store")
    emitIR("store:")
    emitIR("  store i64 %rc1, ptr %raw")
    emitIR("  br label %done")
    emitIR("do_free:")
    emitIR("  call void @free(ptr %raw)")
    emitIR("  br label %done")
    emitIR("done:")
    emitIR("  ret void")
    emitIR("}")
    emitIR("")

    // ss_rc_destroy_map(map) — release all keys, optionally release ptr values, free entries
    // val_type flag at map offset 516: 0=scalar values, 1=ptr values (need release)
    emitIR("define void @ss_rc_destroy_map(ptr %map) {")
    emitIR("entry:")
    emitIR("  %ia = alloca i64, align 8")
    emitIR("  %ea = alloca ptr, align 8")
    emitIR("  %na = alloca ptr, align 8")
    emitIR("  %vtpp = getelementptr i8, ptr %map, i64 516")
    emitIR("  %vtp = load i32, ptr %vtpp")
    emitIR("  %val_is_ptr = icmp eq i32 %vtp, 1")
    emitIR("  store i64 0, ptr %ia")
    emitIR("  br label %bucket.loop")
    emitIR("bucket.loop:")
    emitIR("  %i = load i64, ptr %ia")
    emitIR("  %done = icmp eq i64 %i, 64")
    emitIR("  br i1 %done, label %ret, label %bucket.body")
    emitIR("bucket.body:")
    emitIR("  %bp = getelementptr ptr, ptr %map, i64 %i")
    emitIR("  %e0 = load ptr, ptr %bp")
    emitIR("  store ptr %e0, ptr %ea")
    emitIR("  br label %entry.loop")
    emitIR("entry.loop:")
    emitIR("  %e = load ptr, ptr %ea")
    emitIR("  %enull = icmp eq ptr %e, null")
    emitIR("  br i1 %enull, label %bucket.next, label %entry.body")
    emitIR("entry.body:")
    emitIR("  ; Save next pointer before freeing")
    emitIR("  %enp = getelementptr i8, ptr %e, i64 16")
    emitIR("  %next = load ptr, ptr %enp")
    emitIR("  store ptr %next, ptr %na")
    emitIR("  ; Release key (RC string)")
    emitIR("  %key = load ptr, ptr %e")
    emitIR("  call void @ss_rc_release(ptr %key)")
    emitIR("  ; Release value if map has ptr values")
    emitIR("  br i1 %val_is_ptr, label %rel.val, label %free.entry")
    emitIR("rel.val:")
    emitIR("  %vp2 = getelementptr i8, ptr %e, i64 8")
    emitIR("  %vi = load i64, ptr %vp2")
    emitIR("  %vptr = inttoptr i64 %vi to ptr")
    emitIR("  call void @ss_rc_release(ptr %vptr)")
    emitIR("  br label %free.entry")
    emitIR("free.entry:")
    emitIR("  ; Free entry node (plain malloc)")
    emitIR("  call void @free(ptr %e)")
    emitIR("  ; Advance to next entry")
    emitIR("  %nv = load ptr, ptr %na")
    emitIR("  store ptr %nv, ptr %ea")
    emitIR("  br label %entry.loop")
    emitIR("bucket.next:")
    emitIR("  %ni = load i64, ptr %ia")
    emitIR("  %ni1 = add i64 %ni, 1")
    emitIR("  store i64 %ni1, ptr %ia")
    emitIR("  br label %bucket.loop")
    emitIR("ret:")
    emitIR("  ret void")
    emitIR("}")
    emitIR("")

    // ss_rc_destroy_array_ptrs(arr) — release all ptr elements
    emitIR("define void @ss_rc_destroy_array_ptrs(ptr %arr) {")
    emitIR("entry:")
    emitIR("  %len = load i64, ptr %arr")
    emitIR("  %ia = alloca i64, align 8")
    emitIR("  store i64 0, ptr %ia")
    emitIR("  br label %loop")
    emitIR("loop:")
    emitIR("  %ci = load i64, ptr %ia")
    emitIR("  %done = icmp eq i64 %ci, %len")
    emitIR("  br i1 %done, label %ret, label %body")
    emitIR("body:")
    emitIR("  %slot = add i64 %ci, 1")
    emitIR("  %ep = getelementptr i64, ptr %arr, i64 %slot")
    emitIR("  %ev = load i64, ptr %ep")
    emitIR("  %eptr = inttoptr i64 %ev to ptr")
    emitIR("  call void @ss_rc_release(ptr %eptr)")
    emitIR("  %ni = add i64 %ci, 1")
    emitIR("  store i64 %ni, ptr %ia")
    emitIR("  br label %loop")
    emitIR("ret:")
    emitIR("  ret void")
    emitIR("}")
    emitIR("")

    // ss_rc_atexit_cleanup — stub for program exit cleanup (future cycle cleanup)
    emitIR("define void @ss_rc_atexit_cleanup() {")
    emitIR("entry:")
    emitIR("  ret void")
    emitIR("}")
    emitIR("")
}

// ── String operations ─────────────────────────────────────────

function emitRuntimeStringOps() {
    // ss_stringLength
    emitIR("define i32 @ss_stringLength(ptr %s) {")
    emitIR("  %len = call i64 @strlen(ptr %s)")
    emitIR("  %result = trunc i64 %len to i32")
    emitIR("  ret i32 %result")
    emitIR("}")
    emitIR("")

    // ss_string_concat
    emitIR("define ptr @ss_string_concat(ptr %a, ptr %b) {")
    emitIR("  %alen = call i64 @strlen(ptr %a)")
    emitIR("  %blen = call i64 @strlen(ptr %b)")
    emitIR("  %total = add i64 %alen, %blen")
    emitIR("  %size = add i64 %total, 1")
    emitIR("  %buf = call ptr @ss_rc_alloc(i64 %size, i32 0)")
    emitIR("  %_1 = call ptr @memcpy(ptr %buf, ptr %a, i64 %alen)")
    emitIR("  %dst = getelementptr i8, ptr %buf, i64 %alen")
    emitIR("  %blen1 = add i64 %blen, 1")
    emitIR("  %_2 = call ptr @memcpy(ptr %dst, ptr %b, i64 %blen1)")
    emitIR("  ret ptr %buf")
    emitIR("}")
    emitIR("")

    // ss_string_eq
    emitIR("define i32 @ss_string_eq(ptr %a, ptr %b) {")
    emitIR("  %cmp = call i32 @strcmp(ptr %a, ptr %b)")
    emitIR("  %iseq = icmp eq i32 %cmp, 0")
    emitIR("  %result = zext i1 %iseq to i32")
    emitIR("  ret i32 %result")
    emitIR("}")
    emitIR("")

    // ss_string_ne
    emitIR("define i32 @ss_string_ne(ptr %a, ptr %b) {")
    emitIR("  %cmp = call i32 @strcmp(ptr %a, ptr %b)")
    emitIR("  %isne = icmp ne i32 %cmp, 0")
    emitIR("  %result = zext i1 %isne to i32")
    emitIR("  ret i32 %result")
    emitIR("}")
    emitIR("")

    // ss_strcmp
    emitIR("define i32 @ss_strcmp(ptr %a, ptr %b) {")
    emitIR("  %result = call i32 @strcmp(ptr %a, ptr %b)")
    emitIR("  ret i32 %result")
    emitIR("}")
    emitIR("")

    // ss_indexOf
    emitIR("define i32 @ss_indexOf(ptr %s, ptr %sub) {")
    emitIR("entry:")
    emitIR("  %found = call ptr @strstr(ptr %s, ptr %sub)")
    emitIR("  %isnull = icmp eq ptr %found, null")
    emitIR("  br i1 %isnull, label %neg, label %pos")
    emitIR("neg:")
    emitIR("  ret i32 -1")
    emitIR("pos:")
    emitIR("  %faddr = ptrtoint ptr %found to i64")
    emitIR("  %saddr = ptrtoint ptr %s to i64")
    emitIR("  %diff = sub i64 %faddr, %saddr")
    emitIR("  %result = trunc i64 %diff to i32")
    emitIR("  ret i32 %result")
    emitIR("}")
    emitIR("")

    // ss_charAt
    emitIR("define ptr @ss_charAt(ptr %s, i32 %idx) {")
    emitIR("entry:")
    emitIR("  %len = call i64 @strlen(ptr %s)")
    emitIR("  %idx64 = sext i32 %idx to i64")
    emitIR("  %oob = icmp sge i64 %idx64, %len")
    emitIR("  br i1 %oob, label %oob_ret, label %ok")
    emitIR("oob_ret:")
    emitIR("  %empty = call ptr @ss_rc_strdup(ptr @.rt.str.empty)")
    emitIR("  ret ptr %empty")
    emitIR("ok:")
    emitIR("  %buf = call ptr @ss_rc_alloc(i64 2, i32 0)")
    emitIR("  %cp = getelementptr i8, ptr %s, i64 %idx64")
    emitIR("  %ch = load i8, ptr %cp")
    emitIR("  store i8 %ch, ptr %buf")
    emitIR("  %term = getelementptr i8, ptr %buf, i64 1")
    emitIR("  store i8 0, ptr %term")
    emitIR("  ret ptr %buf")
    emitIR("}")
    emitIR("")

    // ss_substring
    emitIR("define ptr @ss_substring(ptr %s, i32 %start, i32 %count) {")
    emitIR("entry:")
    emitIR("  %len = call i64 @strlen(ptr %s)")
    emitIR("  %start64 = sext i32 %start to i64")
    emitIR("  %count64 = sext i32 %count to i64")
    emitIR("  %neg = icmp slt i64 %start64, 0")
    emitIR("  %clamped_start = select i1 %neg, i64 0, i64 %start64")
    emitIR("  %past_end = icmp sgt i64 %clamped_start, %len")
    emitIR("  %safe_start = select i1 %past_end, i64 %len, i64 %clamped_start")
    emitIR("  %end_pos = add i64 %safe_start, %count64")
    emitIR("  %overflow = icmp sgt i64 %end_pos, %len")
    emitIR("  %remaining = sub i64 %len, %safe_start")
    emitIR("  %safe_count = select i1 %overflow, i64 %remaining, i64 %count64")
    emitIR("  %alloc = add i64 %safe_count, 1")
    emitIR("  %buf = call ptr @ss_rc_alloc(i64 %alloc, i32 0)")
    emitIR("  %src = getelementptr i8, ptr %s, i64 %safe_start")
    emitIR("  %_1 = call ptr @memcpy(ptr %buf, ptr %src, i64 %safe_count)")
    emitIR("  %term = getelementptr i8, ptr %buf, i64 %safe_count")
    emitIR("  store i8 0, ptr %term")
    emitIR("  ret ptr %buf")
    emitIR("}")
    emitIR("")

    // ss_charCodeAt
    emitIR("define i32 @ss_charCodeAt(ptr %s, i32 %idx) {")
    emitIR("  %idx64 = sext i32 %idx to i64")
    emitIR("  %cp = getelementptr i8, ptr %s, i64 %idx64")
    emitIR("  %ch = load i8, ptr %cp")
    emitIR("  %result = zext i8 %ch to i32")
    emitIR("  ret i32 %result")
    emitIR("}")
    emitIR("")

    // ss_fromCharCode
    emitIR("define ptr @ss_fromCharCode(i32 %code) {")
    emitIR("  %buf = call ptr @ss_rc_alloc(i64 2, i32 0)")
    emitIR("  %ch = trunc i32 %code to i8")
    emitIR("  store i8 %ch, ptr %buf")
    emitIR("  %term = getelementptr i8, ptr %buf, i64 1")
    emitIR("  store i8 0, ptr %term")
    emitIR("  ret ptr %buf")
    emitIR("}")
    emitIR("")

    // ss_split — two pass: count then extract
    emitIR("define ptr @ss_split(ptr %s, ptr %delim) {")
    emitIR("entry:")
    emitIR("  %dlen = call i64 @strlen(ptr %delim)")
    emitIR("  %slen = call i64 @strlen(ptr %s)")
    emitIR("  ; Count pass")
    emitIR("  %cnt = alloca i32, align 4")
    emitIR("  store i32 1, ptr %cnt")
    emitIR("  %p1 = alloca ptr, align 8")
    emitIR("  store ptr %s, ptr %p1")
    emitIR("  %is_empty_d = icmp eq i64 %dlen, 0")
    emitIR("  br i1 %is_empty_d, label %build, label %count.loop")
    emitIR("count.loop:")
    emitIR("  %cp = load ptr, ptr %p1")
    emitIR("  %found = call ptr @strstr(ptr %cp, ptr %delim)")
    emitIR("  %nf = icmp eq ptr %found, null")
    emitIR("  br i1 %nf, label %build, label %count.inc")
    emitIR("count.inc:")
    emitIR("  %cc = load i32, ptr %cnt")
    emitIR("  %cc1 = add i32 %cc, 1")
    emitIR("  store i32 %cc1, ptr %cnt")
    emitIR("  %np = getelementptr i8, ptr %found, i64 %dlen")
    emitIR("  store ptr %np, ptr %p1")
    emitIR("  br label %count.loop")
    emitIR("build:")
    emitIR("  %n = load i32, ptr %cnt")
    emitIR("  %n64 = sext i32 %n to i64")
    emitIR("  %slots = add i64 %n64, 1")
    emitIR("  %asize = mul i64 %slots, 8")
    emitIR("  %arr = call ptr @ss_rc_calloc(i64 %asize, i32 5)")
    emitIR("  store i64 %n64, ptr %arr")
    emitIR("  ; Extract pass")
    emitIR("  %idx = alloca i32, align 4")
    emitIR("  store i32 0, ptr %idx")
    emitIR("  store ptr %s, ptr %p1")
    emitIR("  br i1 %is_empty_d, label %single, label %ext.loop")
    emitIR("single:")
    emitIR("  %dup0 = call ptr @ss_rc_strdup(ptr %s)")
    emitIR("  %slot0 = getelementptr i64, ptr %arr, i64 1")
    emitIR("  %dup0i = ptrtoint ptr %dup0 to i64")
    emitIR("  store i64 %dup0i, ptr %slot0")
    emitIR("  ret ptr %arr")
    emitIR("ext.loop:")
    emitIR("  %ep = load ptr, ptr %p1")
    emitIR("  %ef = call ptr @strstr(ptr %ep, ptr %delim)")
    emitIR("  %enf = icmp eq ptr %ef, null")
    emitIR("  br i1 %enf, label %ext.last, label %ext.copy")
    emitIR("ext.copy:")
    emitIR("  %elen = ptrtoint ptr %ef to i64")
    emitIR("  %estart = ptrtoint ptr %ep to i64")
    emitIR("  %epartlen = sub i64 %elen, %estart")
    emitIR("  %ealloc = add i64 %epartlen, 1")
    emitIR("  %ebuf = call ptr @ss_rc_alloc(i64 %ealloc, i32 0)")
    emitIR("  %_1 = call ptr @memcpy(ptr %ebuf, ptr %ep, i64 %epartlen)")
    emitIR("  %eterm = getelementptr i8, ptr %ebuf, i64 %epartlen")
    emitIR("  store i8 0, ptr %eterm")
    emitIR("  %ei = load i32, ptr %idx")
    emitIR("  %ei64 = sext i32 %ei to i64")
    emitIR("  %eslot = add i64 %ei64, 1")
    emitIR("  %eptr = getelementptr i64, ptr %arr, i64 %eslot")
    emitIR("  %ebufi = ptrtoint ptr %ebuf to i64")
    emitIR("  store i64 %ebufi, ptr %eptr")
    emitIR("  %ei1 = add i32 %ei, 1")
    emitIR("  store i32 %ei1, ptr %idx")
    emitIR("  %enp = getelementptr i8, ptr %ef, i64 %dlen")
    emitIR("  store ptr %enp, ptr %p1")
    emitIR("  br label %ext.loop")
    emitIR("ext.last:")
    emitIR("  %ldup = call ptr @ss_rc_strdup(ptr %ep)")
    emitIR("  %li = load i32, ptr %idx")
    emitIR("  %li64 = sext i32 %li to i64")
    emitIR("  %lslot = add i64 %li64, 1")
    emitIR("  %lptr = getelementptr i64, ptr %arr, i64 %lslot")
    emitIR("  %ldupi = ptrtoint ptr %ldup to i64")
    emitIR("  store i64 %ldupi, ptr %lptr")
    emitIR("  ret ptr %arr")
    emitIR("}")
    emitIR("")
}

// ── I/O ───────────────────────────────────────────────────────

function emitRuntimeIO() {
    // ss_println
    emitIR("define void @ss_println(ptr %s) {")
    emitIR("  %_1 = call i32 @puts(ptr %s)")
    emitIR("  ret void")
    emitIR("}")
    emitIR("")

    // ss_print
    emitIR("define void @ss_print(ptr %s) {")
    emitIR("  %out = load ptr, ptr @stdout")
    emitIR("  %_1 = call i32 @fputs(ptr %s, ptr %out)")
    emitIR("  %out2 = load ptr, ptr @stdout")
    emitIR("  %_2 = call i32 @fflush(ptr %out2)")
    emitIR("  ret void")
    emitIR("}")
    emitIR("")

    // ss_readLine — dynamic buffer, reads lines of any length
    emitIR("define ptr @ss_readLine() {")
    emitIR("entry:")
    emitIR("  %bufp = alloca ptr, align 8")
    emitIR("  %cap = alloca i64, align 8")
    emitIR("  %off = alloca i64, align 8")
    emitIR("  %r0 = call ptr @ss_rc_alloc(i64 1024, i32 0)")
    emitIR("  store ptr %r0, ptr %bufp")
    emitIR("  store i64 1024, ptr %cap")
    emitIR("  store i64 0, ptr %off")
    emitIR("  %in = load ptr, ptr @stdin")
    emitIR("  br label %read")
    emitIR("read:")
    emitIR("  %cbuf = load ptr, ptr %bufp")
    emitIR("  %coff = load i64, ptr %off")
    emitIR("  %ccap = load i64, ptr %cap")
    emitIR("  %rem = sub i64 %ccap, %coff")
    emitIR("  %remi = trunc i64 %rem to i32")
    emitIR("  %dst = getelementptr i8, ptr %cbuf, i64 %coff")
    emitIR("  %result = call ptr @fgets(ptr %dst, i32 %remi, ptr %in)")
    emitIR("  %isnull = icmp eq ptr %result, null")
    emitIR("  br i1 %isnull, label %eof, label %check")
    emitIR("eof:")
    emitIR("  %eoff = load i64, ptr %off")
    emitIR("  %empty = icmp eq i64 %eoff, 0")
    emitIR("  br i1 %empty, label %nil, label %done")
    emitIR("nil:")
    emitIR("  %nbuf = load ptr, ptr %bufp")
    emitIR("  store i8 0, ptr %nbuf")
    emitIR("  ret ptr %nbuf")
    emitIR("check:")
    emitIR("  %kbuf = load ptr, ptr %bufp")
    emitIR("  %total = call i64 @strlen(ptr %kbuf)")
    emitIR("  %haslen = icmp sgt i64 %total, 0")
    emitIR("  br i1 %haslen, label %chklast, label %done")
    emitIR("chklast:")
    emitIR("  %lastidx = sub i64 %total, 1")
    emitIR("  %lastp = getelementptr i8, ptr %kbuf, i64 %lastidx")
    emitIR("  %lastch = load i8, ptr %lastp")
    emitIR("  %isnl = icmp eq i8 %lastch, 10")
    emitIR("  br i1 %isnl, label %strip, label %chkfull")
    emitIR("strip:")
    emitIR("  store i8 0, ptr %lastp")
    emitIR("  br label %done")
    emitIR("chkfull:")
    emitIR("  %kcap = load i64, ptr %cap")
    emitIR("  %maxidx = sub i64 %kcap, 1")
    emitIR("  %isfull = icmp eq i64 %total, %maxidx")
    emitIR("  br i1 %isfull, label %grow, label %done")
    emitIR("grow:")
    emitIR("  %gcap = load i64, ptr %cap")
    emitIR("  %newcap = mul i64 %gcap, 2")
    emitIR("  %gbuf = load ptr, ptr %bufp")
    emitIR("  %newbuf = call ptr @ss_rc_realloc(ptr %gbuf, i64 %newcap)")
    emitIR("  store ptr %newbuf, ptr %bufp")
    emitIR("  store i64 %newcap, ptr %cap")
    emitIR("  store i64 %total, ptr %off")
    emitIR("  br label %read")
    emitIR("done:")
    emitIR("  %ret = load ptr, ptr %bufp")
    emitIR("  ret ptr %ret")
    emitIR("}")
    emitIR("")

    // ss_readFile
    emitIR("define ptr @ss_readFile(ptr %path) {")
    emitIR("entry:")
    emitIR("  %fp = call ptr @fopen(ptr %path, ptr @.rt.str.rb)")
    emitIR("  %isnull = icmp eq ptr %fp, null")
    emitIR("  br i1 %isnull, label %fail, label %read")
    emitIR("read:")
    emitIR("  %_1 = call i32 @fseek(ptr %fp, i64 0, i32 2)")
    emitIR("  %size = call i64 @ftell(ptr %fp)")
    emitIR("  %_2 = call i32 @fseek(ptr %fp, i64 0, i32 0)")
    emitIR("  %alloc = add i64 %size, 1")
    emitIR("  %buf = call ptr @ss_rc_alloc(i64 %alloc, i32 0)")
    emitIR("  %_3 = call i64 @fread(ptr %buf, i64 1, i64 %size, ptr %fp)")
    emitIR("  %term = getelementptr i8, ptr %buf, i64 %size")
    emitIR("  store i8 0, ptr %term")
    emitIR("  %_4 = call i32 @fclose(ptr %fp)")
    emitIR("  ret ptr %buf")
    emitIR("fail:")
    emitIR("  %empty = call ptr @ss_rc_strdup(ptr @.rt.str.empty)")
    emitIR("  ret ptr %empty")
    emitIR("}")
    emitIR("")

    // ss_writeFile
    emitIR("define void @ss_writeFile(ptr %path, ptr %data) {")
    emitIR("entry:")
    emitIR("  %fp = call ptr @fopen(ptr %path, ptr @.rt.str.w)")
    emitIR("  %isnull = icmp eq ptr %fp, null")
    emitIR("  br i1 %isnull, label %done, label %wr")
    emitIR("wr:")
    emitIR("  %_1 = call i32 @fputs(ptr %data, ptr %fp)")
    emitIR("  %_2 = call i32 @fclose(ptr %fp)")
    emitIR("  br label %done")
    emitIR("done:")
    emitIR("  ret void")
    emitIR("}")
    emitIR("")

    // ss_appendFile
    emitIR("define void @ss_appendFile(ptr %path, ptr %data) {")
    emitIR("entry:")
    emitIR("  %fp = call ptr @fopen(ptr %path, ptr @.rt.str.a)")
    emitIR("  %isnull = icmp eq ptr %fp, null")
    emitIR("  br i1 %isnull, label %done, label %wr")
    emitIR("wr:")
    emitIR("  %_1 = call i32 @fputs(ptr %data, ptr %fp)")
    emitIR("  %_2 = call i32 @fclose(ptr %fp)")
    emitIR("  br label %done")
    emitIR("done:")
    emitIR("  ret void")
    emitIR("}")
    emitIR("")
}

// ── Array operations ──────────────────────────────────────────

function emitRuntimeArrayOps() {
    // Layout: arr[0] = length (i64), arr[1..n] = elements (i64 each)

    // ss_newArray (scalar elements, tag=1)
    emitIR("define ptr @ss_newArray(i32 %size) {")
    emitIR("  %size64 = sext i32 %size to i64")
    emitIR("  %slots = add i64 %size64, 1")
    emitIR("  %asize = mul i64 %slots, 8")
    emitIR("  %arr = call ptr @ss_rc_calloc(i64 %asize, i32 1)")
    emitIR("  store i64 %size64, ptr %arr")
    emitIR("  ret ptr %arr")
    emitIR("}")
    emitIR("")

    // ss_newArrayPtr (ptr elements, tag=5 — destructor will release elements)
    emitIR("define ptr @ss_newArrayPtr(i32 %size) {")
    emitIR("  %size64 = sext i32 %size to i64")
    emitIR("  %slots = add i64 %size64, 1")
    emitIR("  %asize = mul i64 %slots, 8")
    emitIR("  %arr = call ptr @ss_rc_calloc(i64 %asize, i32 5)")
    emitIR("  store i64 %size64, ptr %arr")
    emitIR("  ret ptr %arr")
    emitIR("}")
    emitIR("")

    // ss_arrayLen
    emitIR("define i32 @ss_arrayLen(ptr %arr) {")
    emitIR("  %len = load i64, ptr %arr")
    emitIR("  %result = trunc i64 %len to i32")
    emitIR("  ret i32 %result")
    emitIR("}")
    emitIR("")

    // ss_arrayGet
    emitIR("define i64 @ss_arrayGet(ptr %arr, i32 %idx) {")
    emitIR("  %idx64 = sext i32 %idx to i64")
    emitIR("  %slot = add i64 %idx64, 1")
    emitIR("  %ptr = getelementptr i64, ptr %arr, i64 %slot")
    emitIR("  %val = load i64, ptr %ptr")
    emitIR("  ret i64 %val")
    emitIR("}")
    emitIR("")

    // ss_arraySet
    emitIR("define void @ss_arraySet(ptr %arr, i32 %idx, i64 %val) {")
    emitIR("  %idx64 = sext i32 %idx to i64")
    emitIR("  %slot = add i64 %idx64, 1")
    emitIR("  %ptr = getelementptr i64, ptr %arr, i64 %slot")
    emitIR("  store i64 %val, ptr %ptr")
    emitIR("  ret void")
    emitIR("}")
    emitIR("")

    // ss_arrayPush
    emitIR("define ptr @ss_arrayPush(ptr %arr, i64 %val) {")
    emitIR("  %len = load i64, ptr %arr")
    emitIR("  %newslots = add i64 %len, 2")
    emitIR("  %bytes = mul i64 %newslots, 8")
    emitIR("  %newarr = call ptr @ss_rc_realloc(ptr %arr, i64 %bytes)")
    emitIR("  %newlen = add i64 %len, 1")
    emitIR("  store i64 %newlen, ptr %newarr")
    emitIR("  %dst = getelementptr i64, ptr %newarr, i64 %newlen")
    emitIR("  store i64 %val, ptr %dst")
    emitIR("  ret ptr %newarr")
    emitIR("}")
    emitIR("")

    // ss_arraySort (qsort with comparator)
    emitIR("define internal i32 @ss_cmp_asc(ptr %a, ptr %b) {")
    emitIR("  %va = load i64, ptr %a")
    emitIR("  %vb = load i64, ptr %b")
    emitIR("  %gt = icmp sgt i64 %va, %vb")
    emitIR("  %lt = icmp slt i64 %va, %vb")
    emitIR("  %gti = zext i1 %gt to i32")
    emitIR("  %lti = zext i1 %lt to i32")
    emitIR("  %result = sub i32 %gti, %lti")
    emitIR("  ret i32 %result")
    emitIR("}")
    emitIR("")
    emitIR("define void @ss_arraySort(ptr %arr) {")
    emitIR("entry:")
    emitIR("  %len = load i64, ptr %arr")
    emitIR("  %need_sort = icmp sgt i64 %len, 1")
    emitIR("  br i1 %need_sort, label %sort, label %done")
    emitIR("sort:")
    emitIR("  %data = getelementptr i64, ptr %arr, i64 1")
    emitIR("  call void @qsort(ptr %data, i64 %len, i64 8, ptr @ss_cmp_asc)")
    emitIR("  br label %done")
    emitIR("done:")
    emitIR("  ret void")
    emitIR("}")
    emitIR("")

    // ss_arrayReverse
    emitIR("define void @ss_arrayReverse(ptr %arr) {")
    emitIR("entry:")
    emitIR("  %len = load i64, ptr %arr")
    emitIR("  %half = sdiv i64 %len, 2")
    emitIR("  %i = alloca i64, align 8")
    emitIR("  store i64 0, ptr %i")
    emitIR("  br label %loop")
    emitIR("loop:")
    emitIR("  %ci = load i64, ptr %i")
    emitIR("  %cond = icmp slt i64 %ci, %half")
    emitIR("  br i1 %cond, label %body, label %done")
    emitIR("body:")
    emitIR("  %li = add i64 %ci, 1")
    emitIR("  %ri64 = sub i64 %len, %ci")
    emitIR("  %lp = getelementptr i64, ptr %arr, i64 %li")
    emitIR("  %rp = getelementptr i64, ptr %arr, i64 %ri64")
    emitIR("  %lv = load i64, ptr %lp")
    emitIR("  %rv = load i64, ptr %rp")
    emitIR("  store i64 %rv, ptr %lp")
    emitIR("  store i64 %lv, ptr %rp")
    emitIR("  %ni = add i64 %ci, 1")
    emitIR("  store i64 %ni, ptr %i")
    emitIR("  br label %loop")
    emitIR("done:")
    emitIR("  ret void")
    emitIR("}")
    emitIR("")

    // ss_arrayFirst
    emitIR("define i64 @ss_arrayFirst(ptr %arr) {")
    emitIR("entry:")
    emitIR("  %len = load i64, ptr %arr")
    emitIR("  %has = icmp sgt i64 %len, 0")
    emitIR("  br i1 %has, label %has_elem, label %empty")
    emitIR("has_elem:")
    emitIR("  %ptr = getelementptr i64, ptr %arr, i64 1")
    emitIR("  %val = load i64, ptr %ptr")
    emitIR("  ret i64 %val")
    emitIR("empty:")
    emitIR("  ret i64 0")
    emitIR("}")
    emitIR("")

    // ss_arrayLast
    emitIR("define i64 @ss_arrayLast(ptr %arr) {")
    emitIR("entry:")
    emitIR("  %len = load i64, ptr %arr")
    emitIR("  %has = icmp sgt i64 %len, 0")
    emitIR("  br i1 %has, label %has_elem, label %empty")
    emitIR("has_elem:")
    emitIR("  %ptr = getelementptr i64, ptr %arr, i64 %len")
    emitIR("  %val = load i64, ptr %ptr")
    emitIR("  ret i64 %val")
    emitIR("empty:")
    emitIR("  ret i64 0")
    emitIR("}")
    emitIR("")

    // ss_arrayIndexOf
    emitIR("define i32 @ss_arrayIndexOf(ptr %arr, i64 %needle) {")
    emitIR("entry:")
    emitIR("  %len = load i64, ptr %arr")
    emitIR("  %i = alloca i64, align 8")
    emitIR("  store i64 0, ptr %i")
    emitIR("  br label %loop")
    emitIR("loop:")
    emitIR("  %ci = load i64, ptr %i")
    emitIR("  %cond = icmp slt i64 %ci, %len")
    emitIR("  br i1 %cond, label %body, label %notfound")
    emitIR("body:")
    emitIR("  %si = add i64 %ci, 1")
    emitIR("  %ep = getelementptr i64, ptr %arr, i64 %si")
    emitIR("  %ev = load i64, ptr %ep")
    emitIR("  %eq = icmp eq i64 %ev, %needle")
    emitIR("  br i1 %eq, label %found, label %inc")
    emitIR("inc:")
    emitIR("  %ni = add i64 %ci, 1")
    emitIR("  store i64 %ni, ptr %i")
    emitIR("  br label %loop")
    emitIR("found:")
    emitIR("  %ri = trunc i64 %ci to i32")
    emitIR("  ret i32 %ri")
    emitIR("notfound:")
    emitIR("  ret i32 -1")
    emitIR("}")
    emitIR("")

    // ss_arraySlice — inherits source tag; retains ptr elements (tag=5)
    emitIR("define ptr @ss_arraySlice(ptr %arr, i32 %start, i32 %end_idx) {")
    emitIR("entry:")
    emitIR("  %ria = alloca i64, align 8")
    emitIR("  %len = load i64, ptr %arr")
    emitIR("  %s = sext i32 %start to i64")
    emitIR("  %e = sext i32 %end_idx to i64")
    emitIR("  %e2 = icmp sgt i64 %e, %len")
    emitIR("  %end = select i1 %e2, i64 %len, i64 %e")
    emitIR("  %nlen = sub i64 %end, %s")
    emitIR("  %nlen2 = icmp slt i64 %nlen, 0")
    emitIR("  %nlen3 = select i1 %nlen2, i64 0, i64 %nlen")
    emitIR("  %slots = add i64 %nlen3, 1")
    emitIR("  %sasize = mul i64 %slots, 8")
    emitIR("  %src_tagp = getelementptr i8, ptr %arr, i64 -8")
    emitIR("  %src_tag = load i32, ptr %src_tagp")
    emitIR("  %newarr = call ptr @ss_rc_calloc(i64 %sasize, i32 %src_tag)")
    emitIR("  store i64 %nlen3, ptr %newarr")
    emitIR("  %src = add i64 %s, 1")
    emitIR("  %srcp = getelementptr i64, ptr %arr, i64 %src")
    emitIR("  %dstp = getelementptr i64, ptr %newarr, i64 1")
    emitIR("  %bytes = mul i64 %nlen3, 8")
    emitIR("  %_1 = call ptr @memcpy(ptr %dstp, ptr %srcp, i64 %bytes)")
    emitIR("  ; If ptr array (tag=5), retain all copied elements")
    emitIR("  %is_ptr = icmp eq i32 %src_tag, 5")
    emitIR("  br i1 %is_ptr, label %retain.init, label %done")
    emitIR("retain.init:")
    emitIR("  store i64 0, ptr %ria")
    emitIR("  br label %retain.loop")
    emitIR("retain.loop:")
    emitIR("  %ri = load i64, ptr %ria")
    emitIR("  %rdone = icmp eq i64 %ri, %nlen3")
    emitIR("  br i1 %rdone, label %done, label %retain.body")
    emitIR("retain.body:")
    emitIR("  %rslot = add i64 %ri, 1")
    emitIR("  %rep = getelementptr i64, ptr %newarr, i64 %rslot")
    emitIR("  %rev = load i64, ptr %rep")
    emitIR("  %rptr = inttoptr i64 %rev to ptr")
    emitIR("  call void @ss_rc_retain(ptr %rptr)")
    emitIR("  %rni = add i64 %ri, 1")
    emitIR("  store i64 %rni, ptr %ria")
    emitIR("  br label %retain.loop")
    emitIR("done:")
    emitIR("  ret ptr %newarr")
    emitIR("}")
    emitIR("")

    // ss_arrayConcat — inherits source tag; retains ptr elements (tag=5)
    emitIR("define ptr @ss_arrayConcat(ptr %a, ptr %b) {")
    emitIR("entry:")
    emitIR("  %ria = alloca i64, align 8")
    emitIR("  %alen = load i64, ptr %a")
    emitIR("  %blen = load i64, ptr %b")
    emitIR("  %total = add i64 %alen, %blen")
    emitIR("  %slots = add i64 %total, 1")
    emitIR("  %casize = mul i64 %slots, 8")
    emitIR("  %src_tagp = getelementptr i8, ptr %a, i64 -8")
    emitIR("  %src_tag = load i32, ptr %src_tagp")
    emitIR("  %newarr = call ptr @ss_rc_calloc(i64 %casize, i32 %src_tag)")
    emitIR("  store i64 %total, ptr %newarr")
    emitIR("  %dst1 = getelementptr i64, ptr %newarr, i64 1")
    emitIR("  %src1 = getelementptr i64, ptr %a, i64 1")
    emitIR("  %abytes = mul i64 %alen, 8")
    emitIR("  %_1 = call ptr @memcpy(ptr %dst1, ptr %src1, i64 %abytes)")
    emitIR("  %dst2 = getelementptr i64, ptr %dst1, i64 %alen")
    emitIR("  %src2 = getelementptr i64, ptr %b, i64 1")
    emitIR("  %bbytes = mul i64 %blen, 8")
    emitIR("  %_2 = call ptr @memcpy(ptr %dst2, ptr %src2, i64 %bbytes)")
    emitIR("  ; If ptr array (tag=5), retain all elements")
    emitIR("  %is_ptr = icmp eq i32 %src_tag, 5")
    emitIR("  br i1 %is_ptr, label %retain.init, label %done")
    emitIR("retain.init:")
    emitIR("  store i64 0, ptr %ria")
    emitIR("  br label %retain.loop")
    emitIR("retain.loop:")
    emitIR("  %ri = load i64, ptr %ria")
    emitIR("  %rdone = icmp eq i64 %ri, %total")
    emitIR("  br i1 %rdone, label %done, label %retain.body")
    emitIR("retain.body:")
    emitIR("  %rslot = add i64 %ri, 1")
    emitIR("  %rep = getelementptr i64, ptr %newarr, i64 %rslot")
    emitIR("  %rev = load i64, ptr %rep")
    emitIR("  %rptr = inttoptr i64 %rev to ptr")
    emitIR("  call void @ss_rc_retain(ptr %rptr)")
    emitIR("  %rni = add i64 %ri, 1")
    emitIR("  store i64 %rni, ptr %ria")
    emitIR("  br label %retain.loop")
    emitIR("done:")
    emitIR("  ret ptr %newarr")
    emitIR("}")
    emitIR("")

    // ss_arrayToString — "[1, 2, 3]" style output (dynamic buffer)
    emitIR("define ptr @ss_arrayToString(ptr %arr) {")
    emitIR("entry:")
    emitIR("  %len = load i64, ptr %arr")
    emitIR("  %bufp = alloca ptr, align 8")
    emitIR("  %cap = alloca i64, align 8")
    emitIR("  %r0 = call ptr @ss_rc_alloc(i64 256, i32 0)")
    emitIR("  store ptr %r0, ptr %bufp")
    emitIR("  store i64 256, ptr %cap")
    emitIR("  store i8 91, ptr %r0")
    emitIR("  %pos = alloca i64, align 8")
    emitIR("  store i64 1, ptr %pos")
    emitIR("  %i = alloca i64, align 8")
    emitIR("  store i64 0, ptr %i")
    emitIR("  br label %loop")
    emitIR("loop:")
    emitIR("  %ci = load i64, ptr %i")
    emitIR("  %cond = icmp slt i64 %ci, %len")
    emitIR("  br i1 %cond, label %body, label %end")
    emitIR("body:")
    // ensure capacity for comma(2) + snprintf(256) + safety
    emitIR("  %bpos = load i64, ptr %pos")
    emitIR("  %bneed = add i64 %bpos, 260")
    emitIR("  %bbuf = call ptr @ss_rt_ensure_cap(ptr %bufp, ptr %cap, i64 %bneed)")
    emitIR("  %ci0 = icmp sgt i64 %ci, 0")
    emitIR("  br i1 %ci0, label %comma, label %val")
    emitIR("comma:")
    emitIR("  %cp2 = load i64, ptr %pos")
    emitIR("  %dp = getelementptr i8, ptr %bbuf, i64 %cp2")
    emitIR("  store i8 44, ptr %dp")
    emitIR("  %cp3 = add i64 %cp2, 1")
    emitIR("  %dp2 = getelementptr i8, ptr %bbuf, i64 %cp3")
    emitIR("  store i8 32, ptr %dp2")
    emitIR("  %cp4 = add i64 %cp3, 1")
    emitIR("  store i64 %cp4, ptr %pos")
    emitIR("  br label %val")
    emitIR("val:")
    emitIR("  %si = add i64 %ci, 1")
    emitIR("  %ep = getelementptr i64, ptr %arr, i64 %si")
    emitIR("  %ev = load i64, ptr %ep")
    emitIR("  %vp = load i64, ptr %pos")
    emitIR("  %dest = getelementptr i8, ptr %bbuf, i64 %vp")
    emitIR(`  %written = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %dest, i64 256, ptr @.rt.fmt.lld, i64 %ev)`)
    emitIR("  %w64 = sext i32 %written to i64")
    emitIR("  %np = add i64 %vp, %w64")
    emitIR("  store i64 %np, ptr %pos")
    emitIR("  %ni = add i64 %ci, 1")
    emitIR("  store i64 %ni, ptr %i")
    emitIR("  br label %loop")
    emitIR("end:")
    emitIR("  %fp = load i64, ptr %pos")
    emitIR("  %fn = add i64 %fp, 2")
    emitIR("  %fbuf = call ptr @ss_rt_ensure_cap(ptr %bufp, ptr %cap, i64 %fn)")
    emitIR("  %ep2 = getelementptr i8, ptr %fbuf, i64 %fp")
    emitIR("  store i8 93, ptr %ep2")
    emitIR("  %fp2 = add i64 %fp, 1")
    emitIR("  %ep3 = getelementptr i8, ptr %fbuf, i64 %fp2")
    emitIR("  store i8 0, ptr %ep3")
    emitIR("  ret ptr %fbuf")
    emitIR("}")
    emitIR("")
}

// ── Type conversions ──────────────────────────────────────────

function emitRuntimeConversions() {
    // ss_int_to_string
    emitIR("define ptr @ss_int_to_string(i32 %val) {")
    emitIR("  %buf = call ptr @ss_rc_alloc(i64 32, i32 0)")
    emitIR(`  %_1 = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %buf, i64 32, ptr @.rt.fmt.d, i32 %val)`)
    emitIR("  ret ptr %buf")
    emitIR("}")
    emitIR("")

    // ss_double_to_string
    emitIR("define ptr @ss_double_to_string(double %val) {")
    emitIR("  %buf = call ptr @ss_rc_alloc(i64 64, i32 0)")
    emitIR(`  %_1 = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %buf, i64 64, ptr @.rt.fmt.g, double %val)`)
    emitIR("  ret ptr %buf")
    emitIR("}")
    emitIR("")

    // ss_bool_to_string
    emitIR("define ptr @ss_bool_to_string(i32 %val) {")
    emitIR("  %nonzero = icmp ne i32 %val, 0")
    emitIR("  %result = select i1 %nonzero, ptr @.rt.str.true, ptr @.rt.str.false")
    emitIR("  ret ptr %result")
    emitIR("}")
    emitIR("")

    // ss_i64_to_string — always format as i64 integer (heuristic eliminated)
    emitIR("define ptr @ss_i64_to_string(i64 %val) {")
    emitIR("entry:")
    emitIR("  %buf = call ptr @ss_rc_alloc(i64 32, i32 0)")
    emitIR(`  %_1 = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %buf, i64 32, ptr @.rt.fmt.lld, i64 %val)`)
    emitIR("  ret ptr %buf")
    emitIR("}")
    emitIR("")

    // ss_parseInt
    emitIR("define i32 @ss_parseInt(ptr %s) {")
    emitIR("  %result = call i32 @atoi(ptr %s)")
    emitIR("  ret i32 %result")
    emitIR("}")
    emitIR("")

    // ss_parseDouble
    emitIR("define double @ss_parseDouble(ptr %s) {")
    emitIR("  %result = call double @atof(ptr %s)")
    emitIR("  ret double %result")
    emitIR("}")
    emitIR("")
}

// ── Process ───────────────────────────────────────────────────

function emitRuntimeProcess() {
    emitIR("define void @ss_exit(i32 %code) {")
    emitIR("  call void @exit(i32 %code)")
    emitIR("  unreachable")
    emitIR("}")
    emitIR("")

    emitIR("define i32 @ss_system(ptr %cmd) {")
    emitIR("  %result = call i32 @system(ptr %cmd)")
    emitIR("  ret i32 %result")
    emitIR("}")
    emitIR("")

    emitIR("define void @ss_initArgs(i32 %argc, ptr %argv) {")
    emitIR("  store i32 %argc, ptr @ss_argc")
    emitIR("  store ptr %argv, ptr @ss_argv")
    emitIR("  ret void")
    emitIR("}")
    emitIR("")

    emitIR("define i32 @ss_argCount() {")
    emitIR("  %count = load i32, ptr @ss_argc")
    emitIR("  ret i32 %count")
    emitIR("}")
    emitIR("")

    emitIR("define ptr @ss_argGet(i32 %idx) {")
    emitIR("entry:")
    emitIR("  %argc = load i32, ptr @ss_argc")
    emitIR("  %oob = icmp sge i32 %idx, %argc")
    emitIR("  br i1 %oob, label %oob_ret, label %ok")
    emitIR("oob_ret:")
    emitIR("  %empty = call ptr @ss_rc_strdup(ptr @.rt.str.empty)")
    emitIR("  ret ptr %empty")
    emitIR("ok:")
    emitIR("  %argv = load ptr, ptr @ss_argv")
    emitIR("  %idx64 = sext i32 %idx to i64")
    emitIR("  %argp = getelementptr ptr, ptr %argv, i64 %idx64")
    emitIR("  %arg = load ptr, ptr %argp")
    emitIR("  %result = call ptr @ss_rc_strdup(ptr %arg)")
    emitIR("  ret ptr %result")
    emitIR("}")
    emitIR("")

    emitIR("define ptr @ss_getenv(ptr %name) {")
    emitIR("entry:")
    emitIR("  %val = call ptr @getenv(ptr %name)")
    emitIR("  %isnull = icmp eq ptr %val, null")
    emitIR("  br i1 %isnull, label %nil, label %ok")
    emitIR("nil:")
    emitIR("  %empty = call ptr @ss_rc_strdup(ptr @.rt.str.empty)")
    emitIR("  ret ptr %empty")
    emitIR("ok:")
    emitIR("  %result = call ptr @ss_rc_strdup(ptr %val)")
    emitIR("  ret ptr %result")
    emitIR("}")
    emitIR("")
}

// ── Math ──────────────────────────────────────────────────────

function emitRuntimeMath() {
    emitIR("define double @ss_sqrt(double %x) {")
    emitIR("  %result = call double @sqrt(double %x)")
    emitIR("  ret double %result")
    emitIR("}")
    emitIR("define double @ss_abs(double %x) {")
    emitIR("  %result = call double @fabs(double %x)")
    emitIR("  ret double %result")
    emitIR("}")
    emitIR("define double @ss_floor(double %x) {")
    emitIR("  %result = call double @floor(double %x)")
    emitIR("  ret double %result")
    emitIR("}")
    emitIR("define double @ss_ceil(double %x) {")
    emitIR("  %result = call double @ceil(double %x)")
    emitIR("  ret double %result")
    emitIR("}")
    emitIR("define double @ss_round(double %x) {")
    emitIR("  %result = call double @round(double %x)")
    emitIR("  ret double %result")
    emitIR("}")
    emitIR("define double @ss_pow(double %base, double %exp) {")
    emitIR("  %result = call double @pow(double %base, double %exp)")
    emitIR("  ret double %result")
    emitIR("}")
    emitIR("define double @ss_log(double %x) {")
    emitIR("  %result = call double @log(double %x)")
    emitIR("  ret double %result")
    emitIR("}")
    emitIR("define double @ss_sin(double %x) {")
    emitIR("  %result = call double @sin(double %x)")
    emitIR("  ret double %result")
    emitIR("}")
    emitIR("define double @ss_cos(double %x) {")
    emitIR("  %result = call double @cos(double %x)")
    emitIR("  ret double %result")
    emitIR("}")
    emitIR("")
    emitIR("define double @ss_min(double %a, double %b) {")
    emitIR("  %cmp = fcmp olt double %a, %b")
    emitIR("  %result = select i1 %cmp, double %a, double %b")
    emitIR("  ret double %result")
    emitIR("}")
    emitIR("")
    emitIR("define double @ss_max(double %a, double %b) {")
    emitIR("  %cmp = fcmp ogt double %a, %b")
    emitIR("  %result = select i1 %cmp, double %a, double %b")
    emitIR("  ret double %result")
    emitIR("}")
    emitIR("")
    emitIR("define double @ss_random() {")
    emitIR("  %raw = call i32 @rand()")
    emitIR("  %fp = sitofp i32 %raw to double")
    emitIR("  %result = fdiv double %fp, 2147483647.0")
    emitIR("  ret double %result")
    emitIR("}")
    emitIR("")
}

// ── Filesystem ────────────────────────────────────────────────

function emitRuntimeFS() {
    // ss_mkdir
    emitIR("define i32 @ss_mkdir(ptr %path) {")
    emitIR("  %result = call i32 @mkdir(ptr %path, i32 493)")
    emitIR("  ret i32 %result")
    emitIR("}")
    emitIR("")

    // ss_mkdirp — recursive mkdir
    emitIR("define i32 @ss_mkdirp(ptr %path) {")
    emitIR("entry:")
    emitIR("  %len = call i64 @strlen(ptr %path)")
    emitIR("  %alloc = add i64 %len, 1")
    emitIR("  %buf = call ptr @malloc(i64 %alloc)")
    emitIR("  %_1 = call ptr @memcpy(ptr %buf, ptr %path, i64 %len)")
    emitIR("  %term = getelementptr i8, ptr %buf, i64 %len")
    emitIR("  store i8 0, ptr %term")
    emitIR("  %i = alloca i64, align 8")
    emitIR("  store i64 1, ptr %i")
    emitIR("  br label %loop")
    emitIR("loop:")
    emitIR("  %ci = load i64, ptr %i")
    emitIR("  %cond = icmp sle i64 %ci, %len")
    emitIR("  br i1 %cond, label %body, label %final")
    emitIR("body:")
    emitIR("  %cp = getelementptr i8, ptr %buf, i64 %ci")
    emitIR("  %ch = load i8, ptr %cp")
    emitIR("  %is_slash = icmp eq i8 %ch, 47")
    emitIR("  %is_end = icmp eq i64 %ci, %len")
    emitIR("  %should_mkdir = or i1 %is_slash, %is_end")
    emitIR("  br i1 %should_mkdir, label %do_mkdir, label %next")
    emitIR("do_mkdir:")
    emitIR("  store i8 0, ptr %cp")
    emitIR("  %_2 = call i32 @mkdir(ptr %buf, i32 493)")
    emitIR("  store i8 %ch, ptr %cp")
    emitIR("  br label %next")
    emitIR("next:")
    emitIR("  %ni = add i64 %ci, 1")
    emitIR("  store i64 %ni, ptr %i")
    emitIR("  br label %loop")
    emitIR("final:")
    emitIR("  call void @free(ptr %buf)")
    emitIR("  ret i32 0")
    emitIR("}")
    emitIR("")

    // ss_fileExists
    emitIR("define i32 @ss_fileExists(ptr %path) {")
    emitIR("  %statbuf = alloca [144 x i8], align 8")
    emitIR("  %rc = call i32 @stat(ptr %path, ptr %statbuf)")
    emitIR("  %exists = icmp eq i32 %rc, 0")
    emitIR("  %result = zext i1 %exists to i32")
    emitIR("  ret i32 %result")
    emitIR("}")
    emitIR("")

    // ss_fileSize
    emitIR("define i64 @ss_fileSize(ptr %path) {")
    emitIR("entry:")
    emitIR("  %statbuf = alloca [144 x i8], align 8")
    emitIR("  %rc = call i32 @stat(ptr %path, ptr %statbuf)")
    emitIR("  %failed = icmp ne i32 %rc, 0")
    emitIR("  br i1 %failed, label %fail, label %ok")
    emitIR("ok:")
    emitIR("  %sizep = getelementptr i8, ptr %statbuf, i64 48")
    emitIR("  %size = load i64, ptr %sizep")
    emitIR("  ret i64 %size")
    emitIR("fail:")
    emitIR("  ret i64 -1")
    emitIR("}")
    emitIR("")

    // ss_removeFile
    emitIR("define i32 @ss_removeFile(ptr %path) {")
    emitIR("  %result = call i32 @remove(ptr %path)")
    emitIR("  ret i32 %result")
    emitIR("}")
    emitIR("")

    // ss_renameFile
    emitIR("define i32 @ss_renameFile(ptr %oldpath, ptr %newpath) {")
    emitIR("  %result = call i32 @rename(ptr %oldpath, ptr %newpath)")
    emitIR("  ret i32 %result")
    emitIR("}")
    emitIR("")

    // ss_listDir (dynamic buffer)
    emitIR("define ptr @ss_listDir(ptr %path) {")
    emitIR("entry:")
    emitIR("  %dp = call ptr @opendir(ptr %path)")
    emitIR("  %isnull = icmp eq ptr %dp, null")
    emitIR("  br i1 %isnull, label %fail, label %init")
    emitIR("fail:")
    emitIR("  %empty = call ptr @ss_rc_strdup(ptr @.rt.str.empty)")
    emitIR("  ret ptr %empty")
    emitIR("init:")
    emitIR("  %bufp = alloca ptr, align 8")
    emitIR("  %cap = alloca i64, align 8")
    emitIR("  %r0 = call ptr @ss_rc_alloc(i64 4096, i32 0)")
    emitIR("  store ptr %r0, ptr %bufp")
    emitIR("  store i64 4096, ptr %cap")
    emitIR("  %pos = alloca i64, align 8")
    emitIR("  store i64 0, ptr %pos")
    emitIR("  br label %loop")
    emitIR("loop:")
    emitIR("  %ent = call ptr @readdir(ptr %dp)")
    emitIR("  %done = icmp eq ptr %ent, null")
    emitIR("  br i1 %done, label %finish, label %process")
    emitIR("process:")
    emitIR("  %name = getelementptr i8, ptr %ent, i64 19")
    emitIR("  %nlen = call i64 @strlen(ptr %name)")
    emitIR("  %cpos = load i64, ptr %pos")
    emitIR("  ; Skip . and ..")
    emitIR("  %c0 = load i8, ptr %name")
    emitIR("  %is_dot = icmp eq i8 %c0, 46")
    emitIR("  br i1 %is_dot, label %chk_dot, label %copy")
    emitIR("chk_dot:")
    emitIR("  %c1 = getelementptr i8, ptr %name, i64 1")
    emitIR("  %c1v = load i8, ptr %c1")
    emitIR("  %is_dotdot = icmp eq i8 %c1v, 46")
    emitIR("  %is_end1 = icmp eq i8 %c1v, 0")
    emitIR("  %skip = or i1 %is_dotdot, %is_end1")
    emitIR("  br i1 %skip, label %loop, label %copy")
    emitIR("copy:")
    // ensure capacity for name + newline + null terminator
    emitIR("  %need = add i64 %cpos, %nlen")
    emitIR("  %need2 = add i64 %need, 2")
    emitIR("  %cbuf = call ptr @ss_rt_ensure_cap(ptr %bufp, ptr %cap, i64 %need2)")
    emitIR("  %dst = getelementptr i8, ptr %cbuf, i64 %cpos")
    emitIR("  %_1 = call ptr @memcpy(ptr %dst, ptr %name, i64 %nlen)")
    emitIR("  %np1 = add i64 %cpos, %nlen")
    emitIR("  %nlp = getelementptr i8, ptr %cbuf, i64 %np1")
    emitIR("  store i8 10, ptr %nlp")
    emitIR("  %np2 = add i64 %np1, 1")
    emitIR("  store i64 %np2, ptr %pos")
    emitIR("  br label %loop")
    emitIR("finish:")
    emitIR("  %_2 = call i32 @closedir(ptr %dp)")
    emitIR("  %fpos = load i64, ptr %pos")
    emitIR("  %fbuf = load ptr, ptr %bufp")
    emitIR("  %fterm = getelementptr i8, ptr %fbuf, i64 %fpos")
    emitIR("  store i8 0, ptr %fterm")
    emitIR("  ret ptr %fbuf")
    emitIR("}")
    emitIR("")

    // ss_timeMs
    emitIR("define i64 @ss_timeMs() {")
    emitIR("  %ts = alloca [16 x i8], align 8")
    emitIR("  %_1 = call i32 @clock_gettime(i32 1, ptr %ts)")
    emitIR("  %sec = load i64, ptr %ts")
    emitIR("  %nsp = getelementptr i8, ptr %ts, i64 8")
    emitIR("  %nsec = load i64, ptr %nsp")
    emitIR("  %ms_sec = mul i64 %sec, 1000")
    emitIR("  %ms_ns = sdiv i64 %nsec, 1000000")
    emitIR("  %result = add i64 %ms_sec, %ms_ns")
    emitIR("  ret i64 %result")
    emitIR("}")
    emitIR("")

    // ss_timeUnix
    emitIR("define i64 @ss_timeUnix() {")
    emitIR("  %result = call i64 @time(ptr null)")
    emitIR("  ret i64 %result")
    emitIR("}")
    emitIR("")
}

// ── Network ───────────────────────────────────────────────────

function emitRuntimeNet() {
    // ss_tcpListen
    emitIR("define i32 @ss_tcpListen(i32 %port) {")
    emitIR("entry:")
    emitIR("  %fd = call i32 @socket(i32 2, i32 1, i32 0)")
    emitIR("  %bad = icmp slt i32 %fd, 0")
    emitIR("  br i1 %bad, label %fail, label %setsock")
    emitIR("setsock:")
    emitIR("  %optval = alloca i32, align 4")
    emitIR("  store i32 1, ptr %optval")
    emitIR("  %_1 = call i32 @setsockopt(i32 %fd, i32 1, i32 2, ptr %optval, i32 4)")
    emitIR("  %addr = alloca [16 x i8], align 4")
    emitIR("  %_2 = call ptr @memset(ptr %addr, i32 0, i64 16)")
    emitIR("  store i16 2, ptr %addr")
    emitIR("  %port16 = trunc i32 %port to i16")
    emitIR("  %portn = call i16 @htons(i16 %port16)")
    emitIR("  %pptr = getelementptr i8, ptr %addr, i64 2")
    emitIR("  store i16 %portn, ptr %pptr")
    emitIR("  %br = call i32 @bind(i32 %fd, ptr %addr, i32 16)")
    emitIR("  %bfail = icmp slt i32 %br, 0")
    emitIR("  br i1 %bfail, label %close_fail, label %do_listen")
    emitIR("do_listen:")
    emitIR("  %lr = call i32 @listen(i32 %fd, i32 128)")
    emitIR("  %lfail = icmp slt i32 %lr, 0")
    emitIR("  br i1 %lfail, label %close_fail, label %done")
    emitIR("done:")
    emitIR("  ret i32 %fd")
    emitIR("close_fail:")
    emitIR("  %_3 = call i32 @close(i32 %fd)")
    emitIR("  br label %fail")
    emitIR("fail:")
    emitIR("  ret i32 -1")
    emitIR("}")
    emitIR("")

    // ss_tcpAccept
    emitIR("define i32 @ss_tcpAccept(i32 %fd) {")
    emitIR("  %client = call i32 @accept(i32 %fd, ptr null, ptr null)")
    emitIR("  ret i32 %client")
    emitIR("}")
    emitIR("")

    // ss_tcpRead
    emitIR("define ptr @ss_tcpRead(i32 %fd, i32 %maxlen) {")
    emitIR("  %maxlen64 = sext i32 %maxlen to i64")
    emitIR("  %alloc = add i64 %maxlen64, 1")
    emitIR("  %buf = call ptr @ss_rc_alloc(i64 %alloc, i32 0)")
    emitIR("  %nread = call i64 @read(i32 %fd, ptr %buf, i64 %maxlen64)")
    emitIR("  %neg = icmp slt i64 %nread, 0")
    emitIR("  %safe = select i1 %neg, i64 0, i64 %nread")
    emitIR("  %term = getelementptr i8, ptr %buf, i64 %safe")
    emitIR("  store i8 0, ptr %term")
    emitIR("  ret ptr %buf")
    emitIR("}")
    emitIR("")

    // ss_tcpWrite
    emitIR("define i32 @ss_tcpWrite(i32 %fd, ptr %data) {")
    emitIR("  %len = call i64 @strlen(ptr %data)")
    emitIR("  %nwritten = call i64 @write(i32 %fd, ptr %data, i64 %len)")
    emitIR("  %result = trunc i64 %nwritten to i32")
    emitIR("  ret i32 %result")
    emitIR("}")
    emitIR("")

    // ss_tcpWriteBytes
    emitIR("define i32 @ss_tcpWriteBytes(i32 %fd, ptr %data, i32 %len) {")
    emitIR("  %len64 = sext i32 %len to i64")
    emitIR("  %nwritten = call i64 @write(i32 %fd, ptr %data, i64 %len64)")
    emitIR("  %result = trunc i64 %nwritten to i32")
    emitIR("  ret i32 %result")
    emitIR("}")
    emitIR("")

    // ss_tcpClose
    emitIR("define void @ss_tcpClose(i32 %fd) {")
    emitIR("  %_1 = call i32 @close(i32 %fd)")
    emitIR("  ret void")
    emitIR("}")
    emitIR("")
}

// ── HashMap ───────────────────────────────────────────────────
// Layout: 64 bucket pointers (ptr) + size (i32) = 520 bytes
// MapEntry: key (ptr, offset 0), value (i64, offset 8), next (ptr, offset 16) = 24 bytes

function emitRuntimeMap() {
    // hash_str — djb2 hash mod 64
    emitIR("define internal i32 @hash_str(ptr %s) {")
    emitIR("entry:")
    emitIR("  %h = alloca i32, align 4")
    emitIR("  store i32 5381, ptr %h")
    emitIR("  %i = alloca i64, align 8")
    emitIR("  store i64 0, ptr %i")
    emitIR("  br label %loop")
    emitIR("loop:")
    emitIR("  %ci = load i64, ptr %i")
    emitIR("  %cp = getelementptr i8, ptr %s, i64 %ci")
    emitIR("  %ch = load i8, ptr %cp")
    emitIR("  %done = icmp eq i8 %ch, 0")
    emitIR("  br i1 %done, label %ret, label %body")
    emitIR("body:")
    emitIR("  %hv = load i32, ptr %h")
    emitIR("  %hv2 = mul i32 %hv, 33")
    emitIR("  %cv = zext i8 %ch to i32")
    emitIR("  %hv3 = add i32 %hv2, %cv")
    emitIR("  store i32 %hv3, ptr %h")
    emitIR("  %ni = add i64 %ci, 1")
    emitIR("  store i64 %ni, ptr %i")
    emitIR("  br label %loop")
    emitIR("ret:")
    emitIR("  %rv = load i32, ptr %h")
    emitIR("  %rm = urem i32 %rv, 64")
    emitIR("  ret i32 %rm")
    emitIR("}")
    emitIR("")

    // find_entry — internal helper
    emitIR("define internal ptr @find_entry(ptr %map, ptr %key) {")
    emitIR("entry:")
    emitIR("  %idx = call i32 @hash_str(ptr %key)")
    emitIR("  %idx64 = sext i32 %idx to i64")
    emitIR("  %bp = getelementptr ptr, ptr %map, i64 %idx64")
    emitIR("  %e0 = load ptr, ptr %bp")
    emitIR("  %ea = alloca ptr, align 8")
    emitIR("  store ptr %e0, ptr %ea")
    emitIR("  br label %loop")
    emitIR("loop:")
    emitIR("  %e = load ptr, ptr %ea")
    emitIR("  %nil = icmp eq ptr %e, null")
    emitIR("  br i1 %nil, label %notfound, label %cmp")
    emitIR("cmp:")
    emitIR("  %ek = load ptr, ptr %e")
    emitIR("  %eq = call i32 @strcmp(ptr %ek, ptr %key)")
    emitIR("  %match = icmp eq i32 %eq, 0")
    emitIR("  br i1 %match, label %found, label %next")
    emitIR("next:")
    emitIR("  %np = getelementptr i8, ptr %e, i64 16")
    emitIR("  %nv = load ptr, ptr %np")
    emitIR("  store ptr %nv, ptr %ea")
    emitIR("  br label %loop")
    emitIR("found:")
    emitIR("  ret ptr %e")
    emitIR("notfound:")
    emitIR("  ret ptr null")
    emitIR("}")
    emitIR("")

    // ss_mapNew
    emitIR("define ptr @ss_mapNew() {")
    emitIR("  %map = call ptr @ss_rc_calloc(i64 520, i32 2)")
    emitIR("  ret ptr %map")
    emitIR("}")
    emitIR("")

    // ss_mapSet — on update: release old ptr value if val_type=1 (offset 516)
    emitIR("define void @ss_mapSet(ptr %map, ptr %key, i64 %val) {")
    emitIR("entry:")
    emitIR("  %e = call ptr @find_entry(ptr %map, ptr %key)")
    emitIR("  %found = icmp ne ptr %e, null")
    emitIR("  br i1 %found, label %update, label %insert")
    emitIR("update:")
    emitIR("  %vp = getelementptr i8, ptr %e, i64 8")
    emitIR("  ; Release old value if map has ptr values")
    emitIR("  %uvtpp = getelementptr i8, ptr %map, i64 516")
    emitIR("  %uvtp = load i32, ptr %uvtpp")
    emitIR("  %uisptr = icmp eq i32 %uvtp, 1")
    emitIR("  br i1 %uisptr, label %rel.old, label %do.store")
    emitIR("rel.old:")
    emitIR("  %oldv = load i64, ptr %vp")
    emitIR("  %oldp = inttoptr i64 %oldv to ptr")
    emitIR("  call void @ss_rc_release(ptr %oldp)")
    emitIR("  br label %do.store")
    emitIR("do.store:")
    emitIR("  store i64 %val, ptr %vp")
    emitIR("  ret void")
    emitIR("insert:")
    emitIR("  %ne = call ptr @malloc(i64 24)")
    emitIR("  %kd = call ptr @ss_rc_strdup(ptr %key)")
    emitIR("  store ptr %kd, ptr %ne")
    emitIR("  %nvp = getelementptr i8, ptr %ne, i64 8")
    emitIR("  store i64 %val, ptr %nvp")
    emitIR("  %idx = call i32 @hash_str(ptr %key)")
    emitIR("  %idx64 = sext i32 %idx to i64")
    emitIR("  %bp = getelementptr ptr, ptr %map, i64 %idx64")
    emitIR("  %old = load ptr, ptr %bp")
    emitIR("  %nnp = getelementptr i8, ptr %ne, i64 16")
    emitIR("  store ptr %old, ptr %nnp")
    emitIR("  store ptr %ne, ptr %bp")
    emitIR("  ; Increment size")
    emitIR("  %szp = getelementptr i8, ptr %map, i64 512")
    emitIR("  %sz = load i32, ptr %szp")
    emitIR("  %sz1 = add i32 %sz, 1")
    emitIR("  store i32 %sz1, ptr %szp")
    emitIR("  ret void")
    emitIR("}")
    emitIR("")

    // ss_mapGet
    emitIR("define i64 @ss_mapGet(ptr %map, ptr %key) {")
    emitIR("entry:")
    emitIR("  %e = call ptr @find_entry(ptr %map, ptr %key)")
    emitIR("  %nil = icmp eq ptr %e, null")
    emitIR("  br i1 %nil, label %nf, label %ok")
    emitIR("ok:")
    emitIR("  %vp = getelementptr i8, ptr %e, i64 8")
    emitIR("  %v = load i64, ptr %vp")
    emitIR("  ret i64 %v")
    emitIR("nf:")
    emitIR("  ret i64 0")
    emitIR("}")
    emitIR("")

    // ss_mapGetString
    emitIR("define ptr @ss_mapGetString(ptr %map, ptr %key) {")
    emitIR("entry:")
    emitIR("  %e = call ptr @find_entry(ptr %map, ptr %key)")
    emitIR("  %nil = icmp eq ptr %e, null")
    emitIR("  br i1 %nil, label %nf, label %ok")
    emitIR("ok:")
    emitIR("  %vp = getelementptr i8, ptr %e, i64 8")
    emitIR("  %v = load i64, ptr %vp")
    emitIR("  %p = inttoptr i64 %v to ptr")
    emitIR("  ret ptr %p")
    emitIR("nf:")
    emitIR("  ret ptr @.rt.str.empty")
    emitIR("}")
    emitIR("")

    // ss_mapHas
    emitIR("define i32 @ss_mapHas(ptr %map, ptr %key) {")
    emitIR("  %e = call ptr @find_entry(ptr %map, ptr %key)")
    emitIR("  %found = icmp ne ptr %e, null")
    emitIR("  %result = zext i1 %found to i32")
    emitIR("  ret i32 %result")
    emitIR("}")
    emitIR("")

    // ss_mapSize
    emitIR("define i32 @ss_mapSize(ptr %map) {")
    emitIR("  %szp = getelementptr i8, ptr %map, i64 512")
    emitIR("  %size = load i32, ptr %szp")
    emitIR("  ret i32 %size")
    emitIR("}")
    emitIR("")

    // ss_mapDelete
    emitIR("define void @ss_mapDelete(ptr %map, ptr %key) {")
    emitIR("entry:")
    emitIR("  %idx = call i32 @hash_str(ptr %key)")
    emitIR("  %idx64 = sext i32 %idx to i64")
    emitIR("  %bp = getelementptr ptr, ptr %map, i64 %idx64")
    emitIR("  %prev = alloca ptr, align 8")
    emitIR("  store ptr null, ptr %prev")
    emitIR("  %ea = alloca ptr, align 8")
    emitIR("  %e0 = load ptr, ptr %bp")
    emitIR("  store ptr %e0, ptr %ea")
    emitIR("  br label %loop")
    emitIR("loop:")
    emitIR("  %e = load ptr, ptr %ea")
    emitIR("  %nil = icmp eq ptr %e, null")
    emitIR("  br i1 %nil, label %done, label %cmp")
    emitIR("cmp:")
    emitIR("  %ek = load ptr, ptr %e")
    emitIR("  %eq = call i32 @strcmp(ptr %ek, ptr %key)")
    emitIR("  %match = icmp eq i32 %eq, 0")
    emitIR("  br i1 %match, label %remove, label %advance")
    emitIR("advance:")
    emitIR("  store ptr %e, ptr %prev")
    emitIR("  %nnp = getelementptr i8, ptr %e, i64 16")
    emitIR("  %nv = load ptr, ptr %nnp")
    emitIR("  store ptr %nv, ptr %ea")
    emitIR("  br label %loop")
    emitIR("remove:")
    emitIR("  %enp = getelementptr i8, ptr %e, i64 16")
    emitIR("  %enxt = load ptr, ptr %enp")
    emitIR("  %pv = load ptr, ptr %prev")
    emitIR("  %has_prev = icmp ne ptr %pv, null")
    emitIR("  br i1 %has_prev, label %unlink_mid, label %unlink_head")
    emitIR("unlink_head:")
    emitIR("  store ptr %enxt, ptr %bp")
    emitIR("  br label %dec")
    emitIR("unlink_mid:")
    emitIR("  %pnp = getelementptr i8, ptr %pv, i64 16")
    emitIR("  store ptr %enxt, ptr %pnp")
    emitIR("  br label %dec")
    emitIR("dec:")
    emitIR("  %szp = getelementptr i8, ptr %map, i64 512")
    emitIR("  %sz = load i32, ptr %szp")
    emitIR("  %sz1 = sub i32 %sz, 1")
    emitIR("  store i32 %sz1, ptr %szp")
    emitIR("  ; Release key (RC string) before freeing entry")
    emitIR("  %dk = load ptr, ptr %e")
    emitIR("  call void @ss_rc_release(ptr %dk)")
    emitIR("  ; Release value if map has ptr values")
    emitIR("  %dvtpp = getelementptr i8, ptr %map, i64 516")
    emitIR("  %dvtp = load i32, ptr %dvtpp")
    emitIR("  %disptr = icmp eq i32 %dvtp, 1")
    emitIR("  br i1 %disptr, label %del.relval, label %del.free")
    emitIR("del.relval:")
    emitIR("  %dvp = getelementptr i8, ptr %e, i64 8")
    emitIR("  %dvi = load i64, ptr %dvp")
    emitIR("  %dvptr = inttoptr i64 %dvi to ptr")
    emitIR("  call void @ss_rc_release(ptr %dvptr)")
    emitIR("  br label %del.free")
    emitIR("del.free:")
    emitIR("  call void @free(ptr %e)")
    emitIR("  br label %done")
    emitIR("done:")
    emitIR("  ret void")
    emitIR("}")
    emitIR("")

    // ss_mapKeys — returns newline-separated string (dynamic buffer)
    emitIR("define ptr @ss_mapKeys(ptr %map) {")
    emitIR("entry:")
    emitIR("  %bufp = alloca ptr, align 8")
    emitIR("  %cap = alloca i64, align 8")
    emitIR("  %r0 = call ptr @ss_rc_alloc(i64 4096, i32 0)")
    emitIR("  store ptr %r0, ptr %bufp")
    emitIR("  store i64 4096, ptr %cap")
    emitIR("  %pos = alloca i64, align 8")
    emitIR("  store i64 0, ptr %pos")
    emitIR("  %bi = alloca i64, align 8")
    emitIR("  store i64 0, ptr %bi")
    emitIR("  br label %bloop")
    emitIR("bloop:")
    emitIR("  %cbi = load i64, ptr %bi")
    emitIR("  %bcond = icmp slt i64 %cbi, 64")
    emitIR("  br i1 %bcond, label %bbody, label %done")
    emitIR("bbody:")
    emitIR("  %bp = getelementptr ptr, ptr %map, i64 %cbi")
    emitIR("  %e0 = load ptr, ptr %bp")
    emitIR("  %ea = alloca ptr, align 8")
    emitIR("  store ptr %e0, ptr %ea")
    emitIR("  br label %eloop")
    emitIR("eloop:")
    emitIR("  %e = load ptr, ptr %ea")
    emitIR("  %enil = icmp eq ptr %e, null")
    emitIR("  br i1 %enil, label %bnext, label %ecopy")
    emitIR("ecopy:")
    emitIR("  %ek = load ptr, ptr %e")
    emitIR("  %klen = call i64 @strlen(ptr %ek)")
    emitIR("  %cpos = load i64, ptr %pos")
    // ensure capacity for key + newline + null
    emitIR("  %need = add i64 %cpos, %klen")
    emitIR("  %need2 = add i64 %need, 2")
    emitIR("  %cbuf = call ptr @ss_rt_ensure_cap(ptr %bufp, ptr %cap, i64 %need2)")
    emitIR("  %dst = getelementptr i8, ptr %cbuf, i64 %cpos")
    emitIR("  %_1 = call ptr @memcpy(ptr %dst, ptr %ek, i64 %klen)")
    emitIR("  %np1 = add i64 %cpos, %klen")
    emitIR("  %nlp = getelementptr i8, ptr %cbuf, i64 %np1")
    emitIR("  store i8 10, ptr %nlp")
    emitIR("  %np2 = add i64 %np1, 1")
    emitIR("  store i64 %np2, ptr %pos")
    emitIR("  %enp = getelementptr i8, ptr %e, i64 16")
    emitIR("  %nxt = load ptr, ptr %enp")
    emitIR("  store ptr %nxt, ptr %ea")
    emitIR("  br label %eloop")
    emitIR("bnext:")
    emitIR("  %nbi = add i64 %cbi, 1")
    emitIR("  store i64 %nbi, ptr %bi")
    emitIR("  br label %bloop")
    emitIR("done:")
    emitIR("  %fpos = load i64, ptr %pos")
    emitIR("  %fbuf = load ptr, ptr %bufp")
    emitIR("  %fterm = getelementptr i8, ptr %fbuf, i64 %fpos")
    emitIR("  store i8 0, ptr %fterm")
    emitIR("  ret ptr %fbuf")
    emitIR("}")
    emitIR("")
}

// ── Exception handling ────────────────────────────────────────

function emitRuntimeExceptions() {
    // ss_throw: store message, longjmp if handler exists, else print+exit
    emitIR("define void @ss_throw(ptr %msg) {")
    emitIR("entry:")
    emitIR("  store ptr %msg, ptr @ss_exc_msg")
    emitIR("  %depth = load i32, ptr @ss_exc_depth")
    emitIR("  %has_handler = icmp sgt i32 %depth, 0")
    emitIR("  br i1 %has_handler, label %do_jump, label %no_handler")
    emitIR("do_jump:")
    emitIR("  %d1 = sub i32 %depth, 1")
    emitIR("  %offset = mul i32 %d1, 200")
    emitIR("  %off64 = sext i32 %offset to i64")
    emitIR("  %bufptr = getelementptr i8, ptr @ss_jmpbuf, i64 %off64")
    emitIR("  call void @longjmp(ptr %bufptr, i32 1)")
    emitIR("  unreachable")
    emitIR("no_handler:")
    emitIR("  %_1 = call ptr @ss_string_concat(ptr @.rt.str.uncaught, ptr %msg)")
    emitIR("  call i32 @puts(ptr %_1)")
    emitIR("  call void @exit(i32 1)")
    emitIR("  unreachable")
    emitIR("}")
    emitIR("")
}

// ── SQLite bindings ───────────────────────────────────────────

function emitRuntimeSQLite() {
    // ss_sqlite3_open(path) → db pointer (as ptr)
    emitIR("define ptr @ss_sqlite3_open(ptr %path) {")
    emitIR("entry:")
    emitIR("  %dbpp = alloca ptr, align 8")
    emitIR("  %rc = call i32 @sqlite3_open(ptr %path, ptr %dbpp)")
    emitIR("  %ok = icmp eq i32 %rc, 0")
    emitIR("  br i1 %ok, label %success, label %fail")
    emitIR("success:")
    emitIR("  %db = load ptr, ptr %dbpp")
    emitIR("  ret ptr %db")
    emitIR("fail:")
    emitIR("  ret ptr null")
    emitIR("}")
    emitIR("")

    // ss_sqlite3_close(db)
    emitIR("define void @ss_sqlite3_close(ptr %db) {")
    emitIR("  %_1 = call i32 @sqlite3_close(ptr %db)")
    emitIR("  ret void")
    emitIR("}")
    emitIR("")

    // ss_sqlite3_exec(db, sql) → 0 on success
    emitIR("define i32 @ss_sqlite3_exec(ptr %db, ptr %sql) {")
    emitIR("  %rc = call i32 @sqlite3_exec(ptr %db, ptr %sql, ptr null, ptr null, ptr null)")
    emitIR("  ret i32 %rc")
    emitIR("}")
    emitIR("")

    // ss_sqlite3_query(db, sql) → "col1\tcol2\nval1\tval2\n..." result string (dynamic buffer)
    emitIR("define ptr @ss_sqlite3_query(ptr %db, ptr %sql) {")
    emitIR("entry:")
    emitIR("  %stmtpp = alloca ptr, align 8")
    emitIR("  %rc = call i32 @sqlite3_prepare_v2(ptr %db, ptr %sql, i32 -1, ptr %stmtpp, ptr null)")
    emitIR("  %ok = icmp eq i32 %rc, 0")
    emitIR("  br i1 %ok, label %prepared, label %empty")
    emitIR("empty:")
    emitIR("  %e = call ptr @ss_rc_strdup(ptr @.rt.str.empty)")
    emitIR("  ret ptr %e")
    emitIR("prepared:")
    emitIR("  %stmt = load ptr, ptr %stmtpp")
    emitIR("  %ncols = call i32 @sqlite3_column_count(ptr %stmt)")
    emitIR("  %bufp = alloca ptr, align 8")
    emitIR("  %cap = alloca i64, align 8")
    emitIR("  %r0 = call ptr @ss_rc_alloc(i64 4096, i32 0)")
    emitIR("  store ptr %r0, ptr %bufp")
    emitIR("  store i64 4096, ptr %cap")
    emitIR("  %pos = alloca i64, align 8")
    emitIR("  store i64 0, ptr %pos")
    // Write column headers
    emitIR("  %ci = alloca i32, align 4")
    emitIR("  store i32 0, ptr %ci")
    emitIR("  br label %hdr.loop")
    emitIR("hdr.loop:")
    emitIR("  %hci = load i32, ptr %ci")
    emitIR("  %hcond = icmp slt i32 %hci, %ncols")
    emitIR("  br i1 %hcond, label %hdr.body, label %hdr.done")
    emitIR("hdr.body:")
    emitIR("  %hci2 = load i32, ptr %ci")
    // Add tab separator between columns
    emitIR("  %needtab = icmp sgt i32 %hci2, 0")
    emitIR("  br i1 %needtab, label %hdr.tab, label %hdr.name")
    emitIR("hdr.tab:")
    emitIR("  %tp = load i64, ptr %pos")
    emitIR("  %tn = add i64 %tp, 2")
    emitIR("  %tbuf = call ptr @ss_rt_ensure_cap(ptr %bufp, ptr %cap, i64 %tn)")
    emitIR("  %td = getelementptr i8, ptr %tbuf, i64 %tp")
    emitIR("  store i8 9, ptr %td")
    emitIR("  %tp1 = add i64 %tp, 1")
    emitIR("  store i64 %tp1, ptr %pos")
    emitIR("  br label %hdr.name")
    emitIR("hdr.name:")
    emitIR("  %cname = call ptr @sqlite3_column_name(ptr %stmt, i32 %hci2)")
    emitIR("  %cnlen = call i64 @strlen(ptr %cname)")
    emitIR("  %cp2 = load i64, ptr %pos")
    emitIR("  %hn = add i64 %cp2, %cnlen")
    emitIR("  %hn2 = add i64 %hn, 1")
    emitIR("  %hbuf = call ptr @ss_rt_ensure_cap(ptr %bufp, ptr %cap, i64 %hn2)")
    emitIR("  %cdst = getelementptr i8, ptr %hbuf, i64 %cp2")
    emitIR("  %_2 = call ptr @memcpy(ptr %cdst, ptr %cname, i64 %cnlen)")
    emitIR("  %cp3 = add i64 %cp2, %cnlen")
    emitIR("  store i64 %cp3, ptr %pos")
    emitIR("  %hci3 = add i32 %hci2, 1")
    emitIR("  store i32 %hci3, ptr %ci")
    emitIR("  br label %hdr.loop")
    emitIR("hdr.done:")
    // Add newline after headers
    emitIR("  %hp = load i64, ptr %pos")
    emitIR("  %hpn = add i64 %hp, 2")
    emitIR("  %hdbuf = call ptr @ss_rt_ensure_cap(ptr %bufp, ptr %cap, i64 %hpn)")
    emitIR("  %hd = getelementptr i8, ptr %hdbuf, i64 %hp")
    emitIR("  store i8 10, ptr %hd")
    emitIR("  %hp1 = add i64 %hp, 1")
    emitIR("  store i64 %hp1, ptr %pos")
    // Row loop
    emitIR("  br label %row.loop")
    emitIR("row.loop:")
    emitIR("  %src = call i32 @sqlite3_step(ptr %stmt)")
    emitIR("  %isrow = icmp eq i32 %src, 100")
    emitIR("  br i1 %isrow, label %row.body, label %row.done")
    emitIR("row.body:")
    emitIR("  store i32 0, ptr %ci")
    emitIR("  br label %col.loop")
    emitIR("col.loop:")
    emitIR("  %cci = load i32, ptr %ci")
    emitIR("  %ccond = icmp slt i32 %cci, %ncols")
    emitIR("  br i1 %ccond, label %col.body, label %col.done")
    emitIR("col.body:")
    emitIR("  %cci2 = load i32, ptr %ci")
    // Tab separator
    emitIR("  %cntab = icmp sgt i32 %cci2, 0")
    emitIR("  br i1 %cntab, label %col.tab, label %col.val")
    emitIR("col.tab:")
    emitIR("  %vtp = load i64, ptr %pos")
    emitIR("  %vtn = add i64 %vtp, 2")
    emitIR("  %vtbuf = call ptr @ss_rt_ensure_cap(ptr %bufp, ptr %cap, i64 %vtn)")
    emitIR("  %vtd = getelementptr i8, ptr %vtbuf, i64 %vtp")
    emitIR("  store i8 9, ptr %vtd")
    emitIR("  %vtp1 = add i64 %vtp, 1")
    emitIR("  store i64 %vtp1, ptr %pos")
    emitIR("  br label %col.val")
    emitIR("col.val:")
    emitIR("  %ctxt = call ptr @sqlite3_column_text(ptr %stmt, i32 %cci2)")
    emitIR("  %isnull = icmp eq ptr %ctxt, null")
    emitIR("  br i1 %isnull, label %col.next, label %col.copy")
    emitIR("col.copy:")
    emitIR("  %vtlen = call i64 @strlen(ptr %ctxt)")
    emitIR("  %vp2 = load i64, ptr %pos")
    emitIR("  %vn = add i64 %vp2, %vtlen")
    emitIR("  %vn2 = add i64 %vn, 1")
    emitIR("  %vbuf = call ptr @ss_rt_ensure_cap(ptr %bufp, ptr %cap, i64 %vn2)")
    emitIR("  %vdst = getelementptr i8, ptr %vbuf, i64 %vp2")
    emitIR("  %_3 = call ptr @memcpy(ptr %vdst, ptr %ctxt, i64 %vtlen)")
    emitIR("  %vp3 = add i64 %vp2, %vtlen")
    emitIR("  store i64 %vp3, ptr %pos")
    emitIR("  br label %col.next")
    emitIR("col.next:")
    emitIR("  %cci3 = add i32 %cci2, 1")
    emitIR("  store i32 %cci3, ptr %ci")
    emitIR("  br label %col.loop")
    emitIR("col.done:")
    // Newline after row
    emitIR("  %rp = load i64, ptr %pos")
    emitIR("  %rn = add i64 %rp, 2")
    emitIR("  %rbuf = call ptr @ss_rt_ensure_cap(ptr %bufp, ptr %cap, i64 %rn)")
    emitIR("  %rd = getelementptr i8, ptr %rbuf, i64 %rp")
    emitIR("  store i8 10, ptr %rd")
    emitIR("  %rp1 = add i64 %rp, 1")
    emitIR("  store i64 %rp1, ptr %pos")
    emitIR("  br label %row.loop")
    emitIR("row.done:")
    emitIR("  %_4 = call i32 @sqlite3_finalize(ptr %stmt)")
    emitIR("  %fp = load i64, ptr %pos")
    emitIR("  %fn = add i64 %fp, 1")
    emitIR("  %fbuf = call ptr @ss_rt_ensure_cap(ptr %bufp, ptr %cap, i64 %fn)")
    emitIR("  %ft = getelementptr i8, ptr %fbuf, i64 %fp")
    emitIR("  store i8 0, ptr %ft")
    emitIR("  ret ptr %fbuf")
    emitIR("}")
    emitIR("")
}
