// gen_rt_array.ss — Runtime array/list operations

// ── Array operations ──────────────────────────────────────────

function emitRuntimeArrayOps() {
    // Layout: arr[0] = length (i64), arr[1..n] = elements (i64 each)

    // ss_newArray (scalar elements, tag=1)
    emitIR("define ptr @ss_newArray(i32 %size) {")
    irSext("size64", "i32", "%size", "i64")
    irAdd("slots", "i64", "%size64", "1")
    irMul("asize", "i64", "%slots", "8")
    irCall("arr", "ptr", "ss_rc_calloc", "i64 %asize, i32 1")
    irStore("i64", "%size64", "%arr")
    irRet("ptr", "%arr")
    emitIR("}")
    emitIR("")

    // ss_newArrayPtr (ptr elements, tag=5 — destructor will release elements)
    emitIR("define ptr @ss_newArrayPtr(i32 %size) {")
    irSext("size64", "i32", "%size", "i64")
    irAdd("slots", "i64", "%size64", "1")
    irMul("asize", "i64", "%slots", "8")
    irCall("arr", "ptr", "ss_rc_calloc", "i64 %asize, i32 5")
    irStore("i64", "%size64", "%arr")
    irRet("ptr", "%arr")
    emitIR("}")
    emitIR("")

    // ss_arrayLen
    emitIR("define i32 @ss_arrayLen(ptr %arr) {")
    irLoad("len", "i64", "%arr")
    irTrunc("result", "i64", "%len", "i32")
    irRet("i32", "%result")
    emitIR("}")
    emitIR("")

    // ss_arrayGet
    emitIR("define i64 @ss_arrayGet(ptr %arr, i32 %idx) {")
    irSext("idx64", "i32", "%idx", "i64")
    irAdd("slot", "i64", "%idx64", "1")
    irGEP("ptr", "i64", "%arr", "%slot")
    irLoad("val", "i64", "%ptr")
    irRet("i64", "%val")
    emitIR("}")
    emitIR("")

    // ss_arraySet
    emitIR("define void @ss_arraySet(ptr %arr, i32 %idx, i64 %val) {")
    irSext("idx64", "i32", "%idx", "i64")
    irAdd("slot", "i64", "%idx64", "1")
    irGEP("ptr", "i64", "%arr", "%slot")
    irStore("i64", "%val", "%ptr")
    irRetVoid()
    emitIR("}")
    emitIR("")

    // ss_arrayPush
    emitIR("define ptr @ss_arrayPush(ptr %arr, i64 %val) {")
    irLoad("len", "i64", "%arr")
    irAdd("newslots", "i64", "%len", "2")
    irMul("bytes", "i64", "%newslots", "8")
    irCall("newarr", "ptr", "ss_rc_realloc", "ptr %arr, i64 %bytes")
    irAdd("newlen", "i64", "%len", "1")
    irStore("i64", "%newlen", "%newarr")
    irGEP("dst", "i64", "%newarr", "%newlen")
    irStore("i64", "%val", "%dst")
    irRet("ptr", "%newarr")
    emitIR("}")
    emitIR("")

    // ss_arraySort (qsort with comparator)
    emitIR("define internal i32 @ss_cmp_asc(ptr %a, ptr %b) {")
    irLoad("va", "i64", "%a")
    irLoad("vb", "i64", "%b")
    irICmp("gt", "sgt", "i64", "%va", "%vb")
    irICmp("lt", "slt", "i64", "%va", "%vb")
    irZext("gti", "i1", "%gt", "i32")
    irZext("lti", "i1", "%lt", "i32")
    irSub("result", "i32", "%gti", "%lti")
    irRet("i32", "%result")
    emitIR("}")
    emitIR("")
    emitIR("define void @ss_arraySort(ptr %arr) {")
    irLabel("entry")
    irLoad("len", "i64", "%arr")
    irICmp("need_sort", "sgt", "i64", "%len", "1")
    irBrCond("need_sort", "sort", "done")
    irLabel("sort")
    irGEP("data", "i64", "%arr", "1")
    irCallVoid("qsort", "ptr %data, i64 %len, i64 8, ptr @ss_cmp_asc")
    irBr("done")
    irLabel("done")
    irRetVoid()
    emitIR("}")
    emitIR("")

    // ss_arrayReverse
    emitIR("define void @ss_arrayReverse(ptr %arr) {")
    irLabel("entry")
    irLoad("len", "i64", "%arr")
    irSDiv("half", "i64", "%len", "2")
    irAlloca("i", "i64", 8)
    irStore("i64", "0", "%i")
    irBr("loop")
    irLabel("loop")
    irLoad("ci", "i64", "%i")
    irICmp("cond", "slt", "i64", "%ci", "%half")
    irBrCond("cond", "body", "done")
    irLabel("body")
    irAdd("li", "i64", "%ci", "1")
    irSub("ri64", "i64", "%len", "%ci")
    irGEP("lp", "i64", "%arr", "%li")
    irGEP("rp", "i64", "%arr", "%ri64")
    irLoad("lv", "i64", "%lp")
    irLoad("rv", "i64", "%rp")
    irStore("i64", "%rv", "%lp")
    irStore("i64", "%lv", "%rp")
    irAdd("ni", "i64", "%ci", "1")
    irStore("i64", "%ni", "%i")
    irBr("loop")
    irLabel("done")
    irRetVoid()
    emitIR("}")
    emitIR("")

    // ss_arrayFirst
    emitIR("define i64 @ss_arrayFirst(ptr %arr) {")
    irLabel("entry")
    irLoad("len", "i64", "%arr")
    irICmp("has", "sgt", "i64", "%len", "0")
    irBrCond("has", "has_elem", "empty")
    irLabel("has_elem")
    irGEP("ptr", "i64", "%arr", "1")
    irLoad("val", "i64", "%ptr")
    irRet("i64", "%val")
    irLabel("empty")
    irRet("i64", "0")
    emitIR("}")
    emitIR("")

    // ss_arrayLast
    emitIR("define i64 @ss_arrayLast(ptr %arr) {")
    irLabel("entry")
    irLoad("len", "i64", "%arr")
    irICmp("has", "sgt", "i64", "%len", "0")
    irBrCond("has", "has_elem", "empty")
    irLabel("has_elem")
    irGEP("ptr", "i64", "%arr", "%len")
    irLoad("val", "i64", "%ptr")
    irRet("i64", "%val")
    irLabel("empty")
    irRet("i64", "0")
    emitIR("}")
    emitIR("")

    // ss_arrayIndexOf
    emitIR("define i32 @ss_arrayIndexOf(ptr %arr, i64 %needle) {")
    irLabel("entry")
    irLoad("len", "i64", "%arr")
    irAlloca("i", "i64", 8)
    irStore("i64", "0", "%i")
    irBr("loop")
    irLabel("loop")
    irLoad("ci", "i64", "%i")
    irICmp("cond", "slt", "i64", "%ci", "%len")
    irBrCond("cond", "body", "notfound")
    irLabel("body")
    irAdd("si", "i64", "%ci", "1")
    irGEP("ep", "i64", "%arr", "%si")
    irLoad("ev", "i64", "%ep")
    irICmp("eq", "eq", "i64", "%ev", "%needle")
    irBrCond("eq", "found", "inc")
    irLabel("inc")
    irAdd("ni", "i64", "%ci", "1")
    irStore("i64", "%ni", "%i")
    irBr("loop")
    irLabel("found")
    irTrunc("ri", "i64", "%ci", "i32")
    irRet("i32", "%ri")
    irLabel("notfound")
    irRet("i32", "-1")
    emitIR("}")
    emitIR("")

    // ss_arraySlice — inherits source tag; retains ptr elements (tag=5)
    emitIR("define ptr @ss_arraySlice(ptr %arr, i32 %start, i32 %end_idx) {")
    irLabel("entry")
    irAlloca("ria", "i64", 8)
    irLoad("len", "i64", "%arr")
    irSext("s", "i32", "%start", "i64")
    irSext("e", "i32", "%end_idx", "i64")
    irICmp("e2", "sgt", "i64", "%e", "%len")
    irSelect("end", "e2", "i64", "%len", "%e")
    irSub("nlen", "i64", "%end", "%s")
    irICmp("nlen2", "slt", "i64", "%nlen", "0")
    irSelect("nlen3", "nlen2", "i64", "0", "%nlen")
    irAdd("slots", "i64", "%nlen3", "1")
    irMul("sasize", "i64", "%slots", "8")
    irGEP("src_tagp", "i8", "%arr", "-8")
    irLoad("src_tag", "i32", "%src_tagp")
    irCall("newarr", "ptr", "ss_rc_calloc", "i64 %sasize, i32 %src_tag")
    irStore("i64", "%nlen3", "%newarr")
    irAdd("src", "i64", "%s", "1")
    irGEP("srcp", "i64", "%arr", "%src")
    irGEP("dstp", "i64", "%newarr", "1")
    irMul("bytes", "i64", "%nlen3", "8")
    irCall("_1", "ptr", "memcpy", "ptr %dstp, ptr %srcp, i64 %bytes")
    emitIR("  ; If ptr array (tag=5), retain all copied elements")
    irICmp("is_ptr", "eq", "i32", "%src_tag", "5")
    irBrCond("is_ptr", "retain.init", "done")
    irLabel("retain.init")
    irStore("i64", "0", "%ria")
    irBr("retain.loop")
    irLabel("retain.loop")
    irLoad("ri", "i64", "%ria")
    irICmp("rdone", "eq", "i64", "%ri", "%nlen3")
    irBrCond("rdone", "done", "retain.body")
    irLabel("retain.body")
    irAdd("rslot", "i64", "%ri", "1")
    irGEP("rep", "i64", "%newarr", "%rslot")
    irLoad("rev", "i64", "%rep")
    irIntToPtr("rptr", "i64", "%rev")
    irCallVoid("ss_rc_retain", "ptr %rptr")
    irAdd("rni", "i64", "%ri", "1")
    irStore("i64", "%rni", "%ria")
    irBr("retain.loop")
    irLabel("done")
    irRet("ptr", "%newarr")
    emitIR("}")
    emitIR("")

    // ss_arrayConcat — inherits source tag; retains ptr elements (tag=5)
    emitIR("define ptr @ss_arrayConcat(ptr %a, ptr %b) {")
    irLabel("entry")
    irAlloca("ria", "i64", 8)
    irLoad("alen", "i64", "%a")
    irLoad("blen", "i64", "%b")
    irAdd("total", "i64", "%alen", "%blen")
    irAdd("slots", "i64", "%total", "1")
    irMul("casize", "i64", "%slots", "8")
    irGEP("src_tagp", "i8", "%a", "-8")
    irLoad("src_tag", "i32", "%src_tagp")
    irCall("newarr", "ptr", "ss_rc_calloc", "i64 %casize, i32 %src_tag")
    irStore("i64", "%total", "%newarr")
    irGEP("dst1", "i64", "%newarr", "1")
    irGEP("src1", "i64", "%a", "1")
    irMul("abytes", "i64", "%alen", "8")
    irCall("_1", "ptr", "memcpy", "ptr %dst1, ptr %src1, i64 %abytes")
    irGEP("dst2", "i64", "%dst1", "%alen")
    irGEP("src2", "i64", "%b", "1")
    irMul("bbytes", "i64", "%blen", "8")
    irCall("_2", "ptr", "memcpy", "ptr %dst2, ptr %src2, i64 %bbytes")
    emitIR("  ; If ptr array (tag=5), retain all elements")
    irICmp("is_ptr", "eq", "i32", "%src_tag", "5")
    irBrCond("is_ptr", "retain.init", "done")
    irLabel("retain.init")
    irStore("i64", "0", "%ria")
    irBr("retain.loop")
    irLabel("retain.loop")
    irLoad("ri", "i64", "%ria")
    irICmp("rdone", "eq", "i64", "%ri", "%total")
    irBrCond("rdone", "done", "retain.body")
    irLabel("retain.body")
    irAdd("rslot", "i64", "%ri", "1")
    irGEP("rep", "i64", "%newarr", "%rslot")
    irLoad("rev", "i64", "%rep")
    irIntToPtr("rptr", "i64", "%rev")
    irCallVoid("ss_rc_retain", "ptr %rptr")
    irAdd("rni", "i64", "%ri", "1")
    irStore("i64", "%rni", "%ria")
    irBr("retain.loop")
    irLabel("done")
    irRet("ptr", "%newarr")
    emitIR("}")
    emitIR("")

    // ss_arrayToString — "[1, 2, 3]" style output (dynamic buffer)
    emitIR("define ptr @ss_arrayToString(ptr %arr) {")
    irLabel("entry")
    irLoad("len", "i64", "%arr")
    irAlloca("bufp", "ptr", 8)
    irAlloca("cap", "i64", 8)
    irCall("r0", "ptr", "ss_rc_alloc", "i64 256, i32 0")
    irStore("ptr", "%r0", "%bufp")
    irStore("i64", "256", "%cap")
    irStore("i8", "91", "%r0")
    irAlloca("pos", "i64", 8)
    irStore("i64", "1", "%pos")
    irAlloca("i", "i64", 8)
    irStore("i64", "0", "%i")
    irBr("loop")
    irLabel("loop")
    irLoad("ci", "i64", "%i")
    irICmp("cond", "slt", "i64", "%ci", "%len")
    irBrCond("cond", "body", "end")
    irLabel("body")
    // ensure capacity for comma(2) + snprintf(256) + safety
    irLoad("bpos", "i64", "%pos")
    irAdd("bneed", "i64", "%bpos", "260")
    irCall("bbuf", "ptr", "ss_rt_ensure_cap", "ptr %bufp, ptr %cap, i64 %bneed")
    irICmp("ci0", "sgt", "i64", "%ci", "0")
    irBrCond("ci0", "comma", "val")
    irLabel("comma")
    irLoad("cp2", "i64", "%pos")
    irGEP("dp", "i8", "%bbuf", "%cp2")
    irStore("i8", "44", "%dp")
    irAdd("cp3", "i64", "%cp2", "1")
    irGEP("dp2", "i8", "%bbuf", "%cp3")
    irStore("i8", "32", "%dp2")
    irAdd("cp4", "i64", "%cp3", "1")
    irStore("i64", "%cp4", "%pos")
    irBr("val")
    irLabel("val")
    irAdd("si", "i64", "%ci", "1")
    irGEP("ep", "i64", "%arr", "%si")
    irLoad("ev", "i64", "%ep")
    irLoad("vp", "i64", "%pos")
    irGEP("dest", "i8", "%bbuf", "%vp")
    irCall("written", "i32 (ptr, i64, ptr, ...)", "snprintf", "ptr %dest, i64 256, ptr @.rt.fmt.lld, i64 %ev")
    irSext("w64", "i32", "%written", "i64")
    irAdd("np", "i64", "%vp", "%w64")
    irStore("i64", "%np", "%pos")
    irAdd("ni", "i64", "%ci", "1")
    irStore("i64", "%ni", "%i")
    irBr("loop")
    irLabel("end")
    irLoad("fp", "i64", "%pos")
    irAdd("fn", "i64", "%fp", "2")
    irCall("fbuf", "ptr", "ss_rt_ensure_cap", "ptr %bufp, ptr %cap, i64 %fn")
    irGEP("ep2", "i8", "%fbuf", "%fp")
    irStore("i8", "93", "%ep2")
    irAdd("fp2", "i64", "%fp", "1")
    irGEP("ep3", "i8", "%fbuf", "%fp2")
    irStore("i8", "0", "%ep3")
    irRet("ptr", "%fbuf")
    emitIR("}")
    emitIR("")
}
