// gen_runtime.ss — Runtime core: dispatcher, libc declarations, globals, helpers, RC

import { emitRuntimeStringOps, emitRuntimeConversions } from "./gen_rt_string"
import { emitRuntimeArrayOps } from "./gen_rt_array"
import { emitRuntimeIO, emitRuntimeProcess, emitRuntimeMath } from "./gen_rt_io"
import { emitRuntimeMap } from "./gen_rt_map"
import { emitRuntimeFS, emitRuntimeNet, emitRuntimeExceptions, emitRuntimeSQLite } from "./gen_rt_system"

function emitRuntimeDefs() {
    emitLibcDecls()
    emitRuntimeGlobals()
    emitRuntimeHelpers()
    emitRuntimeRC()
    emitRuntimeStringOps()
    emitRuntimeIO()
    emitRuntimeArrayOps()
    emitRuntimeConversions()
    emitRuntimeProcess()
    emitRuntimeMath()
    emitRuntimeFS()
    emitRuntimeNet()
    emitRuntimeMap()
    emitRuntimeExceptions()
    emitRuntimeSQLite()
}

// ── libc declarations ─────────────────────────────────────────

function emitLibcDecls() {
    // I/O
    emitIR("declare i32 @puts(ptr)")
    emitIR("declare i32 @fputs(ptr, ptr)")
    emitIR("declare i32 @fflush(ptr)")
    emitIR("declare ptr @fopen(ptr, ptr)")
    emitIR("declare i32 @fclose(ptr)")
    emitIR("declare i32 @fseek(ptr, i64, i32)")
    emitIR("declare i64 @ftell(ptr)")
    emitIR("declare i64 @fread(ptr, i64, i64, ptr)")
    emitIR("declare ptr @fgets(ptr, i32, ptr)")
    // String
    emitIR("declare i64 @strlen(ptr)")
    emitIR("declare ptr @strdup(ptr)")
    emitIR("declare ptr @strstr(ptr, ptr)")
    emitIR("declare i32 @strcmp(ptr, ptr)")
    emitIR("declare i32 @strncmp(ptr, ptr, i64)")
    // Memory (libc)
    emitIR("declare ptr @malloc(i64)")
    emitIR("declare ptr @calloc(i64, i64)")
    emitIR("declare ptr @realloc(ptr, i64)")
    emitIR("declare void @free(ptr)")
    emitIR("declare ptr @memcpy(ptr, ptr, i64)")
    emitIR("declare ptr @memset(ptr, i32, i64)")
    // Memory (mimalloc — class instance allocation)
    emitIR("declare ptr @mi_calloc(i64, i64)")
    emitIR("declare void @mi_free(ptr)")
    // Conversion
    emitIR("declare i32 @atoi(ptr)")
    emitIR("declare double @atof(ptr)")
    emitIR("declare i32 @snprintf(ptr, i64, ptr, ...)")
    // Math
    emitIR("declare double @sqrt(double)")
    emitIR("declare double @fabs(double)")
    emitIR("declare double @floor(double)")
    emitIR("declare double @ceil(double)")
    emitIR("declare double @round(double)")
    emitIR("declare double @pow(double, double)")
    emitIR("declare double @log(double)")
    emitIR("declare double @sin(double)")
    emitIR("declare double @cos(double)")
    emitIR("declare double @tan(double)")
    emitIR("declare double @asin(double)")
    emitIR("declare double @acos(double)")
    emitIR("declare double @atan(double)")
    emitIR("declare double @atan2(double, double)")
    emitIR("declare double @exp(double)")
    emitIR("declare double @log10(double)")
    emitIR("declare double @log2(double)")
    emitIR("declare double @trunc(double)")
    emitIR("declare double @hypot(double, double)")
    emitIR("declare double @fmod(double, double)")
    emitIR("declare i32 @rand()")
    emitIR("declare void @srand(i32)")
    // Exception handling (setjmp/longjmp)
    emitIR("declare i32 @setjmp(ptr)")
    emitIR("declare void @longjmp(ptr, i32)")
    // Process
    emitIR("declare void @exit(i32)")
    emitIR("declare i32 @system(ptr)")
    emitIR("declare ptr @getenv(ptr)")
    emitIR("declare i32 @atexit(ptr)")
    // Time
    emitIR("declare i64 @time(ptr)")
    emitIR("declare i32 @clock_gettime(i32, ptr)")
    // Filesystem
    emitIR("declare i32 @mkdir(ptr, i32)")
    emitIR("declare i32 @stat(ptr, ptr)")
    emitIR("declare ptr @opendir(ptr)")
    emitIR("declare ptr @readdir(ptr)")
    emitIR("declare i32 @closedir(ptr)")
    emitIR("declare i32 @remove(ptr)")
    emitIR("declare i32 @rename(ptr, ptr)")
    // Network
    emitIR("declare i32 @socket(i32, i32, i32)")
    emitIR("declare i32 @bind(i32, ptr, i32)")
    emitIR("declare i32 @listen(i32, i32)")
    emitIR("declare i32 @accept(i32, ptr, ptr)")
    emitIR("declare i32 @setsockopt(i32, i32, i32, ptr, i32)")
    emitIR("declare i64 @read(i32, ptr, i64)")
    emitIR("declare i64 @write(i32, ptr, i64)")
    emitIR("declare i32 @close(i32)")
    emitIR("declare i16 @htons(i16)")
    // Sort
    emitIR("declare void @qsort(ptr, i64, i64, ptr)")
    // SQLite3 C API
    emitIR("declare i32 @sqlite3_open(ptr, ptr)")
    emitIR("declare i32 @sqlite3_close(ptr)")
    emitIR("declare i32 @sqlite3_exec(ptr, ptr, ptr, ptr, ptr)")
    emitIR("declare i32 @sqlite3_prepare_v2(ptr, ptr, i32, ptr, ptr)")
    emitIR("declare i32 @sqlite3_step(ptr)")
    emitIR("declare i32 @sqlite3_finalize(ptr)")
    emitIR("declare i32 @sqlite3_column_count(ptr)")
    emitIR("declare ptr @sqlite3_column_name(ptr, i32)")
    emitIR("declare ptr @sqlite3_column_text(ptr, i32)")
    emitIR("declare i32 @sqlite3_column_int(ptr, i32)")
    emitIR("declare i32 @sqlite3_changes(ptr)")
    emitIR("")
}

// ── Globals ───────────────────────────────────────────────────

function emitRuntimeGlobals() {
    emitIR("@stdin = external global ptr")
    emitIR("@stdout = external global ptr")
    emitIR("@ss_argc = internal global i32 0, align 4")
    emitIR("@ss_argv = internal global ptr null, align 8")
    // Exception handling: jmp_buf stack (200 bytes per level, max 16 deep)
    emitIR("@ss_jmpbuf = internal global [3200 x i8] zeroinitializer, align 16")
    emitIR("@ss_exc_depth = internal global i32 0, align 4")
    emitIR("@ss_exc_msg = internal global ptr null, align 8")
    emitIR(`@.rt.str.uncaught = private constant [21 x i8] c"uncaught exception: \\00"`)
    // Format strings (use @.rt. prefix to avoid collision with user string consts)
    emitIR(`@.rt.fmt.d = private constant [3 x i8] c"%d\\00"`)
    emitIR(`@.rt.fmt.g = private constant [3 x i8] c"%g\\00"`)
    emitIR(`@.rt.fmt.lld = private constant [5 x i8] c"%lld\\00"`)
    emitIR(`@.rt.str.true = private constant [5 x i8] c"true\\00"`)
    emitIR(`@.rt.str.false = private constant [6 x i8] c"false\\00"`)
    emitIR(`@.rt.str.empty = private constant [1 x i8] c"\\00"`)
    emitIR(`@.rt.str.rb = private constant [3 x i8] c"rb\\00"`)
    emitIR(`@.rt.str.w = private constant [2 x i8] c"w\\00"`)
    emitIR(`@.rt.str.a = private constant [2 x i8] c"a\\00"`)
    emitIR(`@.rt.str.nl = private constant [2 x i8] c"\\0A\\00"`)
    // Class destructor table: tag >= 10 indexes into this (tag-10)
    emitIR("@ss_class_dtor = internal global [100 x ptr] zeroinitializer")
    // TypeInfo type: { drop_fn, deep_clone_fn, shallow_clone_fn, size, name, class_id }
    emitIR("%TypeInfo = type { ptr, ptr, ptr, i64, ptr, i32 }")
    // ObjHeader type: { rc:i32, type_info:ptr } — first two fields of every class instance
    emitIR("%ObjHeader = type { i32, ptr }")
    emitIR("")
}

// ── Internal helpers ──────────────────────────────────────────

function emitRuntimeHelpers() {
    // ss_rt_ensure_cap(bufp, capp, needed) — grow buffer if needed
    // bufp: ptr to buffer pointer, capp: ptr to capacity i64, needed: required bytes
    // Returns the (possibly reallocated) buffer pointer
    emitIR("define ptr @ss_rt_ensure_cap(ptr %bufp, ptr %capp, i64 %needed) {")
    irLabel("entry")
    irLoad("cap", "i64", "%capp")
    irICmp("fits", "slt", "i64", "%needed", "%cap")
    irBrCond("fits", "ok", "grow")
    irLabel("grow")
    irMul("dbl", "i64", "%cap", "2")
    irICmp("enough", "sge", "i64", "%dbl", "%needed")
    irAdd("min", "i64", "%needed", "256")
    irSelect("newcap", "enough", "i64", "%dbl", "%min")
    irLoad("oldbuf", "ptr", "%bufp")
    irCall("newbuf", "ptr", "ss_rc_realloc", "ptr %oldbuf, i64 %newcap")
    irStore("ptr", "%newbuf", "%bufp")
    irStore("i64", "%newcap", "%capp")
    irBr("ok")
    irLabel("ok")
    irLoad("buf", "ptr", "%bufp")
    irRet("ptr", "%buf")
    emitIR("}")
    emitIR("")
}

// ── Reference counting ────────────────────────────────────────
// Object layout: [rc:i64][tag:i32][pad:i32] | [user data...]
//                ^raw ptr (malloc'd)          ^user ptr (returned, +16)
// Tags: 0=string, 1=array(scalar), 2=map, 3=class(no dtor), 5=array(ptr), >=10=class(with dtor)

function emitRuntimeRC() {
    // ss_rc_alloc(size, tag) → user ptr with rc=1
    emitIR("define ptr @ss_rc_alloc(i64 %size, i32 %tag) {")
    irLabel("entry")
    irAdd("total", "i64", "%size", "16")
    irCall("raw", "ptr", "malloc", "i64 %total")
    irStore("i64", "1", "%raw")
    irGEP("tagp", "i8", "%raw", "8")
    irStore("i32", "%tag", "%tagp")
    irGEP("padp", "i8", "%raw", "12")
    irStore("i32", "1397969747", "%padp")
    irGEP("user", "i8", "%raw", "16")
    irRet("ptr", "%user")
    emitIR("}")
    emitIR("")

    // ss_rc_calloc(size, tag) → zeroed user data with rc=1
    emitIR("define ptr @ss_rc_calloc(i64 %size, i32 %tag) {")
    irLabel("entry")
    irCall("buf", "ptr", "ss_rc_alloc", "i64 %size, i32 %tag")
    irCall("_1", "ptr", "memset", "ptr %buf, i32 0, i64 %size")
    irRet("ptr", "%buf")
    emitIR("}")
    emitIR("")

    // ss_rc_realloc(user_ptr, new_data_size) → new user ptr (preserves header)
    emitIR("define ptr @ss_rc_realloc(ptr %p, i64 %size) {")
    irLabel("entry")
    irGEP("raw", "i8", "%p", "-16")
    irAdd("total", "i64", "%size", "16")
    irCall("newraw", "ptr", "realloc", "ptr %raw, i64 %total")
    irGEP("user", "i8", "%newraw", "16")
    irRet("ptr", "%user")
    emitIR("}")
    emitIR("")

    // ss_rc_strdup(s) → RC-managed copy of string
    emitIR("define ptr @ss_rc_strdup(ptr %s) {")
    irLabel("entry")
    irCall("len", "i64", "strlen", "ptr %s")
    irAdd("size", "i64", "%len", "1")
    irCall("buf", "ptr", "ss_rc_alloc", "i64 %size, i32 0")
    irCall("_1", "ptr", "memcpy", "ptr %buf, ptr %s, i64 %size")
    irRet("ptr", "%buf")
    emitIR("}")
    emitIR("")

    // ss_rc_retain(p) — increment rc; skip null, non-RC, and immortal (rc<0)
    emitIR("define void @ss_rc_retain(ptr %p) {")
    irLabel("entry")
    irICmp("isnull", "eq", "ptr", "%p", "null")
    irBrCond("isnull", "done", "guard")
    irLabel("guard")
    irGEP("magp", "i8", "%p", "-4")
    irLoad("mag", "i32", "%magp")
    irICmp("isrc", "eq", "i32", "%mag", "1397969747")
    irBrCond("isrc", "check", "done")
    irLabel("check")
    irGEP("raw", "i8", "%p", "-16")
    irLoad("rc", "i64", "%raw")
    irICmp("immortal", "slt", "i64", "%rc", "0")
    irBrCond("immortal", "done", "inc")
    irLabel("inc")
    irAdd("rc1", "i64", "%rc", "1")
    irStore("i64", "%rc1", "%raw")
    irBr("done")
    irLabel("done")
    irRetVoid()
    emitIR("}")
    emitIR("")

    // ss_rc_release(p) — decrement rc; free when 0; skip null, non-RC, and immortal
    // On rc=0: dispatch to type-specific destructor based on tag before freeing
    emitIR("define void @ss_rc_release(ptr %p) {")
    irLabel("entry")
    irICmp("isnull", "eq", "ptr", "%p", "null")
    irBrCond("isnull", "done", "guard")
    irLabel("guard")
    irGEP("magp", "i8", "%p", "-4")
    irLoad("mag", "i32", "%magp")
    irICmp("isrc", "eq", "i32", "%mag", "1397969747")
    irBrCond("isrc", "check", "done")
    irLabel("check")
    irGEP("raw", "i8", "%p", "-16")
    irLoad("rc", "i64", "%raw")
    irICmp("immortal", "slt", "i64", "%rc", "0")
    irBrCond("immortal", "done", "dec")
    irLabel("dec")
    irSub("rc1", "i64", "%rc", "1")
    irICmp("iszero", "eq", "i64", "%rc1", "0")
    irBrCond("iszero", "destroy", "store")
    irLabel("store")
    irStore("i64", "%rc1", "%raw")
    irBr("done")
    irLabel("destroy")
    emitIR("  ; Dispatch destructor by tag")
    irGEP("tagp", "i8", "%p", "-8")
    irLoad("tag", "i32", "%tagp")
    irICmp("is_map", "eq", "i32", "%tag", "2")
    irBrCond("is_map", "dtor_map", "check_arrptr")
    irLabel("check_arrptr")
    irICmp("is_arrptr", "eq", "i32", "%tag", "5")
    irBrCond("is_arrptr", "dtor_arrptr", "check_class")
    irLabel("check_class")
    irICmp("is_class_dtor", "sge", "i32", "%tag", "10")
    irBrCond("is_class_dtor", "dtor_class", "do_free")
    irLabel("dtor_map")
    irCallVoid("ss_rc_destroy_map", "ptr %p")
    irBr("do_free")
    irLabel("dtor_arrptr")
    irCallVoid("ss_rc_destroy_array_ptrs", "ptr %p")
    irBr("do_free")
    irLabel("dtor_class")
    irSub("didx", "i32", "%tag", "10")
    irSext("didx64", "i32", "%didx", "i64")
    emitIR("  %dgep = getelementptr [100 x ptr], ptr @ss_class_dtor, i64 0, i64 %didx64")
    irLoad("dfn", "ptr", "%dgep")
    irICmp("has_dtor", "ne", "ptr", "%dfn", "null")
    irBrCond("has_dtor", "call_dtor", "do_free")
    irLabel("call_dtor")
    emitIR("  call void %dfn(ptr %p)")
    irBr("do_free")
    irLabel("do_free")
    irCallVoid("free", "ptr %raw")
    irBr("done")
    irLabel("done")
    irRetVoid()
    emitIR("}")
    emitIR("")

    // ss_rc_release_no_children(p) — decrement rc; if zero, free without destructor/element cleanup
    // Used for non-owning container fields: the container is freed but elements are not released
    emitIR("define void @ss_rc_release_no_children(ptr %p) {")
    irLabel("entry")
    irICmp("isnull", "eq", "ptr", "%p", "null")
    irBrCond("isnull", "done", "guard")
    irLabel("guard")
    irGEP("magp", "i8", "%p", "-4")
    irLoad("mag", "i32", "%magp")
    irICmp("isrc", "eq", "i32", "%mag", "1397969747")
    irBrCond("isrc", "check", "done")
    irLabel("check")
    irGEP("raw", "i8", "%p", "-16")
    irLoad("rc", "i64", "%raw")
    irICmp("immortal", "slt", "i64", "%rc", "0")
    irBrCond("immortal", "done", "dec")
    irLabel("dec")
    irSub("rc1", "i64", "%rc", "1")
    irICmp("iszero", "eq", "i64", "%rc1", "0")
    irBrCond("iszero", "do_free", "store")
    irLabel("store")
    irStore("i64", "%rc1", "%raw")
    irBr("done")
    irLabel("do_free")
    irCallVoid("free", "ptr %raw")
    irBr("done")
    irLabel("done")
    irRetVoid()
    emitIR("}")
    emitIR("")

    // ss_rc_destroy_map(map) — release all keys, optionally release ptr values, free entries
    // val_type flag at map offset 516: 0=scalar values, 1=ptr values (need release)
    emitIR("define void @ss_rc_destroy_map(ptr %map) {")
    irLabel("entry")
    irAlloca("ia", "i64", 8)
    irAlloca("ea", "ptr", 8)
    irAlloca("na", "ptr", 8)
    irGEP("vtpp", "i8", "%map", "516")
    irLoad("vtp", "i32", "%vtpp")
    irICmp("val_is_ptr", "eq", "i32", "%vtp", "1")
    irStore("i64", "0", "%ia")
    irBr("bucket.loop")
    irLabel("bucket.loop")
    irLoad("i", "i64", "%ia")
    irICmp("done", "eq", "i64", "%i", "64")
    irBrCond("done", "ret", "bucket.body")
    irLabel("bucket.body")
    irGEP("bp", "ptr", "%map", "%i")
    irLoad("e0", "ptr", "%bp")
    irStore("ptr", "%e0", "%ea")
    irBr("entry.loop")
    irLabel("entry.loop")
    irLoad("e", "ptr", "%ea")
    irICmp("enull", "eq", "ptr", "%e", "null")
    irBrCond("enull", "bucket.next", "entry.body")
    irLabel("entry.body")
    emitIR("  ; Save next pointer before freeing")
    irGEP("enp", "i8", "%e", "16")
    irLoad("next", "ptr", "%enp")
    irStore("ptr", "%next", "%na")
    emitIR("  ; Release key (RC string)")
    irLoad("key", "ptr", "%e")
    irCallVoid("ss_rc_release", "ptr %key")
    emitIR("  ; Release value if map has ptr values")
    irBrCond("val_is_ptr", "rel.val", "free.entry")
    irLabel("rel.val")
    irGEP("vp2", "i8", "%e", "8")
    irLoad("vi", "i64", "%vp2")
    irIntToPtr("vptr", "i64", "%vi")
    irCallVoid("ss_rc_release", "ptr %vptr")
    irBr("free.entry")
    irLabel("free.entry")
    emitIR("  ; Free entry node (plain malloc)")
    irCallVoid("free", "ptr %e")
    emitIR("  ; Advance to next entry")
    irLoad("nv", "ptr", "%na")
    irStore("ptr", "%nv", "%ea")
    irBr("entry.loop")
    irLabel("bucket.next")
    irLoad("ni", "i64", "%ia")
    irAdd("ni1", "i64", "%ni", "1")
    irStore("i64", "%ni1", "%ia")
    irBr("bucket.loop")
    irLabel("ret")
    irRetVoid()
    emitIR("}")
    emitIR("")

    // ss_rc_destroy_array_ptrs(arr) — release all ptr elements
    emitIR("define void @ss_rc_destroy_array_ptrs(ptr %arr) {")
    irLabel("entry")
    irLoad("len", "i64", "%arr")
    irAlloca("ia", "i64", 8)
    irStore("i64", "0", "%ia")
    irBr("loop")
    irLabel("loop")
    irLoad("ci", "i64", "%ia")
    irICmp("done", "eq", "i64", "%ci", "%len")
    irBrCond("done", "ret", "body")
    irLabel("body")
    irAdd("slot", "i64", "%ci", "1")
    irGEP("ep", "i64", "%arr", "%slot")
    irLoad("ev", "i64", "%ep")
    irIntToPtr("eptr", "i64", "%ev")
    irCallVoid("ss_rc_release", "ptr %eptr")
    irAdd("ni", "i64", "%ci", "1")
    irStore("i64", "%ni", "%ia")
    irBr("loop")
    irLabel("ret")
    irRetVoid()
    emitIR("}")
    emitIR("")

    // ss_rc_atexit_cleanup — stub for program exit cleanup (future cycle cleanup)
    emitIR("define void @ss_rc_atexit_cleanup() {")
    irLabel("entry")
    irRetVoid()
    emitIR("}")
    emitIR("")

    // ── New class-instance RC (in-struct rc at offset 0, TypeInfo at offset 1) ──

    // ss_retain(ptr) — increment i32 rc at struct offset 0
    emitIR("define void @ss_retain(ptr %p) {")
    irLabel("entry")
    irICmp("isnull", "eq", "ptr", "%p", "null")
    irBrCond("isnull", "done", "inc")
    irLabel("inc")
    emitIR("  %rc_ptr = getelementptr %ObjHeader, ptr %p, i32 0, i32 0")
    irLoad("rc", "i32", "%rc_ptr")
    irAdd("rc1", "i32", "%rc", "1")
    irStore("i32", "%rc1", "%rc_ptr")
    irBr("done")
    irLabel("done")
    irRetVoid()
    emitIR("}")
    emitIR("")

    // ss_release(ptr) — decrement i32 rc; if 0 call drop via TypeInfo
    emitIR("define void @ss_release(ptr %p) {")
    irLabel("entry")
    irICmp("isnull", "eq", "ptr", "%p", "null")
    irBrCond("isnull", "done", "dec")
    irLabel("dec")
    emitIR("  %rc_ptr = getelementptr %ObjHeader, ptr %p, i32 0, i32 0")
    irLoad("rc", "i32", "%rc_ptr")
    irSub("rc1", "i32", "%rc", "1")
    irICmp("iszero", "eq", "i32", "%rc1", "0")
    irBrCond("iszero", "drop", "store")
    irLabel("store")
    irStore("i32", "%rc1", "%rc_ptr")
    irBr("done")
    irLabel("drop")
    // Write rc=0 before calling drop to prevent reentrant double-free
    irStore("i32", "0", "%rc_ptr")
    emitIR("  %ti_ptr = getelementptr %ObjHeader, ptr %p, i32 0, i32 1")
    irLoad("ti", "ptr", "%ti_ptr")
    emitIR("  %drop_fn_ptr = getelementptr %TypeInfo, ptr %ti, i32 0, i32 0")
    irLoad("drop_fn", "ptr", "%drop_fn_ptr")
    emitIR("  call void %drop_fn(ptr %p)")
    irBr("done")
    irLabel("done")
    irRetVoid()
    emitIR("}")
    emitIR("")

    // ss_alloc(size) — allocate zeroed memory for class instance (mimalloc)
    emitIR("define ptr @ss_alloc(i64 %size) {")
    irLabel("entry")
    irCall("p", "ptr", "mi_calloc", "i64 1, i64 %size")
    irRet("ptr", "%p")
    emitIR("}")
    emitIR("")

    // ss_dealloc(ptr) — free class instance memory (mimalloc)
    emitIR("define void @ss_dealloc(ptr %p) {")
    irLabel("entry")
    irCallVoid("mi_free", "ptr %p")
    irRetVoid()
    emitIR("}")
    emitIR("")

}
