// gen_rt_string.ss — Runtime string operations and type conversions

// ── String operations ─────────────────────────────────────────

function emitRuntimeStringOps() {
    // ss_stringLength
    emitIR("define i32 @ss_stringLength(ptr %s) {")
    irCall("len", "i64", "strlen", "ptr %s")
    irTrunc("result", "i64", "%len", "i32")
    irRet("i32", "%result")
    emitIR("}")
    emitIR("")

    // ss_string_concat
    emitIR("define ptr @ss_string_concat(ptr %a, ptr %b) {")
    irCall("alen", "i64", "strlen", "ptr %a")
    irCall("blen", "i64", "strlen", "ptr %b")
    irAdd("total", "i64", "%alen", "%blen")
    irAdd("size", "i64", "%total", "1")
    irCall("buf", "ptr", "ss_rc_alloc", "i64 %size, i32 0")
    irCall("_1", "ptr", "memcpy", "ptr %buf, ptr %a, i64 %alen")
    irGEP("dst", "i8", "%buf", "%alen")
    irAdd("blen1", "i64", "%blen", "1")
    irCall("_2", "ptr", "memcpy", "ptr %dst, ptr %b, i64 %blen1")
    irRet("ptr", "%buf")
    emitIR("}")
    emitIR("")

    // ss_string_eq
    emitIR("define i32 @ss_string_eq(ptr %a, ptr %b) {")
    irCall("cmp", "i32", "strcmp", "ptr %a, ptr %b")
    irICmp("iseq", "eq", "i32", "%cmp", "0")
    irZext("result", "i1", "%iseq", "i32")
    irRet("i32", "%result")
    emitIR("}")
    emitIR("")

    // ss_string_ne
    emitIR("define i32 @ss_string_ne(ptr %a, ptr %b) {")
    irCall("cmp", "i32", "strcmp", "ptr %a, ptr %b")
    irICmp("isne", "ne", "i32", "%cmp", "0")
    irZext("result", "i1", "%isne", "i32")
    irRet("i32", "%result")
    emitIR("}")
    emitIR("")

    // ss_strcmp
    emitIR("define i32 @ss_strcmp(ptr %a, ptr %b) {")
    irCall("result", "i32", "strcmp", "ptr %a, ptr %b")
    irRet("i32", "%result")
    emitIR("}")
    emitIR("")

    // ss_indexOf
    emitIR("define i32 @ss_indexOf(ptr %s, ptr %sub) {")
    irLabel("entry")
    irCall("found", "ptr", "strstr", "ptr %s, ptr %sub")
    irICmp("isnull", "eq", "ptr", "%found", "null")
    irBrCond("isnull", "neg", "pos")
    irLabel("neg")
    irRet("i32", "-1")
    irLabel("pos")
    irPtrToInt("faddr", "%found", "i64")
    irPtrToInt("saddr", "%s", "i64")
    irSub("diff", "i64", "%faddr", "%saddr")
    irTrunc("result", "i64", "%diff", "i32")
    irRet("i32", "%result")
    emitIR("}")
    emitIR("")

    // ss_charAt
    emitIR("define ptr @ss_charAt(ptr %s, i32 %idx) {")
    irLabel("entry")
    irCall("len", "i64", "strlen", "ptr %s")
    irSext("idx64", "i32", "%idx", "i64")
    irICmp("oob", "sge", "i64", "%idx64", "%len")
    irBrCond("oob", "oob_ret", "ok")
    irLabel("oob_ret")
    irCall("empty", "ptr", "ss_rc_strdup", "ptr @.rt.str.empty")
    irRet("ptr", "%empty")
    irLabel("ok")
    irCall("buf", "ptr", "ss_rc_alloc", "i64 2, i32 0")
    irGEP("cp", "i8", "%s", "%idx64")
    irLoad("ch", "i8", "%cp")
    irStore("i8", "%ch", "%buf")
    irGEP("term", "i8", "%buf", "1")
    irStore("i8", "0", "%term")
    irRet("ptr", "%buf")
    emitIR("}")
    emitIR("")

    // ss_substring
    emitIR("define ptr @ss_substring(ptr %s, i32 %start, i32 %count) {")
    irLabel("entry")
    irCall("len", "i64", "strlen", "ptr %s")
    irSext("start64", "i32", "%start", "i64")
    irSext("count64", "i32", "%count", "i64")
    irICmp("neg", "slt", "i64", "%start64", "0")
    irSelect("clamped_start", "neg", "i64", "0", "%start64")
    irICmp("past_end", "sgt", "i64", "%clamped_start", "%len")
    irSelect("safe_start", "past_end", "i64", "%len", "%clamped_start")
    irAdd("end_pos", "i64", "%safe_start", "%count64")
    irICmp("overflow", "sgt", "i64", "%end_pos", "%len")
    irSub("remaining", "i64", "%len", "%safe_start")
    irSelect("safe_count", "overflow", "i64", "%remaining", "%count64")
    irAdd("alloc", "i64", "%safe_count", "1")
    irCall("buf", "ptr", "ss_rc_alloc", "i64 %alloc, i32 0")
    irGEP("src", "i8", "%s", "%safe_start")
    irCall("_1", "ptr", "memcpy", "ptr %buf, ptr %src, i64 %safe_count")
    irGEP("term", "i8", "%buf", "%safe_count")
    irStore("i8", "0", "%term")
    irRet("ptr", "%buf")
    emitIR("}")
    emitIR("")

    // ss_charCodeAt
    emitIR("define i32 @ss_charCodeAt(ptr %s, i32 %idx) {")
    irSext("idx64", "i32", "%idx", "i64")
    irGEP("cp", "i8", "%s", "%idx64")
    irLoad("ch", "i8", "%cp")
    irZext("result", "i8", "%ch", "i32")
    irRet("i32", "%result")
    emitIR("}")
    emitIR("")

    // ss_fromCharCode
    emitIR("define ptr @ss_fromCharCode(i32 %code) {")
    irCall("buf", "ptr", "ss_rc_alloc", "i64 2, i32 0")
    irTrunc("ch", "i32", "%code", "i8")
    irStore("i8", "%ch", "%buf")
    irGEP("term", "i8", "%buf", "1")
    irStore("i8", "0", "%term")
    irRet("ptr", "%buf")
    emitIR("}")
    emitIR("")

    // ss_split — two pass: count then extract
    emitIR("define ptr @ss_split(ptr %s, ptr %delim) {")
    irLabel("entry")
    irCall("dlen", "i64", "strlen", "ptr %delim")
    irCall("slen", "i64", "strlen", "ptr %s")
    emitIR("  ; Count pass")
    irAlloca("cnt", "i32", 4)
    irStore("i32", "1", "%cnt")
    irAlloca("p1", "ptr", 8)
    irStore("ptr", "%s", "%p1")
    irICmp("is_empty_d", "eq", "i64", "%dlen", "0")
    irBrCond("is_empty_d", "build", "count.loop")
    irLabel("count.loop")
    irLoad("cp", "ptr", "%p1")
    irCall("found", "ptr", "strstr", "ptr %cp, ptr %delim")
    irICmp("nf", "eq", "ptr", "%found", "null")
    irBrCond("nf", "build", "count.inc")
    irLabel("count.inc")
    irLoad("cc", "i32", "%cnt")
    irAdd("cc1", "i32", "%cc", "1")
    irStore("i32", "%cc1", "%cnt")
    irGEP("np", "i8", "%found", "%dlen")
    irStore("ptr", "%np", "%p1")
    irBr("count.loop")
    irLabel("build")
    irLoad("n", "i32", "%cnt")
    irSext("n64", "i32", "%n", "i64")
    irAdd("slots", "i64", "%n64", "1")
    irMul("asize", "i64", "%slots", "8")
    irCall("arr", "ptr", "ss_rc_calloc", "i64 %asize, i32 5")
    irStore("i64", "%n64", "%arr")
    emitIR("  ; Extract pass")
    irAlloca("idx", "i32", 4)
    irStore("i32", "0", "%idx")
    irStore("ptr", "%s", "%p1")
    irBrCond("is_empty_d", "single", "ext.loop")
    irLabel("single")
    irCall("dup0", "ptr", "ss_rc_strdup", "ptr %s")
    irGEP("slot0", "i64", "%arr", "1")
    irPtrToInt("dup0i", "%dup0", "i64")
    irStore("i64", "%dup0i", "%slot0")
    irRet("ptr", "%arr")
    irLabel("ext.loop")
    irLoad("ep", "ptr", "%p1")
    irCall("ef", "ptr", "strstr", "ptr %ep, ptr %delim")
    irICmp("enf", "eq", "ptr", "%ef", "null")
    irBrCond("enf", "ext.last", "ext.copy")
    irLabel("ext.copy")
    irPtrToInt("elen", "%ef", "i64")
    irPtrToInt("estart", "%ep", "i64")
    irSub("epartlen", "i64", "%elen", "%estart")
    irAdd("ealloc", "i64", "%epartlen", "1")
    irCall("ebuf", "ptr", "ss_rc_alloc", "i64 %ealloc, i32 0")
    irCall("_1", "ptr", "memcpy", "ptr %ebuf, ptr %ep, i64 %epartlen")
    irGEP("eterm", "i8", "%ebuf", "%epartlen")
    irStore("i8", "0", "%eterm")
    irLoad("ei", "i32", "%idx")
    irSext("ei64", "i32", "%ei", "i64")
    irAdd("eslot", "i64", "%ei64", "1")
    irGEP("eptr", "i64", "%arr", "%eslot")
    irPtrToInt("ebufi", "%ebuf", "i64")
    irStore("i64", "%ebufi", "%eptr")
    irAdd("ei1", "i32", "%ei", "1")
    irStore("i32", "%ei1", "%idx")
    irGEP("enp", "i8", "%ef", "%dlen")
    irStore("ptr", "%enp", "%p1")
    irBr("ext.loop")
    irLabel("ext.last")
    irCall("ldup", "ptr", "ss_rc_strdup", "ptr %ep")
    irLoad("li", "i32", "%idx")
    irSext("li64", "i32", "%li", "i64")
    irAdd("lslot", "i64", "%li64", "1")
    irGEP("lptr", "i64", "%arr", "%lslot")
    irPtrToInt("ldupi", "%ldup", "i64")
    irStore("i64", "%ldupi", "%lptr")
    irRet("ptr", "%arr")
    emitIR("}")
    emitIR("")
}

// ── Type conversions ──────────────────────────────────────────

function emitRuntimeConversions() {
    // ss_int_to_string
    emitIR("define ptr @ss_int_to_string(i32 %val) {")
    irCall("buf", "ptr", "ss_rc_alloc", "i64 32, i32 0")
    irCall("_1", "i32 (ptr, i64, ptr, ...)", "snprintf", "ptr %buf, i64 32, ptr @.rt.fmt.d, i32 %val")
    irRet("ptr", "%buf")
    emitIR("}")
    emitIR("")

    // ss_double_to_string
    emitIR("define ptr @ss_double_to_string(double %val) {")
    irCall("buf", "ptr", "ss_rc_alloc", "i64 64, i32 0")
    irCall("_1", "i32 (ptr, i64, ptr, ...)", "snprintf", "ptr %buf, i64 64, ptr @.rt.fmt.g, double %val")
    irRet("ptr", "%buf")
    emitIR("}")
    emitIR("")

    // ss_bool_to_string
    emitIR("define ptr @ss_bool_to_string(i32 %val) {")
    irICmp("nonzero", "ne", "i32", "%val", "0")
    irSelect("result", "nonzero", "ptr", "@.rt.str.true", "@.rt.str.false")
    irRet("ptr", "%result")
    emitIR("}")
    emitIR("")

    // ss_i64_to_string — always format as i64 integer (heuristic eliminated)
    emitIR("define ptr @ss_i64_to_string(i64 %val) {")
    irLabel("entry")
    irCall("buf", "ptr", "ss_rc_alloc", "i64 32, i32 0")
    irCall("_1", "i32 (ptr, i64, ptr, ...)", "snprintf", "ptr %buf, i64 32, ptr @.rt.fmt.lld, i64 %val")
    irRet("ptr", "%buf")
    emitIR("}")
    emitIR("")

    // ss_parseInt
    emitIR("define i32 @ss_parseInt(ptr %s) {")
    irCall("result", "i32", "atoi", "ptr %s")
    irRet("i32", "%result")
    emitIR("}")
    emitIR("")

    // ss_parseDouble
    emitIR("define double @ss_parseDouble(ptr %s) {")
    irCall("result", "double", "atof", "ptr %s")
    irRet("double", "%result")
    emitIR("}")
    emitIR("")
}
