// D146 Phase 2 unit test — JDBC 4.3 §15 ResultSet cursor / scrollable
// constants + interface methods + Statement / Connection overloads.
// Pure local, no docker dependency. Phase 3 wires real cursor protocol
// through MysqlBinaryResultSet (D146 §Phase 收关锚 §Phase 3); this file
// only verifies the interface signatures are reachable and the JDBC
// standard constant values match the spec.
//
// What this validates:
//   - JDBC 4.3 §java.sql.ResultSet integer constants (1003-1007)
//   - 7 cursor / scrollable methods reachable via mock impl
//   - Statement.executeQuery(sql, type, concurrency) overload signature
//   - Connection.prepareStatement(sql, type, concurrency) overload signature
//   - type + concurrency parameters propagate to the implementor (validated
//     via mock-recorded state — proves the parameters are not silently
//     dropped at the interface signature level)
//
// What is deferred to Phase 3+:
//   - MysqlBinaryResultSet useCursor / fetchSize / cursorExhausted / statementId
//   - In-memory cache for TYPE_SCROLL_INSENSITIVE absolute / first / last /
//     previous (MySQL 5.7+ has no server scrollable cursor — D146 §A.2 H5)
//   - setFetchSize Integer.MIN_VALUE dual semantics (Phase 4 D146 §A.2 H4)

import { assertEqual, assertTrue } from "@/lib/test"
import { Connection, Statement, PreparedStatement, ResultSet, TYPE_FORWARD_ONLY, TYPE_SCROLL_INSENSITIVE, TYPE_SCROLL_SENSITIVE, CONCUR_READ_ONLY } from "@/lib/java/sql"

// ── Mock impls ───────────────────────────────────────────────
// Minimal-shape classes for signature-level verification. Records
// mutator-style argument snapshots so tests can prove parameters reach
// the implementor (vs being silently dropped at the interface signature).

class NoopResultSet : ResultSet {
    fetchSize: int
    closed: int

    function next(): int { return 0 }
    function getString(col: string): string { return "" }
    function getInt(col: string): int { return 0 }
    function getLong(col: string): int { return 0 }
    function getDouble(col: string): double { return 0.0 }
    function getBoolean(col: string): int { return 0 }
    function setFetchSize(rows: int) { this.fetchSize = rows }
    function getFetchSize(): int { return this.fetchSize }
    function absolute(row: int): int { return 0 }
    function first(): int { return 0 }
    function last(): int { return 0 }
    function previous(): int { return 0 }
    function getRow(): int { return 0 }
    function close() { this.closed = 1 }
}

class NoopPreparedStatement : PreparedStatement {
    function setInt(idx: int, val: int) {}
    function setLong(idx: int, val: int) {}
    function setString(idx: int, val: string) {}
    function setDouble(idx: int, val: double) {}
    function setBoolean(idx: int, val: int) {}
    function setNull(idx: int) {}
    // D146 Phase 4 — PreparedStatement interface gained setFetchSize for
    // Spring JdbcTemplate.query(sql, setter, callback) dual-semantics
    // dispatch. Mock stub matches the interface signature; production
    // path lives in MysqlPreparedStatement.setFetchSize (prepared.ss).
    function setFetchSize(rows: int) {}
    function executeQuery(): ResultSet { return new NoopResultSet(0, 0) }
    function executeUpdate(): int { return 0 }
    function getGeneratedKeys(): ResultSet { return new NoopResultSet(0, 0) }
    function getLastInsertId(): int { return 0 }
    function close() {}
}

class NoopStatement : Statement {
    lastType: int
    lastConcurrency: int

    function executeQuery(sql: string): ResultSet { return new NoopResultSet(0, 0) }
    function executeQuery(sql: string, type: int, concurrency: int): ResultSet {
        this.lastType = type
        this.lastConcurrency = concurrency
        return new NoopResultSet(0, 0)
    }
    function executeUpdate(sql: string): int { return 0 }
    function execute(sql: string): int { return 0 }
    function getGeneratedKeys(): ResultSet { return new NoopResultSet(0, 0) }
    function getLastInsertId(): int { return 0 }
    function close() {}
}

class NoopConnection : Connection {
    lastType: int
    lastConcurrency: int

    function createStatement(): Statement { return new NoopStatement(0, 0) }
    function prepareStatement(sql: string): PreparedStatement { return new NoopPreparedStatement() }
    function prepareStatement(sql: string, autoGeneratedKeys: int): PreparedStatement {
        return new NoopPreparedStatement()
    }
    function prepareStatement(sql: string, type: int, concurrency: int): PreparedStatement {
        this.lastType = type
        this.lastConcurrency = concurrency
        return new NoopPreparedStatement()
    }
    function setAutoCommit(auto: int) {}
    function commit() {}
    function rollback() {}
    function close() {}
    function isClosed(): int { return 0 }
}

function main() {
    test("5 cursor / concurrency constants match JDBC 4.3 §java.sql.ResultSet", () => {
        // Standard JDBC integer values - any drift breaks ORM (Hibernate
        // ScrollableResults / MyBatis Cursor) interop.
        assertEqual(TYPE_FORWARD_ONLY, 1003)
        assertEqual(TYPE_SCROLL_INSENSITIVE, 1004)
        assertEqual(TYPE_SCROLL_SENSITIVE, 1005)
        assertEqual(CONCUR_READ_ONLY, 1007)
        // Pairwise distinct - accidental merge of SCROLL_INSENSITIVE /
        // SCROLL_SENSITIVE would mis-route Phase 3 dispatch to the wrong
        // cursor-type branch.
        assertTrue(TYPE_FORWARD_ONLY != TYPE_SCROLL_INSENSITIVE)
        assertTrue(TYPE_SCROLL_INSENSITIVE != TYPE_SCROLL_SENSITIVE)
        assertTrue(TYPE_SCROLL_SENSITIVE != CONCUR_READ_ONLY)
    })

    test("ResultSet 7 cursor / scrollable methods reachable", () => {
        const rs = new NoopResultSet(0, 0)
        // setFetchSize / getFetchSize round-trip through implementor field.
        rs.setFetchSize(10)
        assertEqual(rs.getFetchSize(), 10)
        rs.setFetchSize(100)
        assertEqual(rs.getFetchSize(), 100)
        // forward-only fallback returns 0 (Phase 3 in-memory cache wires
        // real positioning for TYPE_SCROLL_INSENSITIVE).
        assertEqual(rs.absolute(50), 0)
        assertEqual(rs.first(), 0)
        assertEqual(rs.last(), 0)
        assertEqual(rs.previous(), 0)
        assertEqual(rs.getRow(), 0)
    })

    test("Statement.executeQuery(sql, type, concurrency) overload reachable", () => {
        const stmt = new NoopStatement(0, 0)
        // type + concurrency propagate to the implementor (vs being dropped
        // at the interface signature).
        stmt.executeQuery("SELECT 1", TYPE_FORWARD_ONLY, CONCUR_READ_ONLY)
        assertEqual(stmt.lastType, TYPE_FORWARD_ONLY)
        assertEqual(stmt.lastConcurrency, CONCUR_READ_ONLY)
        // 1-arg form still reachable (no shadowing). lastType / lastConcurrency
        // retain the previous overload's writes — the 1-arg form does not
        // touch them.
        stmt.executeQuery("SELECT 1")
        assertEqual(stmt.lastType, TYPE_FORWARD_ONLY)
    })

    test("Connection.prepareStatement(sql, type, concurrency) overload reachable", () => {
        const conn = new NoopConnection(0, 0)
        // 3-arg overload propagates type + concurrency to the implementor.
        conn.prepareStatement("SELECT * FROM t WHERE id = ?", TYPE_SCROLL_INSENSITIVE, CONCUR_READ_ONLY)
        assertEqual(conn.lastType, TYPE_SCROLL_INSENSITIVE)
        assertEqual(conn.lastConcurrency, CONCUR_READ_ONLY)
        // 1-arg + 2-arg + 3-arg forms coexist (overload table 3 deep —
        // D138 prepareStatement(sql, autoGen) + D146 prepareStatement(sql,
        // type, conc) without conflict).
        conn.prepareStatement("SELECT 1")
        conn.prepareStatement("INSERT INTO t VALUES (?)", 1)
    })

    test("Cursor / scrollable methods chainable through Connection → Statement → ResultSet", () => {
        // End-to-end mock dispatch: open mock connection, prepare scrollable
        // cursor, drive ResultSet methods. Pure local — Phase 3 wires the
        // docker round-trip.
        const conn = new NoopConnection(0, 0)
        const ps = conn.prepareStatement("SELECT id FROM t", TYPE_SCROLL_INSENSITIVE, CONCUR_READ_ONLY)
        const rs = ps.executeQuery()
        rs.setFetchSize(10)
        assertEqual(rs.getFetchSize(), 10)
        // forward-only fallback — Phase 3 returns 1 + cached row index for
        // TYPE_SCROLL_INSENSITIVE.
        assertEqual(rs.absolute(5), 0)
        rs.close()
        ps.close()
        conn.close()
    })
}
