// MySQL JDBC driver — D134 Phase 5.
//
// class MysqlConnection : Connection and class MysqlStatement : Statement
// implement the lib/java/sql.ss D025 interfaces. ResultSet is implemented by
// class MysqlResultSet in lib/com/mysql/query.ss (Phase 4 — D025 §interface).
//
// getMysqlConnection parses a jdbc:mysql:// URL, calls handshake.mysqlConnect
// to authenticate, and wraps the authenticated fd in a MysqlConnection.
//
// Circular import note: this file imports lib/java/sql for the Connection /
// Statement / ResultSet interfaces; lib/java/sql imports getMysqlConnection
// from here for DriverManager_getConnection url dispatch. bootstrap/main.ss
// resolveInner (line 186-187) uses a visited set so the cycle expands cleanly —
// interfaces and classes are collected globally before method bodies resolve.
//
// Connection layering note: handshake.mysqlConnect returns the authenticated
// socket fd (D134 Phase 5 NAMESPACE COLLISION decision: handshake.ss owns auth
// protocol only, driver-layer Connection state lives here in jdbc.ss).

import { Connection, Statement, PreparedStatement, ResultSet, DatabaseMetaData, JDBC_MAJOR_VERSION, JDBC_MINOR_VERSION, TRANSACTION_READ_UNCOMMITTED, TRANSACTION_READ_COMMITTED, TRANSACTION_REPEATABLE_READ, TRANSACTION_SERIALIZABLE, TYPE_FORWARD_ONLY, TYPE_SCROLL_INSENSITIVE, CONCUR_READ_ONLY, CONCUR_UPDATABLE } from "@/lib/java/sql"
import { writePacket } from "@/lib/com/mysql/wire"
import { mysqlConnect } from "@/lib/com/mysql/handshake"
import { sendQuery, readUpdateResultPacket, okPacketAffectedRows, okPacketLastInsertId, readQueryResultSet, MysqlResultSet, GeneratedKeyResultSet, NoopResultSetMetaData } from "@/lib/com/mysql/query"
import { doPrepare } from "@/lib/com/mysql/prepared"
import { URL, URL_parse } from "@/lib/url"

const COM_QUIT = 0x01
const DEFAULT_PORT = 3306
const URL_PREFIX = "jdbc:"

class MysqlConnection : Connection {
    fd: int
    autoCommit: int
    closed: int
    // D156 §Phase 3 — driver identity for DatabaseMetaData. Password
    // intentionally not held (JDBC parity + SS memory hygiene).
    url: string
    user: string
    // D156 §Phase 3 — lazy DatabaseMetaData cache. NoopDatabaseMetaData
    // sentinel until first getMetaData() call. Interface-typed field is
    // safe via D155 Phase 3 codegen fix (bootstrap/gen/gen_type_ops.ss
    // isInterfaceType branch — TypeInfo.deep_clone_fn vtable dispatch).
    metaDataCache: DatabaseMetaData
    metaDataInited: int

    function createStatement(): Statement {
        return new MysqlStatement(this.fd, 0)
    }

    // Drives the full prepare flow via prepared.doPrepare — keeps PrepareOk
    // field access encapsulated inside prepared.ss (cross-module struct field
    // access from a function whose body emits before the struct's IR `type`
    // declaration would forward-reference the type and llc would reject the
    // GEP). Phase 1 occupies the prepare half of the protocol; setXxx and
    // executeQuery / executeUpdate / close are Phase 2 stubs.
    function prepareStatement(sql: string): PreparedStatement {
        return doPrepare(this.fd, sql)
    }

    // D138 Phase 2 — JDBC 4.3 §Connection.prepareStatement(sql, autoGeneratedKeys).
    // MySQL wire protocol returns lastInsertId in OkPacket for every INSERT, so
    // autoGeneratedKeys is informational only on this driver — both
    // RETURN_GENERATED_KEYS and NO_GENERATED_KEYS yield the same prepared
    // statement. Future PostgreSQL / SQLite drivers gating id retrieval will
    // read the flag here.
    function prepareStatement(sql: string, autoGeneratedKeys: int): PreparedStatement {
        return doPrepare(this.fd, sql)
    }

    // D146 Phase 3 — JDBC 4.3 §Connection.prepareStatement(sql, type, concurrency).
    // type / concurrency are stashed on the MysqlPreparedStatement so that the
    // 0-arg executeQuery() (PreparedStatement interface) can derive the
    // COM_STMT_EXECUTE cursor flag without needing the user to call the
    // driver-specific 3-arg overload. Scrollable type (TYPE_SCROLL_INSENSITIVE
    // / SENSITIVE) opens a server-side cursor + activates the in-memory cache
    // fallback (D146 §A.2 H5 — MySQL 5.7+ has no server scrollable cursor).
    function prepareStatement(sql: string, type: int, concurrency: int): PreparedStatement {
        const ps = doPrepare(this.fd, sql)
        ps.setCursorMode(type, concurrency)
        return ps
    }

    function setAutoCommit(auto: int) {
        if (this.autoCommit == auto) { return }
        let sql = "SET autocommit=0"
        if (auto == 1) { sql = "SET autocommit=1" }
        sendQuery(this.fd, sql)
        readUpdateResultPacket(this.fd)
        this.autoCommit = auto
    }

    function commit() {
        sendQuery(this.fd, "COMMIT")
        readUpdateResultPacket(this.fd)
    }

    function rollback() {
        sendQuery(this.fd, "ROLLBACK")
        readUpdateResultPacket(this.fd)
    }

    // COM_QUIT is a single 0x01 byte payload, seqId reset to 0. The server
    // closes the socket after receiving it; we close our end too.
    //
    // D156 Phase 3 — break MysqlConnection ↔ MysqlDatabaseMetaData RC cycle.
    // MysqlDatabaseMetaData.conn back-points here; under Perceus RC the
    // pair would leak if the cache outlives the explicit close. Replacing
    // the cache with a stateless NoopDatabaseMetaData lets the previous
    // reflection wrapper (and its conn back-ref) drop. Implicit drop
    // without close() still leaks — full cycle detection 留 SS GC sub-D
    // (D156 §F6).
    function close() {
        if (this.closed != 0) { return }
        writePacket(this.fd, 0, fromCharCode(COM_QUIT), 1)
        tcpClose(this.fd)
        this.closed = 1
        this.metaDataCache = new NoopDatabaseMetaData()
        this.metaDataInited = 0
    }

    function isClosed(): int {
        return this.closed
    }

    // D156 Phase 3 — lazy MysqlDatabaseMetaData (§A.2 H5). Single instance
    // per Connection per JDBC §11 implicit contract.
    function getMetaData(): DatabaseMetaData {
        if (this.metaDataInited == 0) {
            this.metaDataCache = new MysqlDatabaseMetaData(this, "", 0)
            this.metaDataInited = 1
        }
        return this.metaDataCache
    }
}

class MysqlStatement : Statement {
    fd: int
    // Last lastInsertId from the most recent executeUpdate; ERR path throws
    // SQLException via readUpdateResultPacket so a failed INSERT never writes
    // here. Default 0 — JDBC 4.3 §Statement.getGeneratedKeys spec: "an empty
    // ResultSet" when no row was inserted.
    lastInsertId: int

    function executeQuery(sql: string): ResultSet {
        sendQuery(this.fd, sql)
        return readQueryResultSet(this.fd)
    }

    // D146 Phase 2 — JDBC 4.3 §Statement.executeQuery(sql, type, concurrency).
    // MySQL Statement (COM_QUERY 0x03) has no server-side cursor support —
    // type+concurrency are informational on this path. Server-side cursor lives
    // exclusively on PreparedStatement (Connection.prepareStatement(sql, type,
    // concurrency) + COM_STMT_EXECUTE flags CURSOR_TYPE_READ_ONLY 0x01).
    function executeQuery(sql: string, type: int, concurrency: int): ResultSet {
        sendQuery(this.fd, sql)
        return readQueryResultSet(this.fd)
    }

    function executeUpdate(sql: string): int {
        sendQuery(this.fd, sql)
        const ok = readUpdateResultPacket(this.fd)
        this.lastInsertId = okPacketLastInsertId(ok)
        return okPacketAffectedRows(ok)
    }

    function execute(sql: string): int {
        sendQuery(this.fd, sql)
        return okPacketAffectedRows(readUpdateResultPacket(this.fd))
    }

    // D138 Phase 2 — JDBC 4.3 §Statement.getGeneratedKeys returns a ResultSet over
    // the auto-increment ids generated by the most recent executeUpdate. Wraps
    // lastInsertId (single-row, single-column "GENERATED_KEY" — MySQL Connector/J
    // standard). Multi-row INSERT VALUES (...),(...) returns the first id only;
    // subsequent ids are first + 1, first + 2, ... by MySQL protocol contract.
    function getGeneratedKeys(): ResultSet {
        return new GeneratedKeyResultSet(this.lastInsertId, 0, new NoopResultSetMetaData(), 0)
    }

    function getLastInsertId(): int {
        return this.lastInsertId
    }

    // Statement does not own the socket fd — Connection does. close() at the
    // Statement layer is a no-op; ResultSet.close() drains the socket buffer.
    function close() {
    }
}

// Parses jdbc:mysql://[user[:pwd]@]host[:port]/[db][?param=val&...] and opens
// an authenticated connection. Any handshake/auth failure throws an
// SQLException subclass via mysqlConnect (D139 §核心原则 4 — no closed
// sentinel Connection; callers must use try/catch).
//
// JDBC URLs carry a double scheme (`jdbc:mysql:`) which RFC 3986 forbids
// (urlIsValidScheme rejects ':' inside scheme), so we strip the `jdbc:` prefix
// before delegating to URL_parse — `mysql://...` is then a normal URI.
//
// Phase 5 scope: query parameters after `?` are stripped (not consumed). User
// is "root", password "" and database "" by default; port defaults to 3306.
function getMysqlConnection(url: string): MysqlConnection {
    const stripped = url.substring(URL_PREFIX.length(), url.length() - URL_PREFIX.length())
    const u = URL_parse(stripped)

    let user = u.username()
    if (user == "") { user = "root" }
    const pwd = u.password()

    let host = u.hostname()
    if (host == "") { host = "127.0.0.1" }

    let port = DEFAULT_PORT
    const portStr = u.port()
    if (portStr != "") {
        const p = parseInt(portStr)
        if (p > 0) { port = p }
    }

    let db = ""
    const path = u.pathname()
    if (path.length() > 1) {
        db = path.substring(1, path.length() - 1)
    }

    const fd = mysqlConnect(host, port, user, pwd, db)
    return new MysqlConnection(fd, 1, 0, url, user, new NoopDatabaseMetaData(), 0)
}

// D156 Phase 1 — INFORMATION_SCHEMA per-call PreparedStatement helpers and
// driver-static accessors. The MysqlDatabaseMetaData class (Phase 3) routes
// every spec method through these so the protocol boilerplate (prepare →
// executeQuery → row 1 col 1 → drain) lives in one place; future lazy cache
// (D156 §F5) hooks here without touching ≥30 metadata method bodies.
//
// Each *String / *Int helper grabs column 1 by reflecting its name through
// rs.getMetaData().getColumnName(1) — caller's SELECT need not alias the
// expression, since MySQL returns the literal text ("VERSION()", "1", ...) as
// the column name when no alias is given. Empty result set is well-defined:
// "" for string and 0 for int (D156 §A.2 H9 — Connection close-state errors
// are deferred to D139 §F SQLException coverage; here the well-defined empty
// path keeps Phase 3 metadata methods tolerant of stripped-down server states).
//
// getServerVersionStatic walks SELECT VERSION() per-call — Phase 1 does not
// hold serverVersion on MysqlConnection (would widen handshake.mysqlConnect's
// return shape from int to a class). Lazy cache lands in Phase 3 alongside
// the rest of MysqlDatabaseMetaData (D156 §A.2 H6).
//
// Static accessors return JDBC §11 spec literals for MySQL (Connector/J
// range): catalog term "database" / schema term "" (single-tier model, H2)
// / procedure term "procedure" / catalog separator "." / driver name
// "MySQL Connector/SS" + version derived from DRIVER_VERSION_MAJOR /
// _MINOR (SS project hard-codes, not parsed from any manifest — H6;
// single-source so that getDriverVersionStatic / getDriverMajorVersionStatic
// / getDriverMinorVersionStatic cannot drift apart on bumps).

const DRIVER_VERSION_MAJOR = 1
const DRIVER_VERSION_MINOR = 0

function infoSchemaQuery(conn: Connection, sql: string): ResultSet {
    const ps = conn.prepareStatement(sql)
    return ps.executeQuery()
}

function infoSchemaQueryString(conn: Connection, sql: string): string {
    const rs = infoSchemaQuery(conn, sql)
    if (rs.next() == 0) {
        rs.close()
        return ""
    }
    const md = rs.getMetaData()
    const v = rs.getString(md.getColumnName(1))
    rs.close()
    return v
}

function infoSchemaQueryInt(conn: Connection, sql: string): int {
    const rs = infoSchemaQuery(conn, sql)
    if (rs.next() == 0) {
        rs.close()
        return 0
    }
    const md = rs.getMetaData()
    const v = rs.getInt(md.getColumnName(1))
    rs.close()
    return v
}

function getCatalogTermStatic(): string {
    return "database"
}

function getSchemaTermStatic(): string {
    return ""
}

function getProcedureTermStatic(): string {
    return "procedure"
}

function getCatalogSeparatorStatic(): string {
    return "."
}

function getDriverNameStatic(): string {
    return "MySQL Connector/SS"
}

function getDriverVersionStatic(): string {
    return `${DRIVER_VERSION_MAJOR}.${DRIVER_VERSION_MINOR}`
}

function getDriverMajorVersionStatic(): int {
    return DRIVER_VERSION_MAJOR
}

function getDriverMinorVersionStatic(): int {
    return DRIVER_VERSION_MINOR
}

function getServerVersionStatic(conn: Connection): string {
    return infoSchemaQueryString(conn, "SELECT VERSION() AS v")
}

// ── D156 §Phase 2 — NoopDatabaseMetaData stub ───────────────
// Stateless DatabaseMetaData fallback for Phase 2 (Phase 3 swaps in
// MysqlDatabaseMetaData real reflection). emptyResultSetStub reuses
// GeneratedKeyResultSet with firstAccessed=1 (pre-positioned past end)
// so the empty stub still walks the D155 ResultSetMetaData path (§A.2 H4).
function emptyResultSetStub(): ResultSet {
    return new GeneratedKeyResultSet(0, 1, new NoopResultSetMetaData(), 0)
}

class NoopDatabaseMetaData : DatabaseMetaData {
    function getCatalogs(): ResultSet { return emptyResultSetStub() }
    function getSchemas(): ResultSet { return emptyResultSetStub() }
    function getSchemas(catalog: string, schemaPattern: string): ResultSet { return emptyResultSetStub() }
    function getTables(catalog: string, schemaPattern: string, tableNamePattern: string, types: string): ResultSet { return emptyResultSetStub() }
    function getColumns(catalog: string, schemaPattern: string, tableNamePattern: string, columnNamePattern: string): ResultSet { return emptyResultSetStub() }
    function getPrimaryKeys(catalog: string, schema: string, table: string): ResultSet { return emptyResultSetStub() }
    function getImportedKeys(catalog: string, schema: string, table: string): ResultSet { return emptyResultSetStub() }
    function getExportedKeys(catalog: string, schema: string, table: string): ResultSet { return emptyResultSetStub() }
    function getCrossReference(parentCatalog: string, parentSchema: string, parentTable: string, foreignCatalog: string, foreignSchema: string, foreignTable: string): ResultSet { return emptyResultSetStub() }
    function getIndexInfo(catalog: string, schema: string, table: string, unique: int, approximate: int): ResultSet { return emptyResultSetStub() }
    function getProcedures(catalog: string, schemaPattern: string, procedureNamePattern: string): ResultSet { return emptyResultSetStub() }
    function getProcedureColumns(catalog: string, schemaPattern: string, procedureNamePattern: string, columnNamePattern: string): ResultSet { return emptyResultSetStub() }
    function getFunctions(catalog: string, schemaPattern: string, functionNamePattern: string): ResultSet { return emptyResultSetStub() }
    function getFunctionColumns(catalog: string, schemaPattern: string, functionNamePattern: string, columnNamePattern: string): ResultSet { return emptyResultSetStub() }
    function getDriverName(): string { return "" }
    function getDriverVersion(): string { return "" }
    function getDriverMajorVersion(): int { return 0 }
    function getDriverMinorVersion(): int { return 0 }
    function getDatabaseProductName(): string { return "" }
    function getDatabaseProductVersion(): string { return "" }
    function getURL(): string { return "" }
    function getUserName(): string { return "" }
    function getJDBCMajorVersion(): int { return 0 }
    function getJDBCMinorVersion(): int { return 0 }
    function getCatalogTerm(): string { return "" }
    function getSchemaTerm(): string { return "" }
    function getProcedureTerm(): string { return "" }
    function getCatalogSeparator(): string { return "" }
    function supportsTransactions(): int { return 0 }
    function supportsBatchUpdates(): int { return 0 }
    function supportsTransactionIsolationLevel(level: int): int { return 0 }
    function supportsResultSetType(type: int): int { return 0 }
    function supportsResultSetConcurrency(type: int, concurrency: int): int { return 0 }
}

// ── D156 §Phase 3 — MysqlDatabaseMetaData (real reflection) ──────────
// conn typed as concrete MysqlConnection (not Connection interface) —
// getURL / getUserName / lazy getDatabaseProductVersion need driver-
// specific state. Mirrors D155 MysqlResultSetMetaData.colMetadata
// concrete-typed field.
// Lazy cache only on getDatabaseProductVersion (SELECT VERSION() round-
// trip); other ResultSet-returning methods stay per-call — schema may
// evolve between calls and JDBC §11 does not require result identity
// (§F5 future cache).
// catalog vs schema (§A.2 H2): MySQL single-tier — getCatalogs walks
// SCHEMATA, getSchemas empty. PG two-tier reversal stays §F3.
class MysqlDatabaseMetaData : DatabaseMetaData {
    conn: MysqlConnection
    cachedDatabaseProductVersion: string
    cachedVersionInited: int

    // ── Driver static — Phase 1 helper delegation (single-source on bumps) ─
    function getDriverName(): string { return getDriverNameStatic() }
    function getDriverVersion(): string { return getDriverVersionStatic() }
    function getDriverMajorVersion(): int { return getDriverMajorVersionStatic() }
    function getDriverMinorVersion(): int { return getDriverMinorVersionStatic() }

    // ── Database identity — URL/user direct, version lazy SELECT VERSION() ─
    function getDatabaseProductName(): string { return "MySQL" }
    function getDatabaseProductVersion(): string {
        if (this.cachedVersionInited == 0) {
            this.cachedDatabaseProductVersion = getServerVersionStatic(this.conn)
            this.cachedVersionInited = 1
        }
        return this.cachedDatabaseProductVersion
    }
    function getURL(): string { return this.conn.url }
    function getUserName(): string { return this.conn.user }

    // ── JDBC version constants ──
    function getJDBCMajorVersion(): int { return JDBC_MAJOR_VERSION }
    function getJDBCMinorVersion(): int { return JDBC_MINOR_VERSION }

    // ── Naming convention — single-tier MySQL (§A.2 H2) ──
    function getCatalogTerm(): string { return getCatalogTermStatic() }
    function getSchemaTerm(): string { return getSchemaTermStatic() }
    function getProcedureTerm(): string { return getProcedureTermStatic() }
    function getCatalogSeparator(): string { return getCatalogSeparatorStatic() }

    // ── Capability matrix — JDBC §11 / Connector/J 5.1+ static values ──
    function supportsTransactions(): int { return 1 }
    function supportsBatchUpdates(): int { return 1 }
    function supportsTransactionIsolationLevel(level: int): int {
        if (level == TRANSACTION_READ_UNCOMMITTED) { return 1 }
        if (level == TRANSACTION_READ_COMMITTED) { return 1 }
        if (level == TRANSACTION_REPEATABLE_READ) { return 1 }
        if (level == TRANSACTION_SERIALIZABLE) { return 1 }
        return 0
    }
    // SCROLL_INSENSITIVE via D146 §A.2 H5 in-memory cache fallback (MySQL
    // 5.7+ has no server scrollable cursor); SCROLL_SENSITIVE never.
    function supportsResultSetType(type: int): int {
        if (type == TYPE_FORWARD_ONLY) { return 1 }
        if (type == TYPE_SCROLL_INSENSITIVE) { return 1 }
        return 0
    }
    // CONCUR_UPDATABLE + FORWARD_ONLY only (D147 simulated cursor).
    function supportsResultSetConcurrency(type: int, concurrency: int): int {
        if (concurrency == CONCUR_READ_ONLY) {
            if (type == TYPE_FORWARD_ONLY) { return 1 }
            if (type == TYPE_SCROLL_INSENSITIVE) { return 1 }
            return 0
        }
        if (concurrency == CONCUR_UPDATABLE) {
            if (type == TYPE_FORWARD_ONLY) { return 1 }
            return 0
        }
        return 0
    }

    // ── INFORMATION_SCHEMA reflection — per-call PreparedStatement ──────
    // Column aliases match JDBC §11 spec column names verbatim so the
    // returned ResultSet's getColumnName(N) lands on the spec contract
    // (§A.2 H7); LIKE pattern "" defaults to "%" (Connector/J idiom).
    function getCatalogs(): ResultSet {
        return infoSchemaQuery(this.conn, "SELECT SCHEMA_NAME AS TABLE_CAT FROM INFORMATION_SCHEMA.SCHEMATA ORDER BY SCHEMA_NAME")
    }
    // Single-tier MySQL — getCatalogs walks SCHEMATA, getSchemas empty.
    function getSchemas(): ResultSet { return emptyResultSetStub() }
    function getSchemas(catalog: string, schemaPattern: string): ResultSet { return emptyResultSetStub() }
    function getTables(catalog: string, schemaPattern: string, tableNamePattern: string, types: string): ResultSet {
        let cat = catalog
        if (cat == "") { cat = "%" }
        let pat = tableNamePattern
        if (pat == "") { pat = "%" }
        const sql = `SELECT TABLE_SCHEMA AS TABLE_CAT, NULL AS TABLE_SCHEM, TABLE_NAME, TABLE_TYPE, TABLE_COMMENT AS REMARKS, NULL AS TYPE_CAT, NULL AS TYPE_SCHEM, NULL AS TYPE_NAME, NULL AS SELF_REFERENCING_COL_NAME, NULL AS REF_GENERATION FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA LIKE '${cat}' AND TABLE_NAME LIKE '${pat}' ORDER BY TABLE_SCHEMA, TABLE_NAME`
        return infoSchemaQuery(this.conn, sql)
    }
    function getColumns(catalog: string, schemaPattern: string, tableNamePattern: string, columnNamePattern: string): ResultSet {
        let cat = catalog
        if (cat == "") { cat = "%" }
        let tab = tableNamePattern
        if (tab == "") { tab = "%" }
        let col = columnNamePattern
        if (col == "") { col = "%" }
        const sql = `SELECT TABLE_SCHEMA AS TABLE_CAT, NULL AS TABLE_SCHEM, TABLE_NAME, COLUMN_NAME, DATA_TYPE, COLUMN_TYPE AS TYPE_NAME, CHARACTER_MAXIMUM_LENGTH AS COLUMN_SIZE, NULL AS BUFFER_LENGTH, NUMERIC_PRECISION AS DECIMAL_DIGITS, NUMERIC_SCALE AS NUM_PREC_RADIX, IS_NULLABLE AS NULLABLE, COLUMN_COMMENT AS REMARKS, COLUMN_DEFAULT AS COLUMN_DEF, NULL AS SQL_DATA_TYPE, NULL AS SQL_DATETIME_SUB, CHARACTER_OCTET_LENGTH AS CHAR_OCTET_LENGTH, ORDINAL_POSITION, IS_NULLABLE AS IS_NULLABLE_YN, NULL AS SCOPE_CATALOG, NULL AS SCOPE_SCHEMA, NULL AS SCOPE_TABLE, NULL AS SOURCE_DATA_TYPE, EXTRA AS IS_AUTOINCREMENT, NULL AS IS_GENERATEDCOLUMN FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA LIKE '${cat}' AND TABLE_NAME LIKE '${tab}' AND COLUMN_NAME LIKE '${col}' ORDER BY TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION`
        return infoSchemaQuery(this.conn, sql)
    }
    function getPrimaryKeys(catalog: string, schema: string, table: string): ResultSet {
        let cat = catalog
        if (cat == "") { cat = "%" }
        let tab = table
        if (tab == "") { tab = "%" }
        const sql = `SELECT k.TABLE_SCHEMA AS TABLE_CAT, NULL AS TABLE_SCHEM, k.TABLE_NAME, k.COLUMN_NAME, k.ORDINAL_POSITION AS KEY_SEQ, k.CONSTRAINT_NAME AS PK_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE k JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS t ON k.CONSTRAINT_NAME = t.CONSTRAINT_NAME AND k.TABLE_SCHEMA = t.TABLE_SCHEMA AND k.TABLE_NAME = t.TABLE_NAME WHERE t.CONSTRAINT_TYPE = 'PRIMARY KEY' AND k.TABLE_SCHEMA LIKE '${cat}' AND k.TABLE_NAME LIKE '${tab}' ORDER BY k.ORDINAL_POSITION`
        return infoSchemaQuery(this.conn, sql)
    }
    function getImportedKeys(catalog: string, schema: string, table: string): ResultSet {
        let cat = catalog
        if (cat == "") { cat = "%" }
        let tab = table
        if (tab == "") { tab = "%" }
        const sql = `SELECT k.REFERENCED_TABLE_SCHEMA AS PKTABLE_CAT, NULL AS PKTABLE_SCHEM, k.REFERENCED_TABLE_NAME AS PKTABLE_NAME, k.REFERENCED_COLUMN_NAME AS PKCOLUMN_NAME, k.TABLE_SCHEMA AS FKTABLE_CAT, NULL AS FKTABLE_SCHEM, k.TABLE_NAME AS FKTABLE_NAME, k.COLUMN_NAME AS FKCOLUMN_NAME, k.ORDINAL_POSITION AS KEY_SEQ, NULL AS UPDATE_RULE, NULL AS DELETE_RULE, k.CONSTRAINT_NAME AS FK_NAME, k.REFERENCED_TABLE_NAME AS PK_NAME, NULL AS DEFERRABILITY FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE k WHERE k.REFERENCED_TABLE_NAME IS NOT NULL AND k.TABLE_SCHEMA LIKE '${cat}' AND k.TABLE_NAME LIKE '${tab}' ORDER BY k.ORDINAL_POSITION`
        return infoSchemaQuery(this.conn, sql)
    }
    function getExportedKeys(catalog: string, schema: string, table: string): ResultSet {
        let cat = catalog
        if (cat == "") { cat = "%" }
        let tab = table
        if (tab == "") { tab = "%" }
        const sql = `SELECT k.REFERENCED_TABLE_SCHEMA AS PKTABLE_CAT, NULL AS PKTABLE_SCHEM, k.REFERENCED_TABLE_NAME AS PKTABLE_NAME, k.REFERENCED_COLUMN_NAME AS PKCOLUMN_NAME, k.TABLE_SCHEMA AS FKTABLE_CAT, NULL AS FKTABLE_SCHEM, k.TABLE_NAME AS FKTABLE_NAME, k.COLUMN_NAME AS FKCOLUMN_NAME, k.ORDINAL_POSITION AS KEY_SEQ, NULL AS UPDATE_RULE, NULL AS DELETE_RULE, k.CONSTRAINT_NAME AS FK_NAME, k.REFERENCED_TABLE_NAME AS PK_NAME, NULL AS DEFERRABILITY FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE k WHERE k.REFERENCED_TABLE_NAME IS NOT NULL AND k.REFERENCED_TABLE_SCHEMA LIKE '${cat}' AND k.REFERENCED_TABLE_NAME LIKE '${tab}' ORDER BY k.ORDINAL_POSITION`
        return infoSchemaQuery(this.conn, sql)
    }
    function getCrossReference(parentCatalog: string, parentSchema: string, parentTable: string, foreignCatalog: string, foreignSchema: string, foreignTable: string): ResultSet {
        let pCat = parentCatalog
        if (pCat == "") { pCat = "%" }
        let pTab = parentTable
        if (pTab == "") { pTab = "%" }
        let fCat = foreignCatalog
        if (fCat == "") { fCat = "%" }
        let fTab = foreignTable
        if (fTab == "") { fTab = "%" }
        const sql = `SELECT k.REFERENCED_TABLE_SCHEMA AS PKTABLE_CAT, NULL AS PKTABLE_SCHEM, k.REFERENCED_TABLE_NAME AS PKTABLE_NAME, k.REFERENCED_COLUMN_NAME AS PKCOLUMN_NAME, k.TABLE_SCHEMA AS FKTABLE_CAT, NULL AS FKTABLE_SCHEM, k.TABLE_NAME AS FKTABLE_NAME, k.COLUMN_NAME AS FKCOLUMN_NAME, k.ORDINAL_POSITION AS KEY_SEQ, NULL AS UPDATE_RULE, NULL AS DELETE_RULE, k.CONSTRAINT_NAME AS FK_NAME, k.REFERENCED_TABLE_NAME AS PK_NAME, NULL AS DEFERRABILITY FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE k WHERE k.REFERENCED_TABLE_SCHEMA LIKE '${pCat}' AND k.REFERENCED_TABLE_NAME LIKE '${pTab}' AND k.TABLE_SCHEMA LIKE '${fCat}' AND k.TABLE_NAME LIKE '${fTab}' ORDER BY k.ORDINAL_POSITION`
        return infoSchemaQuery(this.conn, sql)
    }
    function getIndexInfo(catalog: string, schema: string, table: string, unique: int, approximate: int): ResultSet {
        let cat = catalog
        if (cat == "") { cat = "%" }
        let tab = table
        if (tab == "") { tab = "%" }
        let uniqueFilter = ""
        if (unique == 1) { uniqueFilter = " AND NON_UNIQUE = 0" }
        const sql = `SELECT TABLE_SCHEMA AS TABLE_CAT, NULL AS TABLE_SCHEM, TABLE_NAME, NON_UNIQUE, INDEX_SCHEMA AS INDEX_QUALIFIER, INDEX_NAME, NULL AS TYPE, SEQ_IN_INDEX AS ORDINAL_POSITION, COLUMN_NAME, COLLATION AS ASC_OR_DESC, CARDINALITY, NULL AS PAGES, NULL AS FILTER_CONDITION FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA LIKE '${cat}' AND TABLE_NAME LIKE '${tab}'${uniqueFilter} ORDER BY NON_UNIQUE, INDEX_NAME, SEQ_IN_INDEX`
        return infoSchemaQuery(this.conn, sql)
    }
    function getProcedures(catalog: string, schemaPattern: string, procedureNamePattern: string): ResultSet {
        let cat = catalog
        if (cat == "") { cat = "%" }
        let pat = procedureNamePattern
        if (pat == "") { pat = "%" }
        const sql = `SELECT ROUTINE_SCHEMA AS PROCEDURE_CAT, NULL AS PROCEDURE_SCHEM, ROUTINE_NAME AS PROCEDURE_NAME, NULL AS RESERVED1, NULL AS RESERVED2, NULL AS RESERVED3, ROUTINE_COMMENT AS REMARKS, NULL AS PROCEDURE_TYPE, ROUTINE_NAME AS SPECIFIC_NAME FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_TYPE = 'PROCEDURE' AND ROUTINE_SCHEMA LIKE '${cat}' AND ROUTINE_NAME LIKE '${pat}' ORDER BY ROUTINE_SCHEMA, ROUTINE_NAME`
        return infoSchemaQuery(this.conn, sql)
    }
    // PARAMETERS join (full JDBC §11 spec column alignment) 留 Phase 4.
    function getProcedureColumns(catalog: string, schemaPattern: string, procedureNamePattern: string, columnNamePattern: string): ResultSet {
        return emptyResultSetStub()
    }
    function getFunctions(catalog: string, schemaPattern: string, functionNamePattern: string): ResultSet {
        let cat = catalog
        if (cat == "") { cat = "%" }
        let pat = functionNamePattern
        if (pat == "") { pat = "%" }
        const sql = `SELECT ROUTINE_SCHEMA AS FUNCTION_CAT, NULL AS FUNCTION_SCHEM, ROUTINE_NAME AS FUNCTION_NAME, ROUTINE_COMMENT AS REMARKS, NULL AS FUNCTION_TYPE, ROUTINE_NAME AS SPECIFIC_NAME FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_TYPE = 'FUNCTION' AND ROUTINE_SCHEMA LIKE '${cat}' AND ROUTINE_NAME LIKE '${pat}' ORDER BY ROUTINE_SCHEMA, ROUTINE_NAME`
        return infoSchemaQuery(this.conn, sql)
    }
    function getFunctionColumns(catalog: string, schemaPattern: string, functionNamePattern: string, columnNamePattern: string): ResultSet {
        return emptyResultSetStub()
    }
}
