// MySQL JDBC driver — D134 Phase 5.
//
// class MysqlConnection : Connection and class MysqlStatement : Statement
// implement the lib/java/sql.ss D025 interfaces. ResultSet is implemented by
// class MysqlResultSet in lib/com/mysql/query.ss (Phase 4 — D025 §interface).
//
// getMysqlConnection parses a jdbc:mysql:// URL, calls handshake.mysqlConnect
// to authenticate, and wraps the authenticated fd in a MysqlConnection.
//
// Circular import note: this file imports lib/java/sql for the Connection /
// Statement / ResultSet interfaces; lib/java/sql imports getMysqlConnection
// from here for DriverManager_getConnection url dispatch. bootstrap/main.ss
// resolveInner (line 186-187) uses a visited set so the cycle expands cleanly —
// interfaces and classes are collected globally before method bodies resolve.
//
// Connection layering note: handshake.mysqlConnect returns the authenticated
// socket fd (D134 Phase 5 NAMESPACE COLLISION decision: handshake.ss owns auth
// protocol only, driver-layer Connection state lives here in jdbc.ss).

import { Connection, Statement, PreparedStatement, ResultSet } from "@/lib/java/sql"
import { writePacket } from "@/lib/com/mysql/wire"
import { mysqlConnect } from "@/lib/com/mysql/handshake"
import { sendQuery, readUpdateResultPacket, okPacketAffectedRows, okPacketLastInsertId, readQueryResultSet, MysqlResultSet, GeneratedKeyResultSet, NoopResultSetMetaData } from "@/lib/com/mysql/query"
import { doPrepare } from "@/lib/com/mysql/prepared"
import { URL, URL_parse } from "@/lib/url"

const COM_QUIT = 0x01
const DEFAULT_PORT = 3306
const URL_PREFIX = "jdbc:"

class MysqlConnection : Connection {
    fd: int
    autoCommit: int
    closed: int

    function createStatement(): Statement {
        return new MysqlStatement(this.fd, 0)
    }

    // Drives the full prepare flow via prepared.doPrepare — keeps PrepareOk
    // field access encapsulated inside prepared.ss (cross-module struct field
    // access from a function whose body emits before the struct's IR `type`
    // declaration would forward-reference the type and llc would reject the
    // GEP). Phase 1 occupies the prepare half of the protocol; setXxx and
    // executeQuery / executeUpdate / close are Phase 2 stubs.
    function prepareStatement(sql: string): PreparedStatement {
        return doPrepare(this.fd, sql)
    }

    // D138 Phase 2 — JDBC 4.3 §Connection.prepareStatement(sql, autoGeneratedKeys).
    // MySQL wire protocol returns lastInsertId in OkPacket for every INSERT, so
    // autoGeneratedKeys is informational only on this driver — both
    // RETURN_GENERATED_KEYS and NO_GENERATED_KEYS yield the same prepared
    // statement. Future PostgreSQL / SQLite drivers gating id retrieval will
    // read the flag here.
    function prepareStatement(sql: string, autoGeneratedKeys: int): PreparedStatement {
        return doPrepare(this.fd, sql)
    }

    // D146 Phase 3 — JDBC 4.3 §Connection.prepareStatement(sql, type, concurrency).
    // type / concurrency are stashed on the MysqlPreparedStatement so that the
    // 0-arg executeQuery() (PreparedStatement interface) can derive the
    // COM_STMT_EXECUTE cursor flag without needing the user to call the
    // driver-specific 3-arg overload. Scrollable type (TYPE_SCROLL_INSENSITIVE
    // / SENSITIVE) opens a server-side cursor + activates the in-memory cache
    // fallback (D146 §A.2 H5 — MySQL 5.7+ has no server scrollable cursor).
    function prepareStatement(sql: string, type: int, concurrency: int): PreparedStatement {
        const ps = doPrepare(this.fd, sql)
        ps.setCursorMode(type, concurrency)
        return ps
    }

    function setAutoCommit(auto: int) {
        if (this.autoCommit == auto) { return }
        let sql = "SET autocommit=0"
        if (auto == 1) { sql = "SET autocommit=1" }
        sendQuery(this.fd, sql)
        readUpdateResultPacket(this.fd)
        this.autoCommit = auto
    }

    function commit() {
        sendQuery(this.fd, "COMMIT")
        readUpdateResultPacket(this.fd)
    }

    function rollback() {
        sendQuery(this.fd, "ROLLBACK")
        readUpdateResultPacket(this.fd)
    }

    // COM_QUIT is a single 0x01 byte payload, seqId reset to 0. The server
    // closes the socket after receiving it; we close our end too.
    function close() {
        if (this.closed != 0) { return }
        writePacket(this.fd, 0, fromCharCode(COM_QUIT), 1)
        tcpClose(this.fd)
        this.closed = 1
    }

    function isClosed(): int {
        return this.closed
    }
}

class MysqlStatement : Statement {
    fd: int
    // Last lastInsertId from the most recent executeUpdate; ERR path throws
    // SQLException via readUpdateResultPacket so a failed INSERT never writes
    // here. Default 0 — JDBC 4.3 §Statement.getGeneratedKeys spec: "an empty
    // ResultSet" when no row was inserted.
    lastInsertId: int

    function executeQuery(sql: string): ResultSet {
        sendQuery(this.fd, sql)
        return readQueryResultSet(this.fd)
    }

    // D146 Phase 2 — JDBC 4.3 §Statement.executeQuery(sql, type, concurrency).
    // MySQL Statement (COM_QUERY 0x03) has no server-side cursor support —
    // type+concurrency are informational on this path. Server-side cursor lives
    // exclusively on PreparedStatement (Connection.prepareStatement(sql, type,
    // concurrency) + COM_STMT_EXECUTE flags CURSOR_TYPE_READ_ONLY 0x01).
    function executeQuery(sql: string, type: int, concurrency: int): ResultSet {
        sendQuery(this.fd, sql)
        return readQueryResultSet(this.fd)
    }

    function executeUpdate(sql: string): int {
        sendQuery(this.fd, sql)
        const ok = readUpdateResultPacket(this.fd)
        this.lastInsertId = okPacketLastInsertId(ok)
        return okPacketAffectedRows(ok)
    }

    function execute(sql: string): int {
        sendQuery(this.fd, sql)
        return okPacketAffectedRows(readUpdateResultPacket(this.fd))
    }

    // D138 Phase 2 — JDBC 4.3 §Statement.getGeneratedKeys returns a ResultSet over
    // the auto-increment ids generated by the most recent executeUpdate. Wraps
    // lastInsertId (single-row, single-column "GENERATED_KEY" — MySQL Connector/J
    // standard). Multi-row INSERT VALUES (...),(...) returns the first id only;
    // subsequent ids are first + 1, first + 2, ... by MySQL protocol contract.
    function getGeneratedKeys(): ResultSet {
        return new GeneratedKeyResultSet(this.lastInsertId, 0, new NoopResultSetMetaData(), 0)
    }

    function getLastInsertId(): int {
        return this.lastInsertId
    }

    // Statement does not own the socket fd — Connection does. close() at the
    // Statement layer is a no-op; ResultSet.close() drains the socket buffer.
    function close() {
    }
}

// Parses jdbc:mysql://[user[:pwd]@]host[:port]/[db][?param=val&...] and opens
// an authenticated connection. Any handshake/auth failure throws an
// SQLException subclass via mysqlConnect (D139 §核心原则 4 — no closed
// sentinel Connection; callers must use try/catch).
//
// JDBC URLs carry a double scheme (`jdbc:mysql:`) which RFC 3986 forbids
// (urlIsValidScheme rejects ':' inside scheme), so we strip the `jdbc:` prefix
// before delegating to URL_parse — `mysql://...` is then a normal URI.
//
// Phase 5 scope: query parameters after `?` are stripped (not consumed). User
// is "root", password "" and database "" by default; port defaults to 3306.
function getMysqlConnection(url: string): MysqlConnection {
    const stripped = url.substring(URL_PREFIX.length(), url.length() - URL_PREFIX.length())
    const u = URL_parse(stripped)

    let user = u.username()
    if (user == "") { user = "root" }
    const pwd = u.password()

    let host = u.hostname()
    if (host == "") { host = "127.0.0.1" }

    let port = DEFAULT_PORT
    const portStr = u.port()
    if (portStr != "") {
        const p = parseInt(portStr)
        if (p > 0) { port = p }
    }

    let db = ""
    const path = u.pathname()
    if (path.length() > 1) {
        db = path.substring(1, path.length() - 1)
    }

    const fd = mysqlConnect(host, port, user, pwd, db)
    return new MysqlConnection(fd, 1, 0)
}
