// gen_prelude_embed.ss — generate bootstrap/parse/prelude_embed.ss from prelude.ss
//
// Run from repo root after editing bootstrap/parse/prelude.ss:
//   bin/ss run tools/gen_prelude_embed.ss
//
// This embeds prelude.ss content as a string literal in a generated SS file
// so that the compiler binary becomes self-contained and works from any cwd.
// See D-doc on prelude embed (root cause fix for cwd-fragile prelude lookup).

function escapeForSS(s: string): string {
    let result = ""
    let i = 0
    const sLen = s.length()
    while (i < sLen) {
        const code = charCodeAt(s, i)
        if (code == 92) { result = result + "\\\\" }
        else if (code == 34) { result = result + "\\\"" }
        else if (code == 10) { result = result + "\\n" }
        else if (code == 13) { result = result + "\\r" }
        else if (code == 9) { result = result + "\\t" }
        else if (code == 96) { result = result + "\\`" }
        else if (code == 36) { result = result + "\\$" }
        else { result = result + fromCharCode(code) }
        i = i + 1
    }
    return result
}

function main() {
    const srcPath = "bootstrap/parse/prelude.ss"
    const dstPath = "bootstrap/parse/prelude_embed.ss"
    if (fileExists(srcPath) == 0) {
        println(`error: ${srcPath} not found (run from repo root)`)
        exit(1)
    }
    const content = readFile(srcPath)
    const escaped = escapeForSS(content)
    let out = "// AUTO-GENERATED by tools/gen_prelude_embed.ss — DO NOT EDIT\n"
    out = out + "// Source: bootstrap/parse/prelude.ss\n"
    out = out + "// Re-generate after editing prelude.ss:\n"
    out = out + "//   bin/ss run tools/gen_prelude_embed.ss\n"
    out = out + "\n"
    out = out + "function ssPreludeContent(): string {\n"
    out = out + "    return \"" + escaped + "\"\n"
    out = out + "}\n"
    writeFile(dstPath, out)
    println(`wrote ${dstPath} (${content.length()} bytes prelude → ${out.length()} bytes embed)`)
}
