[package]
name = "ss-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ss"
path = "src/main.rs"

[dependencies]
ss-lexer = { path = "../ss-lexer" }
ss-parser = { path = "../ss-parser" }
ss-checker = { path = "../ss-checker" }
ss-codegen = { path = "../ss-codegen" }
clap = { version = "4", features = ["derive"] }
inkwell = { version = "0.5", features = ["llvm18-0"] }
